/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as models from "../index.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import { SquadcastSDKError } from "./squadcastsdkerror.js";

/**
 * Server error
 */
export type GatewayTimeoutErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Server error
 */
export class GatewayTimeoutError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: GatewayTimeoutErrorData;

  constructor(
    err: GatewayTimeoutErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "GatewayTimeoutError";
  }
}

/**
 * Service unavailable.
 */
export type ServiceUnavailableErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Service unavailable.
 */
export class ServiceUnavailableError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: ServiceUnavailableErrorData;

  constructor(
    err: ServiceUnavailableErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "ServiceUnavailableError";
  }
}

/**
 * Server error
 */
export type BadGatewayErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Server error
 */
export class BadGatewayError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: BadGatewayErrorData;

  constructor(
    err: BadGatewayErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "BadGatewayError";
  }
}

/**
 * Server error
 */
export type InternalServerErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Server error
 */
export class InternalServerError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: InternalServerErrorData;

  constructor(
    err: InternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "InternalServerError";
  }
}

/**
 * Client error
 */
export type UnprocessableEntityErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Client error
 */
export class UnprocessableEntityError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: UnprocessableEntityErrorData;

  constructor(
    err: UnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "UnprocessableEntityError";
  }
}

/**
 * The request conflicts with the current state of the server.
 */
export type ConflictErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * The request conflicts with the current state of the server.
 */
export class ConflictError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: ConflictErrorData;

  constructor(
    err: ConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "ConflictError";
  }
}

/**
 * The server cannot find the requested resource.
 */
export type NotFoundErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * The server cannot find the requested resource.
 */
export class NotFoundError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorData;

  constructor(
    err: NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "NotFoundError";
  }
}

/**
 * Access is forbidden.
 */
export type ForbiddenErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Access is forbidden.
 */
export class ForbiddenError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorData;

  constructor(
    err: ForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "ForbiddenError";
  }
}

/**
 * Client error
 */
export type PaymentRequiredErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Client error
 */
export class PaymentRequiredError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: PaymentRequiredErrorData;

  constructor(
    err: PaymentRequiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "PaymentRequiredError";
  }
}

/**
 * Access is unauthorized.
 */
export type UnauthorizedErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * Access is unauthorized.
 */
export class UnauthorizedError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedErrorData;

  constructor(
    err: UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "UnauthorizedError";
  }
}

/**
 * The server could not understand the request due to invalid syntax.
 */
export type BadRequestErrorData = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

/**
 * The server could not understand the request due to invalid syntax.
 */
export class BadRequestError extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "BadRequestError";
  }
}

export type ResponseBodyError2Data = {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;
};

export class ResponseBodyError2 extends SquadcastSDKError {
  /**
   * Represents a single response containing data of type T.
   */
  meta: models.CommonV3ErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: ResponseBodyError2Data;

  constructor(
    err: ResponseBodyError2Data,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "ResponseBodyError2";
  }
}

export type ResponseBodyError1Data = {
  /**
   * Represents the metadata for a CircleCI error response.
   */
  meta: models.V3IncidentsIncidentActionsCircleCIErrorMeta;
};

export class ResponseBodyError1 extends SquadcastSDKError {
  /**
   * Represents the metadata for a CircleCI error response.
   */
  meta: models.V3IncidentsIncidentActionsCircleCIErrorMeta;

  /** The original data that was passed to this error instance. */
  data$: ResponseBodyError1Data;

  constructor(
    err: ResponseBodyError1Data,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.meta = err.meta;

    this.name = "ResponseBodyError1";
  }
}

/**
 * Represents a CircleCI error response for a 400 status code.
 */
export type BadRequest = ResponseBodyError1 | ResponseBodyError2;

/** @internal */
export const GatewayTimeoutError$inboundSchema: z.ZodType<
  GatewayTimeoutError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GatewayTimeoutError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const ServiceUnavailableError$inboundSchema: z.ZodType<
  ServiceUnavailableError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ServiceUnavailableError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const BadGatewayError$inboundSchema: z.ZodType<
  BadGatewayError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new BadGatewayError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const InternalServerError$inboundSchema: z.ZodType<
  InternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const UnprocessableEntityError$inboundSchema: z.ZodType<
  UnprocessableEntityError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UnprocessableEntityError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const ConflictError$inboundSchema: z.ZodType<
  ConflictError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const NotFoundError$inboundSchema: z.ZodType<
  NotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new NotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const ForbiddenError$inboundSchema: z.ZodType<
  ForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PaymentRequiredError$inboundSchema: z.ZodType<
  PaymentRequiredError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PaymentRequiredError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const UnauthorizedError$inboundSchema: z.ZodType<
  UnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const BadRequestError$inboundSchema: z.ZodType<
  BadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new BadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const ResponseBodyError2$inboundSchema: z.ZodType<
  ResponseBodyError2,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.CommonV3ErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ResponseBodyError2(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const ResponseBodyError1$inboundSchema: z.ZodType<
  ResponseBodyError1,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: models.V3IncidentsIncidentActionsCircleCIErrorMeta$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ResponseBodyError1(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const BadRequest$inboundSchema: z.ZodType<
  BadRequest,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ResponseBodyError1$inboundSchema),
  z.lazy(() => ResponseBodyError2$inboundSchema),
]);

export function badRequestFromJSON(
  jsonString: string,
): SafeParseResult<BadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadRequest' from JSON`,
  );
}
