/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AdditionalRespondersAddAdditionalRespondersRequest = {
  incidentID: string;
  v3IncidentsAdditionalRespondersAddAdditionalRespondersRequest:
    models.V3IncidentsAdditionalRespondersAddAdditionalRespondersRequest;
};

/**
 * The request has succeeded.
 */
export type AdditionalRespondersAddAdditionalRespondersResponse = {
  data: models.V3IncidentsAdditionalRespondersAdditionalResponderResponse;
};

/** @internal */
export type AdditionalRespondersAddAdditionalRespondersRequest$Outbound = {
  incidentID: string;
  "V3.Incidents.AdditionalResponders.AddAdditionalRespondersRequest":
    models.V3IncidentsAdditionalRespondersAddAdditionalRespondersRequest$Outbound;
};

/** @internal */
export const AdditionalRespondersAddAdditionalRespondersRequest$outboundSchema:
  z.ZodType<
    AdditionalRespondersAddAdditionalRespondersRequest$Outbound,
    z.ZodTypeDef,
    AdditionalRespondersAddAdditionalRespondersRequest
  > = z.object({
    incidentID: z.string(),
    v3IncidentsAdditionalRespondersAddAdditionalRespondersRequest:
      models
        .V3IncidentsAdditionalRespondersAddAdditionalRespondersRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      v3IncidentsAdditionalRespondersAddAdditionalRespondersRequest:
        "V3.Incidents.AdditionalResponders.AddAdditionalRespondersRequest",
    });
  });

export function additionalRespondersAddAdditionalRespondersRequestToJSON(
  additionalRespondersAddAdditionalRespondersRequest:
    AdditionalRespondersAddAdditionalRespondersRequest,
): string {
  return JSON.stringify(
    AdditionalRespondersAddAdditionalRespondersRequest$outboundSchema.parse(
      additionalRespondersAddAdditionalRespondersRequest,
    ),
  );
}

/** @internal */
export const AdditionalRespondersAddAdditionalRespondersResponse$inboundSchema:
  z.ZodType<
    AdditionalRespondersAddAdditionalRespondersResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V3IncidentsAdditionalRespondersAdditionalResponderResponse$inboundSchema,
  });

export function additionalRespondersAddAdditionalRespondersResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AdditionalRespondersAddAdditionalRespondersResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AdditionalRespondersAddAdditionalRespondersResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AdditionalRespondersAddAdditionalRespondersResponse' from JSON`,
  );
}
