/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdditionalRespondersRemoveAdditionalRespondersRequest = {
  incidentID: string;
  responderID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type AdditionalRespondersRemoveAdditionalRespondersResponseBody = {};

/** @internal */
export type AdditionalRespondersRemoveAdditionalRespondersRequest$Outbound = {
  incidentID: string;
  responderID: string;
};

/** @internal */
export const AdditionalRespondersRemoveAdditionalRespondersRequest$outboundSchema:
  z.ZodType<
    AdditionalRespondersRemoveAdditionalRespondersRequest$Outbound,
    z.ZodTypeDef,
    AdditionalRespondersRemoveAdditionalRespondersRequest
  > = z.object({
    incidentID: z.string(),
    responderID: z.string(),
  });

export function additionalRespondersRemoveAdditionalRespondersRequestToJSON(
  additionalRespondersRemoveAdditionalRespondersRequest:
    AdditionalRespondersRemoveAdditionalRespondersRequest,
): string {
  return JSON.stringify(
    AdditionalRespondersRemoveAdditionalRespondersRequest$outboundSchema.parse(
      additionalRespondersRemoveAdditionalRespondersRequest,
    ),
  );
}

/** @internal */
export const AdditionalRespondersRemoveAdditionalRespondersResponseBody$inboundSchema:
  z.ZodType<
    AdditionalRespondersRemoveAdditionalRespondersResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function additionalRespondersRemoveAdditionalRespondersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  AdditionalRespondersRemoveAdditionalRespondersResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AdditionalRespondersRemoveAdditionalRespondersResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'AdditionalRespondersRemoveAdditionalRespondersResponseBody' from JSON`,
  );
}
