/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AuditLogsGetAuditLogByIdRequest = {
  id: string;
};

/** @internal */
export type AuditLogsGetAuditLogByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const AuditLogsGetAuditLogByIdRequest$outboundSchema: z.ZodType<
  AuditLogsGetAuditLogByIdRequest$Outbound,
  z.ZodTypeDef,
  AuditLogsGetAuditLogByIdRequest
> = z.object({
  id: z.string(),
});

export function auditLogsGetAuditLogByIdRequestToJSON(
  auditLogsGetAuditLogByIdRequest: AuditLogsGetAuditLogByIdRequest,
): string {
  return JSON.stringify(
    AuditLogsGetAuditLogByIdRequest$outboundSchema.parse(
      auditLogsGetAuditLogByIdRequest,
    ),
  );
}
