/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const Client = {
  Web: "web",
  Mobile: "mobile",
  Terraform: "terraform",
} as const;
export type Client = ClosedEnum<typeof Client>;

export type AuditLogsListAuditLogsRequest = {
  pageSize: number;
  pageNumber: number;
  startDate: RFCDate;
  endDate: RFCDate;
  action?: Array<string> | undefined;
  resource?: Array<string> | undefined;
  actor?: Array<string> | undefined;
  team?: Array<string> | undefined;
  client?: Array<Client> | undefined;
};

export type AuditLogsListAuditLogsResponse = {
  result: models.V3AuditLogsListAuditLogsResponse;
};

/** @internal */
export const Client$outboundSchema: z.ZodNativeEnum<typeof Client> = z
  .nativeEnum(Client);

/** @internal */
export type AuditLogsListAuditLogsRequest$Outbound = {
  pageSize: number;
  pageNumber: number;
  startDate: string;
  endDate: string;
  "action[]"?: Array<string> | undefined;
  "resource[]"?: Array<string> | undefined;
  "actor[]"?: Array<string> | undefined;
  "team[]"?: Array<string> | undefined;
  "client[]"?: Array<string> | undefined;
};

/** @internal */
export const AuditLogsListAuditLogsRequest$outboundSchema: z.ZodType<
  AuditLogsListAuditLogsRequest$Outbound,
  z.ZodTypeDef,
  AuditLogsListAuditLogsRequest
> = z.object({
  pageSize: z.number().int(),
  pageNumber: z.number().int(),
  startDate: z.instanceof(RFCDate).transform(v => v.toString()),
  endDate: z.instanceof(RFCDate).transform(v => v.toString()),
  action: z.array(z.string()).optional(),
  resource: z.array(z.string()).optional(),
  actor: z.array(z.string()).optional(),
  team: z.array(z.string()).optional(),
  client: z.array(Client$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    action: "action[]",
    resource: "resource[]",
    actor: "actor[]",
    team: "team[]",
    client: "client[]",
  });
});

export function auditLogsListAuditLogsRequestToJSON(
  auditLogsListAuditLogsRequest: AuditLogsListAuditLogsRequest,
): string {
  return JSON.stringify(
    AuditLogsListAuditLogsRequest$outboundSchema.parse(
      auditLogsListAuditLogsRequest,
    ),
  );
}

/** @internal */
export const AuditLogsListAuditLogsResponse$inboundSchema: z.ZodType<
  AuditLogsListAuditLogsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.V3AuditLogsListAuditLogsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function auditLogsListAuditLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AuditLogsListAuditLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditLogsListAuditLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditLogsListAuditLogsResponse' from JSON`,
  );
}
