/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AuditLogsGetAuditLogsExportHistoryByIdRequest = {
  id: string;
};

/** @internal */
export type AuditLogsGetAuditLogsExportHistoryByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const AuditLogsGetAuditLogsExportHistoryByIdRequest$outboundSchema:
  z.ZodType<
    AuditLogsGetAuditLogsExportHistoryByIdRequest$Outbound,
    z.ZodTypeDef,
    AuditLogsGetAuditLogsExportHistoryByIdRequest
  > = z.object({
    id: z.string(),
  });

export function auditLogsGetAuditLogsExportHistoryByIdRequestToJSON(
  auditLogsGetAuditLogsExportHistoryByIdRequest:
    AuditLogsGetAuditLogsExportHistoryByIdRequest,
): string {
  return JSON.stringify(
    AuditLogsGetAuditLogsExportHistoryByIdRequest$outboundSchema.parse(
      auditLogsGetAuditLogsExportHistoryByIdRequest,
    ),
  );
}
