/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded.
 */
export type CommunicationCardsCreateSlackChannelInCommunicationCardResponse = {
  data: models.V3IncidentsCommunicationCardsCommunicationCardResponse;
};

/** @internal */
export const CommunicationCardsCreateSlackChannelInCommunicationCardResponse$inboundSchema:
  z.ZodType<
    CommunicationCardsCreateSlackChannelInCommunicationCardResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema,
  });

export function communicationCardsCreateSlackChannelInCommunicationCardResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CommunicationCardsCreateSlackChannelInCommunicationCardResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CommunicationCardsCreateSlackChannelInCommunicationCardResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CommunicationCardsCreateSlackChannelInCommunicationCardResponse' from JSON`,
  );
}
