/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CommunicationCardsCreateCommunicationCardRequest = {
  /**
   * Required
   */
  incidentId: string;
  v3IncidentsCommunicationCardsCreateCommunicationCardRequest:
    models.V3IncidentsCommunicationCardsCreateCommunicationCardRequest;
};

/**
 * The request has succeeded.
 */
export type CommunicationCardsCreateCommunicationCardResponse = {
  data: models.V3IncidentsCommunicationCardsCommunicationCardResponse;
};

/** @internal */
export type CommunicationCardsCreateCommunicationCardRequest$Outbound = {
  IncidentId: string;
  "V3.Incidents.CommunicationCards.CreateCommunicationCardRequest":
    models.V3IncidentsCommunicationCardsCreateCommunicationCardRequest$Outbound;
};

/** @internal */
export const CommunicationCardsCreateCommunicationCardRequest$outboundSchema:
  z.ZodType<
    CommunicationCardsCreateCommunicationCardRequest$Outbound,
    z.ZodTypeDef,
    CommunicationCardsCreateCommunicationCardRequest
  > = z.object({
    incidentId: z.string(),
    v3IncidentsCommunicationCardsCreateCommunicationCardRequest:
      models
        .V3IncidentsCommunicationCardsCreateCommunicationCardRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      incidentId: "IncidentId",
      v3IncidentsCommunicationCardsCreateCommunicationCardRequest:
        "V3.Incidents.CommunicationCards.CreateCommunicationCardRequest",
    });
  });

export function communicationCardsCreateCommunicationCardRequestToJSON(
  communicationCardsCreateCommunicationCardRequest:
    CommunicationCardsCreateCommunicationCardRequest,
): string {
  return JSON.stringify(
    CommunicationCardsCreateCommunicationCardRequest$outboundSchema.parse(
      communicationCardsCreateCommunicationCardRequest,
    ),
  );
}

/** @internal */
export const CommunicationCardsCreateCommunicationCardResponse$inboundSchema:
  z.ZodType<
    CommunicationCardsCreateCommunicationCardResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema,
  });

export function communicationCardsCreateCommunicationCardResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CommunicationCardsCreateCommunicationCardResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CommunicationCardsCreateCommunicationCardResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CommunicationCardsCreateCommunicationCardResponse' from JSON`,
  );
}
