/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ComponentGroupsCreateComponentGroupRequest = {
  statuspageID: string;
  v4StatusPagesComponentGroupsCreateComponentGroupRequest:
    models.V4StatusPagesComponentGroupsCreateComponentGroupRequest;
};

/**
 * The request has succeeded.
 */
export type ComponentGroupsCreateComponentGroupResponse = {
  data: models.V4StatusPagesComponentGroupsCreateComponentGroupResponse;
};

/** @internal */
export type ComponentGroupsCreateComponentGroupRequest$Outbound = {
  statuspageID: string;
  "V4.StatusPages.ComponentGroups.CreateComponentGroupRequest":
    models.V4StatusPagesComponentGroupsCreateComponentGroupRequest$Outbound;
};

/** @internal */
export const ComponentGroupsCreateComponentGroupRequest$outboundSchema:
  z.ZodType<
    ComponentGroupsCreateComponentGroupRequest$Outbound,
    z.ZodTypeDef,
    ComponentGroupsCreateComponentGroupRequest
  > = z.object({
    statuspageID: z.string(),
    v4StatusPagesComponentGroupsCreateComponentGroupRequest:
      models
        .V4StatusPagesComponentGroupsCreateComponentGroupRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      v4StatusPagesComponentGroupsCreateComponentGroupRequest:
        "V4.StatusPages.ComponentGroups.CreateComponentGroupRequest",
    });
  });

export function componentGroupsCreateComponentGroupRequestToJSON(
  componentGroupsCreateComponentGroupRequest:
    ComponentGroupsCreateComponentGroupRequest,
): string {
  return JSON.stringify(
    ComponentGroupsCreateComponentGroupRequest$outboundSchema.parse(
      componentGroupsCreateComponentGroupRequest,
    ),
  );
}

/** @internal */
export const ComponentGroupsCreateComponentGroupResponse$inboundSchema:
  z.ZodType<
    ComponentGroupsCreateComponentGroupResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data:
      models
        .V4StatusPagesComponentGroupsCreateComponentGroupResponse$inboundSchema,
  });

export function componentGroupsCreateComponentGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComponentGroupsCreateComponentGroupResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComponentGroupsCreateComponentGroupResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComponentGroupsCreateComponentGroupResponse' from JSON`,
  );
}
