/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ComponentGroupsListComponentGroupsRequest = {
  statuspageID: string;
};

/**
 * The request has succeeded.
 */
export type ComponentGroupsListComponentGroupsResponse = {
  data: Array<models.V4StatusPagesComponentGroupsComponentGroupResponse>;
};

/** @internal */
export type ComponentGroupsListComponentGroupsRequest$Outbound = {
  statuspageID: string;
};

/** @internal */
export const ComponentGroupsListComponentGroupsRequest$outboundSchema:
  z.ZodType<
    ComponentGroupsListComponentGroupsRequest$Outbound,
    z.ZodTypeDef,
    ComponentGroupsListComponentGroupsRequest
  > = z.object({
    statuspageID: z.string(),
  });

export function componentGroupsListComponentGroupsRequestToJSON(
  componentGroupsListComponentGroupsRequest:
    ComponentGroupsListComponentGroupsRequest,
): string {
  return JSON.stringify(
    ComponentGroupsListComponentGroupsRequest$outboundSchema.parse(
      componentGroupsListComponentGroupsRequest,
    ),
  );
}

/** @internal */
export const ComponentGroupsListComponentGroupsResponse$inboundSchema:
  z.ZodType<ComponentGroupsListComponentGroupsResponse, z.ZodTypeDef, unknown> =
    z.object({
      data: z.array(
        models.V4StatusPagesComponentGroupsComponentGroupResponse$inboundSchema,
      ),
    });

export function componentGroupsListComponentGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ComponentGroupsListComponentGroupsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ComponentGroupsListComponentGroupsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ComponentGroupsListComponentGroupsResponse' from JSON`,
  );
}
