/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeduplicationRulesGetDeduplicationRulesRequest = {
  serviceID: string;
};

export type DeduplicationRulesGetDeduplicationRulesData = {
  rules: Array<models.V3ServicesDeduplicationRulesDeduplicationRuleResponse>;
};

/**
 * The request has succeeded.
 */
export type DeduplicationRulesGetDeduplicationRulesResponse = {
  data: DeduplicationRulesGetDeduplicationRulesData;
};

/** @internal */
export type DeduplicationRulesGetDeduplicationRulesRequest$Outbound = {
  serviceID: string;
};

/** @internal */
export const DeduplicationRulesGetDeduplicationRulesRequest$outboundSchema:
  z.ZodType<
    DeduplicationRulesGetDeduplicationRulesRequest$Outbound,
    z.ZodTypeDef,
    DeduplicationRulesGetDeduplicationRulesRequest
  > = z.object({
    serviceID: z.string(),
  });

export function deduplicationRulesGetDeduplicationRulesRequestToJSON(
  deduplicationRulesGetDeduplicationRulesRequest:
    DeduplicationRulesGetDeduplicationRulesRequest,
): string {
  return JSON.stringify(
    DeduplicationRulesGetDeduplicationRulesRequest$outboundSchema.parse(
      deduplicationRulesGetDeduplicationRulesRequest,
    ),
  );
}

/** @internal */
export const DeduplicationRulesGetDeduplicationRulesData$inboundSchema:
  z.ZodType<
    DeduplicationRulesGetDeduplicationRulesData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    rules: z.array(
      models
        .V3ServicesDeduplicationRulesDeduplicationRuleResponse$inboundSchema,
    ),
  });

export function deduplicationRulesGetDeduplicationRulesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  DeduplicationRulesGetDeduplicationRulesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeduplicationRulesGetDeduplicationRulesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeduplicationRulesGetDeduplicationRulesData' from JSON`,
  );
}

/** @internal */
export const DeduplicationRulesGetDeduplicationRulesResponse$inboundSchema:
  z.ZodType<
    DeduplicationRulesGetDeduplicationRulesResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      DeduplicationRulesGetDeduplicationRulesData$inboundSchema
    ),
  });

export function deduplicationRulesGetDeduplicationRulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeduplicationRulesGetDeduplicationRulesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeduplicationRulesGetDeduplicationRulesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeduplicationRulesGetDeduplicationRulesResponse' from JSON`,
  );
}
