/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DependenciesCreateOrUpdateDependenciesRequest = {
  serviceID: string;
  v3ServicesDependenciesCreateOrUpdateDependenciesRequest:
    models.V3ServicesDependenciesCreateOrUpdateDependenciesRequest;
};

export type DependenciesCreateOrUpdateDependenciesData = {
  ok: boolean;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type DependenciesCreateOrUpdateDependenciesResponse = {
  data: DependenciesCreateOrUpdateDependenciesData;
};

/** @internal */
export type DependenciesCreateOrUpdateDependenciesRequest$Outbound = {
  serviceID: string;
  "V3.Services.Dependencies.CreateOrUpdateDependenciesRequest":
    models.V3ServicesDependenciesCreateOrUpdateDependenciesRequest$Outbound;
};

/** @internal */
export const DependenciesCreateOrUpdateDependenciesRequest$outboundSchema:
  z.ZodType<
    DependenciesCreateOrUpdateDependenciesRequest$Outbound,
    z.ZodTypeDef,
    DependenciesCreateOrUpdateDependenciesRequest
  > = z.object({
    serviceID: z.string(),
    v3ServicesDependenciesCreateOrUpdateDependenciesRequest:
      models
        .V3ServicesDependenciesCreateOrUpdateDependenciesRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      v3ServicesDependenciesCreateOrUpdateDependenciesRequest:
        "V3.Services.Dependencies.CreateOrUpdateDependenciesRequest",
    });
  });

export function dependenciesCreateOrUpdateDependenciesRequestToJSON(
  dependenciesCreateOrUpdateDependenciesRequest:
    DependenciesCreateOrUpdateDependenciesRequest,
): string {
  return JSON.stringify(
    DependenciesCreateOrUpdateDependenciesRequest$outboundSchema.parse(
      dependenciesCreateOrUpdateDependenciesRequest,
    ),
  );
}

/** @internal */
export const DependenciesCreateOrUpdateDependenciesData$inboundSchema:
  z.ZodType<DependenciesCreateOrUpdateDependenciesData, z.ZodTypeDef, unknown> =
    z.object({
      ok: z.boolean(),
    });

export function dependenciesCreateOrUpdateDependenciesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  DependenciesCreateOrUpdateDependenciesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DependenciesCreateOrUpdateDependenciesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DependenciesCreateOrUpdateDependenciesData' from JSON`,
  );
}

/** @internal */
export const DependenciesCreateOrUpdateDependenciesResponse$inboundSchema:
  z.ZodType<
    DependenciesCreateOrUpdateDependenciesResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      DependenciesCreateOrUpdateDependenciesData$inboundSchema
    ),
  });

export function dependenciesCreateOrUpdateDependenciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DependenciesCreateOrUpdateDependenciesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DependenciesCreateOrUpdateDependenciesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DependenciesCreateOrUpdateDependenciesResponse' from JSON`,
  );
}
