/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type EscalationPoliciesUpdateEscalationPolicyRequest = {
  /**
   * (Required) escalation policy ID
   */
  escalationPolicyID: string;
  v3EscalationPoliciesUpdateEscalationPolicyRequest:
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array;
};

/**
 * The request has succeeded.
 */
export type EscalationPoliciesUpdateEscalationPolicyResponse = {
  /**
   * Represents an Escalation Policy in the system.
   */
  data: models.V3EscalationPoliciesEscalationPolicyResponse;
};

/** @internal */
export type EscalationPoliciesUpdateEscalationPolicyRequest$Outbound = {
  escalationPolicyID: string;
  "V3.EscalationPolicies.UpdateEscalationPolicyRequest":
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Uint8Array;
};

/** @internal */
export const EscalationPoliciesUpdateEscalationPolicyRequest$outboundSchema:
  z.ZodType<
    EscalationPoliciesUpdateEscalationPolicyRequest$Outbound,
    z.ZodTypeDef,
    EscalationPoliciesUpdateEscalationPolicyRequest
  > = z.object({
    escalationPolicyID: z.string(),
    v3EscalationPoliciesUpdateEscalationPolicyRequest: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  }).transform((v) => {
    return remap$(v, {
      v3EscalationPoliciesUpdateEscalationPolicyRequest:
        "V3.EscalationPolicies.UpdateEscalationPolicyRequest",
    });
  });

export function escalationPoliciesUpdateEscalationPolicyRequestToJSON(
  escalationPoliciesUpdateEscalationPolicyRequest:
    EscalationPoliciesUpdateEscalationPolicyRequest,
): string {
  return JSON.stringify(
    EscalationPoliciesUpdateEscalationPolicyRequest$outboundSchema.parse(
      escalationPoliciesUpdateEscalationPolicyRequest,
    ),
  );
}

/** @internal */
export const EscalationPoliciesUpdateEscalationPolicyResponse$inboundSchema:
  z.ZodType<
    EscalationPoliciesUpdateEscalationPolicyResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: models.V3EscalationPoliciesEscalationPolicyResponse$inboundSchema,
  });

export function escalationPoliciesUpdateEscalationPolicyResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  EscalationPoliciesUpdateEscalationPolicyResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EscalationPoliciesUpdateEscalationPolicyResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EscalationPoliciesUpdateEscalationPolicyResponse' from JSON`,
  );
}
