/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ExportCreateScheduleIcalLinkRequestBody = {};

export type ExportCreateScheduleIcalLinkRequest = {
  scheduleID: string;
  myOnCall: boolean;
  requestBody: ExportCreateScheduleIcalLinkRequestBody;
};

/**
 * The request has succeeded.
 */
export type ExportCreateScheduleIcalLinkResponse = {
  data: models.V4ICalLinkResponse;
};

/** @internal */
export type ExportCreateScheduleIcalLinkRequestBody$Outbound = {};

/** @internal */
export const ExportCreateScheduleIcalLinkRequestBody$outboundSchema: z.ZodType<
  ExportCreateScheduleIcalLinkRequestBody$Outbound,
  z.ZodTypeDef,
  ExportCreateScheduleIcalLinkRequestBody
> = z.object({});

export function exportCreateScheduleIcalLinkRequestBodyToJSON(
  exportCreateScheduleIcalLinkRequestBody:
    ExportCreateScheduleIcalLinkRequestBody,
): string {
  return JSON.stringify(
    ExportCreateScheduleIcalLinkRequestBody$outboundSchema.parse(
      exportCreateScheduleIcalLinkRequestBody,
    ),
  );
}

/** @internal */
export type ExportCreateScheduleIcalLinkRequest$Outbound = {
  scheduleID: string;
  myOnCall: boolean;
  RequestBody: ExportCreateScheduleIcalLinkRequestBody$Outbound;
};

/** @internal */
export const ExportCreateScheduleIcalLinkRequest$outboundSchema: z.ZodType<
  ExportCreateScheduleIcalLinkRequest$Outbound,
  z.ZodTypeDef,
  ExportCreateScheduleIcalLinkRequest
> = z.object({
  scheduleID: z.string(),
  myOnCall: z.boolean(),
  requestBody: z.lazy(() =>
    ExportCreateScheduleIcalLinkRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function exportCreateScheduleIcalLinkRequestToJSON(
  exportCreateScheduleIcalLinkRequest: ExportCreateScheduleIcalLinkRequest,
): string {
  return JSON.stringify(
    ExportCreateScheduleIcalLinkRequest$outboundSchema.parse(
      exportCreateScheduleIcalLinkRequest,
    ),
  );
}

/** @internal */
export const ExportCreateScheduleIcalLinkResponse$inboundSchema: z.ZodType<
  ExportCreateScheduleIcalLinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4ICalLinkResponse$inboundSchema,
});

export function exportCreateScheduleIcalLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExportCreateScheduleIcalLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ExportCreateScheduleIcalLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExportCreateScheduleIcalLinkResponse' from JSON`,
  );
}
