/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExportDeleteIcalLinkRequest = {
  scheduleID: string;
  myOnCall: boolean;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type ExportDeleteIcalLinkResponseBody = {};

/** @internal */
export type ExportDeleteIcalLinkRequest$Outbound = {
  scheduleID: string;
  myOnCall: boolean;
};

/** @internal */
export const ExportDeleteIcalLinkRequest$outboundSchema: z.ZodType<
  ExportDeleteIcalLinkRequest$Outbound,
  z.ZodTypeDef,
  ExportDeleteIcalLinkRequest
> = z.object({
  scheduleID: z.string(),
  myOnCall: z.boolean(),
});

export function exportDeleteIcalLinkRequestToJSON(
  exportDeleteIcalLinkRequest: ExportDeleteIcalLinkRequest,
): string {
  return JSON.stringify(
    ExportDeleteIcalLinkRequest$outboundSchema.parse(
      exportDeleteIcalLinkRequest,
    ),
  );
}

/** @internal */
export const ExportDeleteIcalLinkResponseBody$inboundSchema: z.ZodType<
  ExportDeleteIcalLinkResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function exportDeleteIcalLinkResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ExportDeleteIcalLinkResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExportDeleteIcalLinkResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExportDeleteIcalLinkResponseBody' from JSON`,
  );
}
