/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GlobalEventRulesListGlobalEventRulesRequest = {
  ownerId: string;
  pageSize?: number | undefined;
  pageNumber?: number | undefined;
  filtersOwnerId?: Array<string> | undefined;
  filtersSearch?: string | undefined;
};

export type GlobalEventRulesListGlobalEventRulesMeta = {
  totalCount: number;
};

/**
 * The request has succeeded.
 */
export type GlobalEventRulesListGlobalEventRulesResponseBody = {
  data: Array<models.V3GlobalEventRulesGlobalEventRuleInList>;
  meta: GlobalEventRulesListGlobalEventRulesMeta;
};

export type GlobalEventRulesListGlobalEventRulesResponse = {
  result: GlobalEventRulesListGlobalEventRulesResponseBody;
};

/** @internal */
export type GlobalEventRulesListGlobalEventRulesRequest$Outbound = {
  owner_id: string;
  page_size?: number | undefined;
  page_number?: number | undefined;
  "filters.owner_id[]"?: Array<string> | undefined;
  "filters.search"?: string | undefined;
};

/** @internal */
export const GlobalEventRulesListGlobalEventRulesRequest$outboundSchema:
  z.ZodType<
    GlobalEventRulesListGlobalEventRulesRequest$Outbound,
    z.ZodTypeDef,
    GlobalEventRulesListGlobalEventRulesRequest
  > = z.object({
    ownerId: z.string(),
    pageSize: z.number().int().optional(),
    pageNumber: z.number().int().optional(),
    filtersOwnerId: z.array(z.string()).optional(),
    filtersSearch: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      ownerId: "owner_id",
      pageSize: "page_size",
      pageNumber: "page_number",
      filtersOwnerId: "filters.owner_id[]",
      filtersSearch: "filters.search",
    });
  });

export function globalEventRulesListGlobalEventRulesRequestToJSON(
  globalEventRulesListGlobalEventRulesRequest:
    GlobalEventRulesListGlobalEventRulesRequest,
): string {
  return JSON.stringify(
    GlobalEventRulesListGlobalEventRulesRequest$outboundSchema.parse(
      globalEventRulesListGlobalEventRulesRequest,
    ),
  );
}

/** @internal */
export const GlobalEventRulesListGlobalEventRulesMeta$inboundSchema: z.ZodType<
  GlobalEventRulesListGlobalEventRulesMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  total_count: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function globalEventRulesListGlobalEventRulesMetaFromJSON(
  jsonString: string,
): SafeParseResult<
  GlobalEventRulesListGlobalEventRulesMeta,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesListGlobalEventRulesMeta$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GlobalEventRulesListGlobalEventRulesMeta' from JSON`,
  );
}

/** @internal */
export const GlobalEventRulesListGlobalEventRulesResponseBody$inboundSchema:
  z.ZodType<
    GlobalEventRulesListGlobalEventRulesResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.array(models.V3GlobalEventRulesGlobalEventRuleInList$inboundSchema),
    meta: z.lazy(() => GlobalEventRulesListGlobalEventRulesMeta$inboundSchema),
  });

export function globalEventRulesListGlobalEventRulesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GlobalEventRulesListGlobalEventRulesResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesListGlobalEventRulesResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GlobalEventRulesListGlobalEventRulesResponseBody' from JSON`,
  );
}

/** @internal */
export const GlobalEventRulesListGlobalEventRulesResponse$inboundSchema:
  z.ZodType<
    GlobalEventRulesListGlobalEventRulesResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Result: z.lazy(() =>
      GlobalEventRulesListGlobalEventRulesResponseBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  });

export function globalEventRulesListGlobalEventRulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GlobalEventRulesListGlobalEventRulesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesListGlobalEventRulesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GlobalEventRulesListGlobalEventRulesResponse' from JSON`,
  );
}
