/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GlobalEventRulesUpdateGlobalEventRuleByIdRequest = {
  gerId: number;
  v3GlobalEventRulesUpdateGlobalEventRuleRequest:
    models.V3GlobalEventRulesUpdateGlobalEventRuleRequest;
};

/**
 * The request has succeeded.
 */
export type GlobalEventRulesUpdateGlobalEventRuleByIdResponse = {
  data: models.V3GlobalEventRulesGlobalEventRuleResponse;
};

/** @internal */
export type GlobalEventRulesUpdateGlobalEventRuleByIdRequest$Outbound = {
  ger_id: number;
  "V3.GlobalEventRules.UpdateGlobalEventRuleRequest":
    models.V3GlobalEventRulesUpdateGlobalEventRuleRequest$Outbound;
};

/** @internal */
export const GlobalEventRulesUpdateGlobalEventRuleByIdRequest$outboundSchema:
  z.ZodType<
    GlobalEventRulesUpdateGlobalEventRuleByIdRequest$Outbound,
    z.ZodTypeDef,
    GlobalEventRulesUpdateGlobalEventRuleByIdRequest
  > = z.object({
    gerId: z.number().int(),
    v3GlobalEventRulesUpdateGlobalEventRuleRequest:
      models.V3GlobalEventRulesUpdateGlobalEventRuleRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      gerId: "ger_id",
      v3GlobalEventRulesUpdateGlobalEventRuleRequest:
        "V3.GlobalEventRules.UpdateGlobalEventRuleRequest",
    });
  });

export function globalEventRulesUpdateGlobalEventRuleByIdRequestToJSON(
  globalEventRulesUpdateGlobalEventRuleByIdRequest:
    GlobalEventRulesUpdateGlobalEventRuleByIdRequest,
): string {
  return JSON.stringify(
    GlobalEventRulesUpdateGlobalEventRuleByIdRequest$outboundSchema.parse(
      globalEventRulesUpdateGlobalEventRuleByIdRequest,
    ),
  );
}

/** @internal */
export const GlobalEventRulesUpdateGlobalEventRuleByIdResponse$inboundSchema:
  z.ZodType<
    GlobalEventRulesUpdateGlobalEventRuleByIdResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: models.V3GlobalEventRulesGlobalEventRuleResponse$inboundSchema,
  });

export function globalEventRulesUpdateGlobalEventRuleByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GlobalEventRulesUpdateGlobalEventRuleByIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesUpdateGlobalEventRuleByIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GlobalEventRulesUpdateGlobalEventRuleByIdResponse' from JSON`,
  );
}
