/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type GlobalEventRulesCreateGlobalEventRuleResponse = {
  data: models.V3GlobalEventRulesCreatedGlobalEventRuleResponse;
};

/** @internal */
export const GlobalEventRulesCreateGlobalEventRuleResponse$inboundSchema:
  z.ZodType<
    GlobalEventRulesCreateGlobalEventRuleResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: models.V3GlobalEventRulesCreatedGlobalEventRuleResponse$inboundSchema,
  });

export function globalEventRulesCreateGlobalEventRuleResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GlobalEventRulesCreateGlobalEventRuleResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesCreateGlobalEventRuleResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GlobalEventRulesCreateGlobalEventRuleResponse' from JSON`,
  );
}
