/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GlobalEventRulesGetRulesetRequest = {
  gerId: number;
  alertSourceVersion: string;
  alertSourceShortname: string;
};

/**
 * The request has succeeded.
 */
export type GlobalEventRulesGetRulesetResponse = {
  data: models.V3GlobalEventRulesRulesetResponse;
};

/** @internal */
export type GlobalEventRulesGetRulesetRequest$Outbound = {
  ger_id: number;
  alert_source_version: string;
  alert_source_shortname: string;
};

/** @internal */
export const GlobalEventRulesGetRulesetRequest$outboundSchema: z.ZodType<
  GlobalEventRulesGetRulesetRequest$Outbound,
  z.ZodTypeDef,
  GlobalEventRulesGetRulesetRequest
> = z.object({
  gerId: z.number().int(),
  alertSourceVersion: z.string(),
  alertSourceShortname: z.string(),
}).transform((v) => {
  return remap$(v, {
    gerId: "ger_id",
    alertSourceVersion: "alert_source_version",
    alertSourceShortname: "alert_source_shortname",
  });
});

export function globalEventRulesGetRulesetRequestToJSON(
  globalEventRulesGetRulesetRequest: GlobalEventRulesGetRulesetRequest,
): string {
  return JSON.stringify(
    GlobalEventRulesGetRulesetRequest$outboundSchema.parse(
      globalEventRulesGetRulesetRequest,
    ),
  );
}

/** @internal */
export const GlobalEventRulesGetRulesetResponse$inboundSchema: z.ZodType<
  GlobalEventRulesGetRulesetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3GlobalEventRulesRulesetResponse$inboundSchema,
});

export function globalEventRulesGetRulesetResponseFromJSON(
  jsonString: string,
): SafeParseResult<GlobalEventRulesGetRulesetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GlobalEventRulesGetRulesetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GlobalEventRulesGetRulesetResponse' from JSON`,
  );
}
