/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RequestsStatus = {};

export type IncidentsGetIncidentsStatusByRequestidsMeta = {
  errorCount: number;
  successCount: number;
};

/**
 * The request has succeeded.
 */
export type IncidentsGetIncidentsStatusByRequestidsResponse = {
  requestsStatus: RequestsStatus;
  meta: IncidentsGetIncidentsStatusByRequestidsMeta;
};

/** @internal */
export const RequestsStatus$inboundSchema: z.ZodType<
  RequestsStatus,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function requestsStatusFromJSON(
  jsonString: string,
): SafeParseResult<RequestsStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RequestsStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequestsStatus' from JSON`,
  );
}

/** @internal */
export const IncidentsGetIncidentsStatusByRequestidsMeta$inboundSchema:
  z.ZodType<
    IncidentsGetIncidentsStatusByRequestidsMeta,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error_count: z.number().int(),
    success_count: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "error_count": "errorCount",
      "success_count": "successCount",
    });
  });

export function incidentsGetIncidentsStatusByRequestidsMetaFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentsGetIncidentsStatusByRequestidsMeta,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentsGetIncidentsStatusByRequestidsMeta$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentsGetIncidentsStatusByRequestidsMeta' from JSON`,
  );
}

/** @internal */
export const IncidentsGetIncidentsStatusByRequestidsResponse$inboundSchema:
  z.ZodType<
    IncidentsGetIncidentsStatusByRequestidsResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    requests_status: z.lazy(() => RequestsStatus$inboundSchema),
    meta: z.lazy(() =>
      IncidentsGetIncidentsStatusByRequestidsMeta$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "requests_status": "requestsStatus",
    });
  });

export function incidentsGetIncidentsStatusByRequestidsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentsGetIncidentsStatusByRequestidsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentsGetIncidentsStatusByRequestidsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentsGetIncidentsStatusByRequestidsResponse' from JSON`,
  );
}
