/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IncidentsAcknowledgeIncidentRequest = {
  incidentID: string;
};

/**
 * The request has succeeded.
 */
export type IncidentsAcknowledgeIncidentResponse = {
  data: string;
};

/** @internal */
export type IncidentsAcknowledgeIncidentRequest$Outbound = {
  incidentID: string;
};

/** @internal */
export const IncidentsAcknowledgeIncidentRequest$outboundSchema: z.ZodType<
  IncidentsAcknowledgeIncidentRequest$Outbound,
  z.ZodTypeDef,
  IncidentsAcknowledgeIncidentRequest
> = z.object({
  incidentID: z.string(),
});

export function incidentsAcknowledgeIncidentRequestToJSON(
  incidentsAcknowledgeIncidentRequest: IncidentsAcknowledgeIncidentRequest,
): string {
  return JSON.stringify(
    IncidentsAcknowledgeIncidentRequest$outboundSchema.parse(
      incidentsAcknowledgeIncidentRequest,
    ),
  );
}

/** @internal */
export const IncidentsAcknowledgeIncidentResponse$inboundSchema: z.ZodType<
  IncidentsAcknowledgeIncidentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string(),
});

export function incidentsAcknowledgeIncidentResponseFromJSON(
  jsonString: string,
): SafeParseResult<IncidentsAcknowledgeIncidentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentsAcknowledgeIncidentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentsAcknowledgeIncidentResponse' from JSON`,
  );
}
