/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type IncidentsMergeIncidentsRequest =
  | models.V3IncidentsMergeIntoExistingParentRequest
  | models.V3IncidentsMergeIntoNewParentRequest;

/**
 * The request has succeeded.
 */
export type IncidentsMergeIncidentsResponse = {
  /**
   * Result of merging incidents.
   */
  data: models.V3IncidentsMergeIncidentsResponse;
};

/** @internal */
export type IncidentsMergeIncidentsRequest$Outbound =
  | models.V3IncidentsMergeIntoExistingParentRequest$Outbound
  | models.V3IncidentsMergeIntoNewParentRequest$Outbound;

/** @internal */
export const IncidentsMergeIncidentsRequest$outboundSchema: z.ZodType<
  IncidentsMergeIncidentsRequest$Outbound,
  z.ZodTypeDef,
  IncidentsMergeIncidentsRequest
> = z.union([
  models.V3IncidentsMergeIntoExistingParentRequest$outboundSchema,
  models.V3IncidentsMergeIntoNewParentRequest$outboundSchema,
]);

export function incidentsMergeIncidentsRequestToJSON(
  incidentsMergeIncidentsRequest: IncidentsMergeIncidentsRequest,
): string {
  return JSON.stringify(
    IncidentsMergeIncidentsRequest$outboundSchema.parse(
      incidentsMergeIncidentsRequest,
    ),
  );
}

/** @internal */
export const IncidentsMergeIncidentsResponse$inboundSchema: z.ZodType<
  IncidentsMergeIncidentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3IncidentsMergeIncidentsResponse$inboundSchema,
});

export function incidentsMergeIncidentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<IncidentsMergeIncidentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentsMergeIncidentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentsMergeIncidentsResponse' from JSON`,
  );
}
