/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has been accepted for processing, but processing has not yet completed.
 */
export type IncidentsIncidentExportAsyncResponseBody = {
  data: models.V3IncidentsIncidentExportAsyncResponse;
};

/** @internal */
export const IncidentsIncidentExportAsyncResponseBody$inboundSchema: z.ZodType<
  IncidentsIncidentExportAsyncResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3IncidentsIncidentExportAsyncResponse$inboundSchema,
});

export function incidentsIncidentExportAsyncResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentsIncidentExportAsyncResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentsIncidentExportAsyncResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentsIncidentExportAsyncResponseBody' from JSON`,
  );
}
