/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IncidentActionsCreateATicketOnJiraCloudRequest = {
  incidentID: string;
};

/**
 * The request has succeeded.
 */
export type IncidentActionsCreateATicketOnJiraCloudResponse = {
  data: string;
};

/** @internal */
export type IncidentActionsCreateATicketOnJiraCloudRequest$Outbound = {
  incidentID: string;
};

/** @internal */
export const IncidentActionsCreateATicketOnJiraCloudRequest$outboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraCloudRequest$Outbound,
    z.ZodTypeDef,
    IncidentActionsCreateATicketOnJiraCloudRequest
  > = z.object({
    incidentID: z.string(),
  });

export function incidentActionsCreateATicketOnJiraCloudRequestToJSON(
  incidentActionsCreateATicketOnJiraCloudRequest:
    IncidentActionsCreateATicketOnJiraCloudRequest,
): string {
  return JSON.stringify(
    IncidentActionsCreateATicketOnJiraCloudRequest$outboundSchema.parse(
      incidentActionsCreateATicketOnJiraCloudRequest,
    ),
  );
}

/** @internal */
export const IncidentActionsCreateATicketOnJiraCloudResponse$inboundSchema:
  z.ZodType<
    IncidentActionsCreateATicketOnJiraCloudResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.string(),
  });

export function incidentActionsCreateATicketOnJiraCloudResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  IncidentActionsCreateATicketOnJiraCloudResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IncidentActionsCreateATicketOnJiraCloudResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IncidentActionsCreateATicketOnJiraCloudResponse' from JSON`,
  );
}
