/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type IncidentsReassignIncidentRequest = {
  incidentID: string;
  v3IncidentsReassignIncidentRequest: models.V3IncidentsReassignIncidentRequest;
};

/**
 * The request has succeeded.
 */
export type IncidentsReassignIncidentResponse = {
  data: string;
};

/** @internal */
export type IncidentsReassignIncidentRequest$Outbound = {
  incidentID: string;
  "V3.Incidents.ReassignIncidentRequest":
    models.V3IncidentsReassignIncidentRequest$Outbound;
};

/** @internal */
export const IncidentsReassignIncidentRequest$outboundSchema: z.ZodType<
  IncidentsReassignIncidentRequest$Outbound,
  z.ZodTypeDef,
  IncidentsReassignIncidentRequest
> = z.object({
  incidentID: z.string(),
  v3IncidentsReassignIncidentRequest:
    models.V3IncidentsReassignIncidentRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3IncidentsReassignIncidentRequest: "V3.Incidents.ReassignIncidentRequest",
  });
});

export function incidentsReassignIncidentRequestToJSON(
  incidentsReassignIncidentRequest: IncidentsReassignIncidentRequest,
): string {
  return JSON.stringify(
    IncidentsReassignIncidentRequest$outboundSchema.parse(
      incidentsReassignIncidentRequest,
    ),
  );
}

/** @internal */
export const IncidentsReassignIncidentResponse$inboundSchema: z.ZodType<
  IncidentsReassignIncidentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string(),
});

export function incidentsReassignIncidentResponseFromJSON(
  jsonString: string,
): SafeParseResult<IncidentsReassignIncidentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentsReassignIncidentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentsReassignIncidentResponse' from JSON`,
  );
}
