/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type IncidentsUnmergeIncidentRequest = {
  incidentID: string;
  v3IncidentsUnmergeIncidentRequest: models.V3IncidentsUnmergeIncidentRequest;
};

/**
 * The request has succeeded.
 */
export type IncidentsUnmergeIncidentResponse = {
  /**
   * Result of unmerging an incident.
   */
  data: models.V3IncidentsUnmergeIncidentResponse;
};

/** @internal */
export type IncidentsUnmergeIncidentRequest$Outbound = {
  incidentID: string;
  "V3.Incidents.UnmergeIncidentRequest":
    models.V3IncidentsUnmergeIncidentRequest$Outbound;
};

/** @internal */
export const IncidentsUnmergeIncidentRequest$outboundSchema: z.ZodType<
  IncidentsUnmergeIncidentRequest$Outbound,
  z.ZodTypeDef,
  IncidentsUnmergeIncidentRequest
> = z.object({
  incidentID: z.string(),
  v3IncidentsUnmergeIncidentRequest:
    models.V3IncidentsUnmergeIncidentRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3IncidentsUnmergeIncidentRequest: "V3.Incidents.UnmergeIncidentRequest",
  });
});

export function incidentsUnmergeIncidentRequestToJSON(
  incidentsUnmergeIncidentRequest: IncidentsUnmergeIncidentRequest,
): string {
  return JSON.stringify(
    IncidentsUnmergeIncidentRequest$outboundSchema.parse(
      incidentsUnmergeIncidentRequest,
    ),
  );
}

/** @internal */
export const IncidentsUnmergeIncidentResponse$inboundSchema: z.ZodType<
  IncidentsUnmergeIncidentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3IncidentsUnmergeIncidentResponse$inboundSchema,
});

export function incidentsUnmergeIncidentResponseFromJSON(
  jsonString: string,
): SafeParseResult<IncidentsUnmergeIncidentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IncidentsUnmergeIncidentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IncidentsUnmergeIncidentResponse' from JSON`,
  );
}
