/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type IssuesListStatusPageIssueStatesRequest = {
  statuspageID: string;
};

/**
 * The request has succeeded.
 */
export type IssuesListStatusPageIssueStatesResponse = {
  data: Array<models.V4StatusPagesIssuesListStatusPageIssueStatesResponse>;
};

/** @internal */
export type IssuesListStatusPageIssueStatesRequest$Outbound = {
  statuspageID: string;
};

/** @internal */
export const IssuesListStatusPageIssueStatesRequest$outboundSchema: z.ZodType<
  IssuesListStatusPageIssueStatesRequest$Outbound,
  z.ZodTypeDef,
  IssuesListStatusPageIssueStatesRequest
> = z.object({
  statuspageID: z.string(),
});

export function issuesListStatusPageIssueStatesRequestToJSON(
  issuesListStatusPageIssueStatesRequest:
    IssuesListStatusPageIssueStatesRequest,
): string {
  return JSON.stringify(
    IssuesListStatusPageIssueStatesRequest$outboundSchema.parse(
      issuesListStatusPageIssueStatesRequest,
    ),
  );
}

/** @internal */
export const IssuesListStatusPageIssueStatesResponse$inboundSchema: z.ZodType<
  IssuesListStatusPageIssueStatesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(
    models.V4StatusPagesIssuesListStatusPageIssueStatesResponse$inboundSchema,
  ),
});

export function issuesListStatusPageIssueStatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  IssuesListStatusPageIssueStatesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      IssuesListStatusPageIssueStatesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'IssuesListStatusPageIssueStatesResponse' from JSON`,
  );
}
