/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type IssuesCreateIssueRequest = {
  statuspageID: string;
  v4StatusPagesIssuesCreateIssueRequest:
    models.V4StatusPagesIssuesCreateIssueRequest;
};

/**
 * The request has succeeded.
 */
export type IssuesCreateIssueResponse = {
  data: models.V4StatusPagesIssuesCreateIssueResponse;
};

/** @internal */
export type IssuesCreateIssueRequest$Outbound = {
  statuspageID: string;
  "V4.StatusPages.Issues.CreateIssueRequest":
    models.V4StatusPagesIssuesCreateIssueRequest$Outbound;
};

/** @internal */
export const IssuesCreateIssueRequest$outboundSchema: z.ZodType<
  IssuesCreateIssueRequest$Outbound,
  z.ZodTypeDef,
  IssuesCreateIssueRequest
> = z.object({
  statuspageID: z.string(),
  v4StatusPagesIssuesCreateIssueRequest:
    models.V4StatusPagesIssuesCreateIssueRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v4StatusPagesIssuesCreateIssueRequest:
      "V4.StatusPages.Issues.CreateIssueRequest",
  });
});

export function issuesCreateIssueRequestToJSON(
  issuesCreateIssueRequest: IssuesCreateIssueRequest,
): string {
  return JSON.stringify(
    IssuesCreateIssueRequest$outboundSchema.parse(issuesCreateIssueRequest),
  );
}

/** @internal */
export const IssuesCreateIssueResponse$inboundSchema: z.ZodType<
  IssuesCreateIssueResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4StatusPagesIssuesCreateIssueResponse$inboundSchema,
});

export function issuesCreateIssueResponseFromJSON(
  jsonString: string,
): SafeParseResult<IssuesCreateIssueResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IssuesCreateIssueResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IssuesCreateIssueResponse' from JSON`,
  );
}
