/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MaintenancesDeleteMaintenanceByIdRequest = {
  statuspageID: string;
  maintenanceId: string;
};

/**
 * The request has succeeded.
 */
export type MaintenancesDeleteMaintenanceByIdResponse = {
  data: models.V4StatusPagesMaintenancesDeleteMaintenanceByIdResponse;
};

/** @internal */
export type MaintenancesDeleteMaintenanceByIdRequest$Outbound = {
  statuspageID: string;
  maintenance_id: string;
};

/** @internal */
export const MaintenancesDeleteMaintenanceByIdRequest$outboundSchema: z.ZodType<
  MaintenancesDeleteMaintenanceByIdRequest$Outbound,
  z.ZodTypeDef,
  MaintenancesDeleteMaintenanceByIdRequest
> = z.object({
  statuspageID: z.string(),
  maintenanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    maintenanceId: "maintenance_id",
  });
});

export function maintenancesDeleteMaintenanceByIdRequestToJSON(
  maintenancesDeleteMaintenanceByIdRequest:
    MaintenancesDeleteMaintenanceByIdRequest,
): string {
  return JSON.stringify(
    MaintenancesDeleteMaintenanceByIdRequest$outboundSchema.parse(
      maintenancesDeleteMaintenanceByIdRequest,
    ),
  );
}

/** @internal */
export const MaintenancesDeleteMaintenanceByIdResponse$inboundSchema: z.ZodType<
  MaintenancesDeleteMaintenanceByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data:
    models.V4StatusPagesMaintenancesDeleteMaintenanceByIdResponse$inboundSchema,
});

export function maintenancesDeleteMaintenanceByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  MaintenancesDeleteMaintenanceByIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MaintenancesDeleteMaintenanceByIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MaintenancesDeleteMaintenanceByIdResponse' from JSON`,
  );
}
