/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MaintenanceModeCreateOrUpdateMaintenanceModeRequest = {
  serviceID: string;
  v3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest:
    models.V3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest;
};

/**
 * The request has succeeded.
 */
export type MaintenanceModeCreateOrUpdateMaintenanceModeResponse = {
  data: string;
};

/** @internal */
export type MaintenanceModeCreateOrUpdateMaintenanceModeRequest$Outbound = {
  serviceID: string;
  "V3.Services.MaintenanceMode.CreateOrUpdateMaintenanceModeRequest":
    models.V3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest$Outbound;
};

/** @internal */
export const MaintenanceModeCreateOrUpdateMaintenanceModeRequest$outboundSchema:
  z.ZodType<
    MaintenanceModeCreateOrUpdateMaintenanceModeRequest$Outbound,
    z.ZodTypeDef,
    MaintenanceModeCreateOrUpdateMaintenanceModeRequest
  > = z.object({
    serviceID: z.string(),
    v3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest:
      models
        .V3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      v3ServicesMaintenanceModeCreateOrUpdateMaintenanceModeRequest:
        "V3.Services.MaintenanceMode.CreateOrUpdateMaintenanceModeRequest",
    });
  });

export function maintenanceModeCreateOrUpdateMaintenanceModeRequestToJSON(
  maintenanceModeCreateOrUpdateMaintenanceModeRequest:
    MaintenanceModeCreateOrUpdateMaintenanceModeRequest,
): string {
  return JSON.stringify(
    MaintenanceModeCreateOrUpdateMaintenanceModeRequest$outboundSchema.parse(
      maintenanceModeCreateOrUpdateMaintenanceModeRequest,
    ),
  );
}

/** @internal */
export const MaintenanceModeCreateOrUpdateMaintenanceModeResponse$inboundSchema:
  z.ZodType<
    MaintenanceModeCreateOrUpdateMaintenanceModeResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.string(),
  });

export function maintenanceModeCreateOrUpdateMaintenanceModeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  MaintenanceModeCreateOrUpdateMaintenanceModeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MaintenanceModeCreateOrUpdateMaintenanceModeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MaintenanceModeCreateOrUpdateMaintenanceModeResponse' from JSON`,
  );
}
