/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type MaintenancesListMaintenancesRequest = {
  statuspageID: string;
  startTime: string;
  endTime: string;
};

/** @internal */
export type MaintenancesListMaintenancesRequest$Outbound = {
  statuspageID: string;
  startTime: string;
  endTime: string;
};

/** @internal */
export const MaintenancesListMaintenancesRequest$outboundSchema: z.ZodType<
  MaintenancesListMaintenancesRequest$Outbound,
  z.ZodTypeDef,
  MaintenancesListMaintenancesRequest
> = z.object({
  statuspageID: z.string(),
  startTime: z.string(),
  endTime: z.string(),
});

export function maintenancesListMaintenancesRequestToJSON(
  maintenancesListMaintenancesRequest: MaintenancesListMaintenancesRequest,
): string {
  return JSON.stringify(
    MaintenancesListMaintenancesRequest$outboundSchema.parse(
      maintenancesListMaintenancesRequest,
    ),
  );
}
