/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type OverridesDeleteScheduleOverrideRequest = {
  scheduleID: string;
  overrideID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type OverridesDeleteScheduleOverrideResponseBody = {};

/** @internal */
export type OverridesDeleteScheduleOverrideRequest$Outbound = {
  scheduleID: string;
  overrideID: string;
};

/** @internal */
export const OverridesDeleteScheduleOverrideRequest$outboundSchema: z.ZodType<
  OverridesDeleteScheduleOverrideRequest$Outbound,
  z.ZodTypeDef,
  OverridesDeleteScheduleOverrideRequest
> = z.object({
  scheduleID: z.string(),
  overrideID: z.string(),
});

export function overridesDeleteScheduleOverrideRequestToJSON(
  overridesDeleteScheduleOverrideRequest:
    OverridesDeleteScheduleOverrideRequest,
): string {
  return JSON.stringify(
    OverridesDeleteScheduleOverrideRequest$outboundSchema.parse(
      overridesDeleteScheduleOverrideRequest,
    ),
  );
}

/** @internal */
export const OverridesDeleteScheduleOverrideResponseBody$inboundSchema:
  z.ZodType<
    OverridesDeleteScheduleOverrideResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function overridesDeleteScheduleOverrideResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  OverridesDeleteScheduleOverrideResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OverridesDeleteScheduleOverrideResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OverridesDeleteScheduleOverrideResponseBody' from JSON`,
  );
}
