/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type OverridesCreateScheduleOverrideRequest = {
  scheduleID: string;
  v4CreateScheduleOverrideRequest: models.V4CreateScheduleOverrideRequest;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type OverridesCreateScheduleOverrideResponse = {
  data: models.V4OverrideResponse;
};

/** @internal */
export type OverridesCreateScheduleOverrideRequest$Outbound = {
  scheduleID: string;
  "V4.CreateScheduleOverrideRequest":
    models.V4CreateScheduleOverrideRequest$Outbound;
};

/** @internal */
export const OverridesCreateScheduleOverrideRequest$outboundSchema: z.ZodType<
  OverridesCreateScheduleOverrideRequest$Outbound,
  z.ZodTypeDef,
  OverridesCreateScheduleOverrideRequest
> = z.object({
  scheduleID: z.string(),
  v4CreateScheduleOverrideRequest:
    models.V4CreateScheduleOverrideRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v4CreateScheduleOverrideRequest: "V4.CreateScheduleOverrideRequest",
  });
});

export function overridesCreateScheduleOverrideRequestToJSON(
  overridesCreateScheduleOverrideRequest:
    OverridesCreateScheduleOverrideRequest,
): string {
  return JSON.stringify(
    OverridesCreateScheduleOverrideRequest$outboundSchema.parse(
      overridesCreateScheduleOverrideRequest,
    ),
  );
}

/** @internal */
export const OverridesCreateScheduleOverrideResponse$inboundSchema: z.ZodType<
  OverridesCreateScheduleOverrideResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4OverrideResponse$inboundSchema,
});

export function overridesCreateScheduleOverrideResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OverridesCreateScheduleOverrideResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OverridesCreateScheduleOverrideResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OverridesCreateScheduleOverrideResponse' from JSON`,
  );
}
