/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type OverlayOptinForKeyBasedDeduplicationForAServiceRequest = {
  serviceID: string;
  v3ServicesOverlayOptInForKeyBasedDeduplicationRequest:
    models.V3ServicesOverlayOptInForKeyBasedDeduplicationRequest;
};

/**
 * The request has succeeded.
 */
export type OverlayOptinForKeyBasedDeduplicationForAServiceResponse = {};

/** @internal */
export type OverlayOptinForKeyBasedDeduplicationForAServiceRequest$Outbound = {
  serviceID: string;
  "V3.Services.Overlay.OptInForKeyBasedDeduplicationRequest":
    models.V3ServicesOverlayOptInForKeyBasedDeduplicationRequest$Outbound;
};

/** @internal */
export const OverlayOptinForKeyBasedDeduplicationForAServiceRequest$outboundSchema:
  z.ZodType<
    OverlayOptinForKeyBasedDeduplicationForAServiceRequest$Outbound,
    z.ZodTypeDef,
    OverlayOptinForKeyBasedDeduplicationForAServiceRequest
  > = z.object({
    serviceID: z.string(),
    v3ServicesOverlayOptInForKeyBasedDeduplicationRequest:
      models
        .V3ServicesOverlayOptInForKeyBasedDeduplicationRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      v3ServicesOverlayOptInForKeyBasedDeduplicationRequest:
        "V3.Services.Overlay.OptInForKeyBasedDeduplicationRequest",
    });
  });

export function overlayOptinForKeyBasedDeduplicationForAServiceRequestToJSON(
  overlayOptinForKeyBasedDeduplicationForAServiceRequest:
    OverlayOptinForKeyBasedDeduplicationForAServiceRequest,
): string {
  return JSON.stringify(
    OverlayOptinForKeyBasedDeduplicationForAServiceRequest$outboundSchema.parse(
      overlayOptinForKeyBasedDeduplicationForAServiceRequest,
    ),
  );
}

/** @internal */
export const OverlayOptinForKeyBasedDeduplicationForAServiceResponse$inboundSchema:
  z.ZodType<
    OverlayOptinForKeyBasedDeduplicationForAServiceResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function overlayOptinForKeyBasedDeduplicationForAServiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OverlayOptinForKeyBasedDeduplicationForAServiceResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OverlayOptinForKeyBasedDeduplicationForAServiceResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'OverlayOptinForKeyBasedDeduplicationForAServiceResponse' from JSON`,
  );
}
