/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type OverlayDeleteDedupKeyOverlayRequest = {
  serviceID: string;
  alertSource: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type OverlayDeleteDedupKeyOverlayResponseBody = {};

/** @internal */
export type OverlayDeleteDedupKeyOverlayRequest$Outbound = {
  serviceID: string;
  alertSource: string;
};

/** @internal */
export const OverlayDeleteDedupKeyOverlayRequest$outboundSchema: z.ZodType<
  OverlayDeleteDedupKeyOverlayRequest$Outbound,
  z.ZodTypeDef,
  OverlayDeleteDedupKeyOverlayRequest
> = z.object({
  serviceID: z.string(),
  alertSource: z.string(),
});

export function overlayDeleteDedupKeyOverlayRequestToJSON(
  overlayDeleteDedupKeyOverlayRequest: OverlayDeleteDedupKeyOverlayRequest,
): string {
  return JSON.stringify(
    OverlayDeleteDedupKeyOverlayRequest$outboundSchema.parse(
      overlayDeleteDedupKeyOverlayRequest,
    ),
  );
}

/** @internal */
export const OverlayDeleteDedupKeyOverlayResponseBody$inboundSchema: z.ZodType<
  OverlayDeleteDedupKeyOverlayResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function overlayDeleteDedupKeyOverlayResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  OverlayDeleteDedupKeyOverlayResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OverlayDeleteDedupKeyOverlayResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OverlayDeleteDedupKeyOverlayResponseBody' from JSON`,
  );
}
