/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type OverlayGetCustomContentTemplateOverlayRequest = {
  serviceID: string;
  alertSource: string;
};

/**
 * The request has succeeded.
 */
export type OverlayGetCustomContentTemplateOverlayResponse = {
  data: models.V3ServicesOverlayCustomContentOverlayResponse;
};

/** @internal */
export type OverlayGetCustomContentTemplateOverlayRequest$Outbound = {
  serviceID: string;
  alertSource: string;
};

/** @internal */
export const OverlayGetCustomContentTemplateOverlayRequest$outboundSchema:
  z.ZodType<
    OverlayGetCustomContentTemplateOverlayRequest$Outbound,
    z.ZodTypeDef,
    OverlayGetCustomContentTemplateOverlayRequest
  > = z.object({
    serviceID: z.string(),
    alertSource: z.string(),
  });

export function overlayGetCustomContentTemplateOverlayRequestToJSON(
  overlayGetCustomContentTemplateOverlayRequest:
    OverlayGetCustomContentTemplateOverlayRequest,
): string {
  return JSON.stringify(
    OverlayGetCustomContentTemplateOverlayRequest$outboundSchema.parse(
      overlayGetCustomContentTemplateOverlayRequest,
    ),
  );
}

/** @internal */
export const OverlayGetCustomContentTemplateOverlayResponse$inboundSchema:
  z.ZodType<
    OverlayGetCustomContentTemplateOverlayResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: models.V3ServicesOverlayCustomContentOverlayResponse$inboundSchema,
  });

export function overlayGetCustomContentTemplateOverlayResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OverlayGetCustomContentTemplateOverlayResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OverlayGetCustomContentTemplateOverlayResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OverlayGetCustomContentTemplateOverlayResponse' from JSON`,
  );
}
