/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type OverlayGetAllCustomContentTemplateOverlayByServiceRequest = {
  serviceID: string;
};

/**
 * The request has succeeded.
 */
export type OverlayGetAllCustomContentTemplateOverlayByServiceResponse = {
  data: Array<models.V3ServicesOverlayCustomContentOverlayResponse>;
};

/** @internal */
export type OverlayGetAllCustomContentTemplateOverlayByServiceRequest$Outbound =
  {
    serviceID: string;
  };

/** @internal */
export const OverlayGetAllCustomContentTemplateOverlayByServiceRequest$outboundSchema:
  z.ZodType<
    OverlayGetAllCustomContentTemplateOverlayByServiceRequest$Outbound,
    z.ZodTypeDef,
    OverlayGetAllCustomContentTemplateOverlayByServiceRequest
  > = z.object({
    serviceID: z.string(),
  });

export function overlayGetAllCustomContentTemplateOverlayByServiceRequestToJSON(
  overlayGetAllCustomContentTemplateOverlayByServiceRequest:
    OverlayGetAllCustomContentTemplateOverlayByServiceRequest,
): string {
  return JSON.stringify(
    OverlayGetAllCustomContentTemplateOverlayByServiceRequest$outboundSchema
      .parse(overlayGetAllCustomContentTemplateOverlayByServiceRequest),
  );
}

/** @internal */
export const OverlayGetAllCustomContentTemplateOverlayByServiceResponse$inboundSchema:
  z.ZodType<
    OverlayGetAllCustomContentTemplateOverlayByServiceResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.array(
      models.V3ServicesOverlayCustomContentOverlayResponse$inboundSchema,
    ),
  });

export function overlayGetAllCustomContentTemplateOverlayByServiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  OverlayGetAllCustomContentTemplateOverlayByServiceResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OverlayGetAllCustomContentTemplateOverlayByServiceResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'OverlayGetAllCustomContentTemplateOverlayByServiceResponse' from JSON`,
  );
}
