/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostmortemsCreatePostmortemRequest = {
  incidentID: string;
  v3IncidentsPostmortemsCreatePostmortemRequest:
    models.V3IncidentsPostmortemsCreatePostmortemRequest;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type PostmortemsCreatePostmortemResponse = {
  data: models.V3IncidentsPostmortemsPostmortemResponse;
};

/** @internal */
export type PostmortemsCreatePostmortemRequest$Outbound = {
  incidentID: string;
  "V3.Incidents.Postmortems.CreatePostmortemRequest":
    models.V3IncidentsPostmortemsCreatePostmortemRequest$Outbound;
};

/** @internal */
export const PostmortemsCreatePostmortemRequest$outboundSchema: z.ZodType<
  PostmortemsCreatePostmortemRequest$Outbound,
  z.ZodTypeDef,
  PostmortemsCreatePostmortemRequest
> = z.object({
  incidentID: z.string(),
  v3IncidentsPostmortemsCreatePostmortemRequest:
    models.V3IncidentsPostmortemsCreatePostmortemRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3IncidentsPostmortemsCreatePostmortemRequest:
      "V3.Incidents.Postmortems.CreatePostmortemRequest",
  });
});

export function postmortemsCreatePostmortemRequestToJSON(
  postmortemsCreatePostmortemRequest: PostmortemsCreatePostmortemRequest,
): string {
  return JSON.stringify(
    PostmortemsCreatePostmortemRequest$outboundSchema.parse(
      postmortemsCreatePostmortemRequest,
    ),
  );
}

/** @internal */
export const PostmortemsCreatePostmortemResponse$inboundSchema: z.ZodType<
  PostmortemsCreatePostmortemResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3IncidentsPostmortemsPostmortemResponse$inboundSchema,
});

export function postmortemsCreatePostmortemResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostmortemsCreatePostmortemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostmortemsCreatePostmortemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostmortemsCreatePostmortemResponse' from JSON`,
  );
}
