/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostmortemsGetAllPostmortemsRequest = {
  /**
   * Provide date in RFC3339 format
   */
  fromDate: string;
  /**
   * Provide date in RFC3339 format
   */
  toDate: string;
  /**
   * Here owner_id represents team_id
   */
  ownerId: string;
  limit: number;
};

export type PostmortemsGetAllPostmortemsData = {
  result: Array<models.V3IncidentsPostmortemsPostmortemListResult>;
  totalCount: Array<models.V3IncidentsPostmortemsTotalPostmortemCount>;
};

/**
 * The request has succeeded.
 */
export type PostmortemsGetAllPostmortemsResponse = {
  data: Array<PostmortemsGetAllPostmortemsData>;
};

/** @internal */
export type PostmortemsGetAllPostmortemsRequest$Outbound = {
  fromDate: string;
  toDate: string;
  owner_id: string;
  limit: number;
};

/** @internal */
export const PostmortemsGetAllPostmortemsRequest$outboundSchema: z.ZodType<
  PostmortemsGetAllPostmortemsRequest$Outbound,
  z.ZodTypeDef,
  PostmortemsGetAllPostmortemsRequest
> = z.object({
  fromDate: z.string(),
  toDate: z.string(),
  ownerId: z.string(),
  limit: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
  });
});

export function postmortemsGetAllPostmortemsRequestToJSON(
  postmortemsGetAllPostmortemsRequest: PostmortemsGetAllPostmortemsRequest,
): string {
  return JSON.stringify(
    PostmortemsGetAllPostmortemsRequest$outboundSchema.parse(
      postmortemsGetAllPostmortemsRequest,
    ),
  );
}

/** @internal */
export const PostmortemsGetAllPostmortemsData$inboundSchema: z.ZodType<
  PostmortemsGetAllPostmortemsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: z.array(
    models.V3IncidentsPostmortemsPostmortemListResult$inboundSchema,
  ),
  total_count: z.array(
    models.V3IncidentsPostmortemsTotalPostmortemCount$inboundSchema,
  ),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function postmortemsGetAllPostmortemsDataFromJSON(
  jsonString: string,
): SafeParseResult<PostmortemsGetAllPostmortemsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostmortemsGetAllPostmortemsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostmortemsGetAllPostmortemsData' from JSON`,
  );
}

/** @internal */
export const PostmortemsGetAllPostmortemsResponse$inboundSchema: z.ZodType<
  PostmortemsGetAllPostmortemsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => PostmortemsGetAllPostmortemsData$inboundSchema)),
});

export function postmortemsGetAllPostmortemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostmortemsGetAllPostmortemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostmortemsGetAllPostmortemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostmortemsGetAllPostmortemsResponse' from JSON`,
  );
}
