/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RotationsGetScheduleRotationsRequest = {
  scheduleID: string;
};

/**
 * The request has succeeded.
 */
export type RotationsGetScheduleRotationsResponse = {
  data: Array<models.V4RotationResponse>;
};

/** @internal */
export type RotationsGetScheduleRotationsRequest$Outbound = {
  scheduleID: string;
};

/** @internal */
export const RotationsGetScheduleRotationsRequest$outboundSchema: z.ZodType<
  RotationsGetScheduleRotationsRequest$Outbound,
  z.ZodTypeDef,
  RotationsGetScheduleRotationsRequest
> = z.object({
  scheduleID: z.string(),
});

export function rotationsGetScheduleRotationsRequestToJSON(
  rotationsGetScheduleRotationsRequest: RotationsGetScheduleRotationsRequest,
): string {
  return JSON.stringify(
    RotationsGetScheduleRotationsRequest$outboundSchema.parse(
      rotationsGetScheduleRotationsRequest,
    ),
  );
}

/** @internal */
export const RotationsGetScheduleRotationsResponse$inboundSchema: z.ZodType<
  RotationsGetScheduleRotationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.V4RotationResponse$inboundSchema),
});

export function rotationsGetScheduleRotationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<RotationsGetScheduleRotationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RotationsGetScheduleRotationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RotationsGetScheduleRotationsResponse' from JSON`,
  );
}
