/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RotationsDeleteRotationRequest = {
  scheduleID: string;
  rotationID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type RotationsDeleteRotationResponseBody = {};

/** @internal */
export type RotationsDeleteRotationRequest$Outbound = {
  scheduleID: string;
  rotationID: string;
};

/** @internal */
export const RotationsDeleteRotationRequest$outboundSchema: z.ZodType<
  RotationsDeleteRotationRequest$Outbound,
  z.ZodTypeDef,
  RotationsDeleteRotationRequest
> = z.object({
  scheduleID: z.string(),
  rotationID: z.string(),
});

export function rotationsDeleteRotationRequestToJSON(
  rotationsDeleteRotationRequest: RotationsDeleteRotationRequest,
): string {
  return JSON.stringify(
    RotationsDeleteRotationRequest$outboundSchema.parse(
      rotationsDeleteRotationRequest,
    ),
  );
}

/** @internal */
export const RotationsDeleteRotationResponseBody$inboundSchema: z.ZodType<
  RotationsDeleteRotationResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function rotationsDeleteRotationResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RotationsDeleteRotationResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RotationsDeleteRotationResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RotationsDeleteRotationResponseBody' from JSON`,
  );
}
