/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RoutingRulesCreateOrUpdateRoutingRulesRequest = {
  serviceID: string;
  v3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest:
    models.V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest;
};

export type RoutingRulesCreateOrUpdateRoutingRulesData = {
  rules: Array<models.V3ServicesRoutingRulesRoutingRuleResponse>;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type RoutingRulesCreateOrUpdateRoutingRulesResponse = {
  data: RoutingRulesCreateOrUpdateRoutingRulesData;
};

/** @internal */
export type RoutingRulesCreateOrUpdateRoutingRulesRequest$Outbound = {
  serviceID: string;
  "V3.Services.RoutingRules.CreateOrUpdateRoutingRulesRequest":
    models.V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest$Outbound;
};

/** @internal */
export const RoutingRulesCreateOrUpdateRoutingRulesRequest$outboundSchema:
  z.ZodType<
    RoutingRulesCreateOrUpdateRoutingRulesRequest$Outbound,
    z.ZodTypeDef,
    RoutingRulesCreateOrUpdateRoutingRulesRequest
  > = z.object({
    serviceID: z.string(),
    v3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest:
      models
        .V3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      v3ServicesRoutingRulesCreateOrUpdateRoutingRulesRequest:
        "V3.Services.RoutingRules.CreateOrUpdateRoutingRulesRequest",
    });
  });

export function routingRulesCreateOrUpdateRoutingRulesRequestToJSON(
  routingRulesCreateOrUpdateRoutingRulesRequest:
    RoutingRulesCreateOrUpdateRoutingRulesRequest,
): string {
  return JSON.stringify(
    RoutingRulesCreateOrUpdateRoutingRulesRequest$outboundSchema.parse(
      routingRulesCreateOrUpdateRoutingRulesRequest,
    ),
  );
}

/** @internal */
export const RoutingRulesCreateOrUpdateRoutingRulesData$inboundSchema:
  z.ZodType<RoutingRulesCreateOrUpdateRoutingRulesData, z.ZodTypeDef, unknown> =
    z.object({
      rules: z.array(
        models.V3ServicesRoutingRulesRoutingRuleResponse$inboundSchema,
      ),
    });

export function routingRulesCreateOrUpdateRoutingRulesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  RoutingRulesCreateOrUpdateRoutingRulesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RoutingRulesCreateOrUpdateRoutingRulesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RoutingRulesCreateOrUpdateRoutingRulesData' from JSON`,
  );
}

/** @internal */
export const RoutingRulesCreateOrUpdateRoutingRulesResponse$inboundSchema:
  z.ZodType<
    RoutingRulesCreateOrUpdateRoutingRulesResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      RoutingRulesCreateOrUpdateRoutingRulesData$inboundSchema
    ),
  });

export function routingRulesCreateOrUpdateRoutingRulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  RoutingRulesCreateOrUpdateRoutingRulesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RoutingRulesCreateOrUpdateRoutingRulesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RoutingRulesCreateOrUpdateRoutingRulesResponse' from JSON`,
  );
}
