/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded.
 */
export type RunbooksGetAllRunbooksByTeamResponse = {
  data: Array<models.V3RunbooksRunbookResponse>;
};

/** @internal */
export const RunbooksGetAllRunbooksByTeamResponse$inboundSchema: z.ZodType<
  RunbooksGetAllRunbooksByTeamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.V3RunbooksRunbookResponse$inboundSchema),
});

export function runbooksGetAllRunbooksByTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<RunbooksGetAllRunbooksByTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RunbooksGetAllRunbooksByTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunbooksGetAllRunbooksByTeamResponse' from JSON`,
  );
}
