/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type RunbooksCreateRunbookResponse = {
  data: models.V3RunbooksRunbookResponse;
};

/** @internal */
export const RunbooksCreateRunbookResponse$inboundSchema: z.ZodType<
  RunbooksCreateRunbookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3RunbooksRunbookResponse$inboundSchema,
});

export function runbooksCreateRunbookResponseFromJSON(
  jsonString: string,
): SafeParseResult<RunbooksCreateRunbookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunbooksCreateRunbookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunbooksCreateRunbookResponse' from JSON`,
  );
}
