/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RunbooksGetRunbookByIdRequest = {
  runbookID: string;
};

/**
 * The request has succeeded.
 */
export type RunbooksGetRunbookByIdResponse = {
  data: models.V3RunbooksRunbookResponse;
};

/** @internal */
export type RunbooksGetRunbookByIdRequest$Outbound = {
  runbookID: string;
};

/** @internal */
export const RunbooksGetRunbookByIdRequest$outboundSchema: z.ZodType<
  RunbooksGetRunbookByIdRequest$Outbound,
  z.ZodTypeDef,
  RunbooksGetRunbookByIdRequest
> = z.object({
  runbookID: z.string(),
});

export function runbooksGetRunbookByIdRequestToJSON(
  runbooksGetRunbookByIdRequest: RunbooksGetRunbookByIdRequest,
): string {
  return JSON.stringify(
    RunbooksGetRunbookByIdRequest$outboundSchema.parse(
      runbooksGetRunbookByIdRequest,
    ),
  );
}

/** @internal */
export const RunbooksGetRunbookByIdResponse$inboundSchema: z.ZodType<
  RunbooksGetRunbookByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3RunbooksRunbookResponse$inboundSchema,
});

export function runbooksGetRunbookByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<RunbooksGetRunbookByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunbooksGetRunbookByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunbooksGetRunbookByIdResponse' from JSON`,
  );
}
