/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SchedulesDeleteScheduleRequest = {
  scheduleID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type SchedulesDeleteScheduleResponseBody = {};

/** @internal */
export type SchedulesDeleteScheduleRequest$Outbound = {
  scheduleID: string;
};

/** @internal */
export const SchedulesDeleteScheduleRequest$outboundSchema: z.ZodType<
  SchedulesDeleteScheduleRequest$Outbound,
  z.ZodTypeDef,
  SchedulesDeleteScheduleRequest
> = z.object({
  scheduleID: z.string(),
});

export function schedulesDeleteScheduleRequestToJSON(
  schedulesDeleteScheduleRequest: SchedulesDeleteScheduleRequest,
): string {
  return JSON.stringify(
    SchedulesDeleteScheduleRequest$outboundSchema.parse(
      schedulesDeleteScheduleRequest,
    ),
  );
}

/** @internal */
export const SchedulesDeleteScheduleResponseBody$inboundSchema: z.ZodType<
  SchedulesDeleteScheduleResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function schedulesDeleteScheduleResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SchedulesDeleteScheduleResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SchedulesDeleteScheduleResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchedulesDeleteScheduleResponseBody' from JSON`,
  );
}
