/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ServicesCreateOrUpdateIAGConfigRequest = {
  serviceID: string;
  v3ServicesIAGConfigRequest: models.V3ServicesIAGConfigRequest;
};

export type ServicesCreateOrUpdateIAGConfigData = {
  msg: string;
};

/**
 * The request has succeeded.
 */
export type ServicesCreateOrUpdateIAGConfigResponse = {
  data: ServicesCreateOrUpdateIAGConfigData;
};

/** @internal */
export type ServicesCreateOrUpdateIAGConfigRequest$Outbound = {
  serviceID: string;
  "V3.Services.IAGConfigRequest": models.V3ServicesIAGConfigRequest$Outbound;
};

/** @internal */
export const ServicesCreateOrUpdateIAGConfigRequest$outboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigRequest$Outbound,
  z.ZodTypeDef,
  ServicesCreateOrUpdateIAGConfigRequest
> = z.object({
  serviceID: z.string(),
  v3ServicesIAGConfigRequest: models.V3ServicesIAGConfigRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3ServicesIAGConfigRequest: "V3.Services.IAGConfigRequest",
  });
});

export function servicesCreateOrUpdateIAGConfigRequestToJSON(
  servicesCreateOrUpdateIAGConfigRequest:
    ServicesCreateOrUpdateIAGConfigRequest,
): string {
  return JSON.stringify(
    ServicesCreateOrUpdateIAGConfigRequest$outboundSchema.parse(
      servicesCreateOrUpdateIAGConfigRequest,
    ),
  );
}

/** @internal */
export const ServicesCreateOrUpdateIAGConfigData$inboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigData,
  z.ZodTypeDef,
  unknown
> = z.object({
  msg: z.string(),
});

export function servicesCreateOrUpdateIAGConfigDataFromJSON(
  jsonString: string,
): SafeParseResult<ServicesCreateOrUpdateIAGConfigData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ServicesCreateOrUpdateIAGConfigData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesCreateOrUpdateIAGConfigData' from JSON`,
  );
}

/** @internal */
export const ServicesCreateOrUpdateIAGConfigResponse$inboundSchema: z.ZodType<
  ServicesCreateOrUpdateIAGConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ServicesCreateOrUpdateIAGConfigData$inboundSchema),
});

export function servicesCreateOrUpdateIAGConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ServicesCreateOrUpdateIAGConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ServicesCreateOrUpdateIAGConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ServicesCreateOrUpdateIAGConfigResponse' from JSON`,
  );
}
