/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServicesDeleteServiceRequest = {
  serviceID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type ServicesDeleteServiceResponseBody = {};

/** @internal */
export type ServicesDeleteServiceRequest$Outbound = {
  serviceID: string;
};

/** @internal */
export const ServicesDeleteServiceRequest$outboundSchema: z.ZodType<
  ServicesDeleteServiceRequest$Outbound,
  z.ZodTypeDef,
  ServicesDeleteServiceRequest
> = z.object({
  serviceID: z.string(),
});

export function servicesDeleteServiceRequestToJSON(
  servicesDeleteServiceRequest: ServicesDeleteServiceRequest,
): string {
  return JSON.stringify(
    ServicesDeleteServiceRequest$outboundSchema.parse(
      servicesDeleteServiceRequest,
    ),
  );
}

/** @internal */
export const ServicesDeleteServiceResponseBody$inboundSchema: z.ZodType<
  ServicesDeleteServiceResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function servicesDeleteServiceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ServicesDeleteServiceResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServicesDeleteServiceResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesDeleteServiceResponseBody' from JSON`,
  );
}
