/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ServicesCreateServiceRequest = {
  ownerId: string;
  v3ServicesCreateServiceRequest: models.V3ServicesCreateServiceRequest;
};

/**
 * The body type of the operation request or response.
 */
export type ServicesCreateServiceBody = {
  data: models.V3ServicesServiceResponse;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type ServicesCreateServiceResponse = {
  /**
   * The body type of the operation request or response.
   */
  body: ServicesCreateServiceBody;
};

/** @internal */
export type ServicesCreateServiceRequest$Outbound = {
  owner_id: string;
  "V3.Services.CreateServiceRequest":
    models.V3ServicesCreateServiceRequest$Outbound;
};

/** @internal */
export const ServicesCreateServiceRequest$outboundSchema: z.ZodType<
  ServicesCreateServiceRequest$Outbound,
  z.ZodTypeDef,
  ServicesCreateServiceRequest
> = z.object({
  ownerId: z.string(),
  v3ServicesCreateServiceRequest:
    models.V3ServicesCreateServiceRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
    v3ServicesCreateServiceRequest: "V3.Services.CreateServiceRequest",
  });
});

export function servicesCreateServiceRequestToJSON(
  servicesCreateServiceRequest: ServicesCreateServiceRequest,
): string {
  return JSON.stringify(
    ServicesCreateServiceRequest$outboundSchema.parse(
      servicesCreateServiceRequest,
    ),
  );
}

/** @internal */
export const ServicesCreateServiceBody$inboundSchema: z.ZodType<
  ServicesCreateServiceBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3ServicesServiceResponse$inboundSchema,
});

export function servicesCreateServiceBodyFromJSON(
  jsonString: string,
): SafeParseResult<ServicesCreateServiceBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServicesCreateServiceBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesCreateServiceBody' from JSON`,
  );
}

/** @internal */
export const ServicesCreateServiceResponse$inboundSchema: z.ZodType<
  ServicesCreateServiceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.lazy(() => ServicesCreateServiceBody$inboundSchema),
});

export function servicesCreateServiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServicesCreateServiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServicesCreateServiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesCreateServiceResponse' from JSON`,
  );
}
