/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ServicesUpdateServiceRequest = {
  serviceID: string;
  v3ServicesUpdateServiceRequest: models.V3ServicesUpdateServiceRequest;
};

/**
 * The request has succeeded.
 */
export type ServicesUpdateServiceResponse = {
  data: models.V3ServicesServiceResponse;
};

/** @internal */
export type ServicesUpdateServiceRequest$Outbound = {
  serviceID: string;
  "V3.Services.UpdateServiceRequest":
    models.V3ServicesUpdateServiceRequest$Outbound;
};

/** @internal */
export const ServicesUpdateServiceRequest$outboundSchema: z.ZodType<
  ServicesUpdateServiceRequest$Outbound,
  z.ZodTypeDef,
  ServicesUpdateServiceRequest
> = z.object({
  serviceID: z.string(),
  v3ServicesUpdateServiceRequest:
    models.V3ServicesUpdateServiceRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3ServicesUpdateServiceRequest: "V3.Services.UpdateServiceRequest",
  });
});

export function servicesUpdateServiceRequestToJSON(
  servicesUpdateServiceRequest: ServicesUpdateServiceRequest,
): string {
  return JSON.stringify(
    ServicesUpdateServiceRequest$outboundSchema.parse(
      servicesUpdateServiceRequest,
    ),
  );
}

/** @internal */
export const ServicesUpdateServiceResponse$inboundSchema: z.ZodType<
  ServicesUpdateServiceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3ServicesServiceResponse$inboundSchema,
});

export function servicesUpdateServiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServicesUpdateServiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServicesUpdateServiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesUpdateServiceResponse' from JSON`,
  );
}
