/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ServicesGetServicesByNameRequest = {
  name: string;
  ownerId: string;
};

/**
 * The request has succeeded.
 */
export type ServicesGetServicesByNameResponse = {
  data: models.V3ServicesServiceResponse;
};

/** @internal */
export type ServicesGetServicesByNameRequest$Outbound = {
  name: string;
  owner_id: string;
};

/** @internal */
export const ServicesGetServicesByNameRequest$outboundSchema: z.ZodType<
  ServicesGetServicesByNameRequest$Outbound,
  z.ZodTypeDef,
  ServicesGetServicesByNameRequest
> = z.object({
  name: z.string(),
  ownerId: z.string(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
  });
});

export function servicesGetServicesByNameRequestToJSON(
  servicesGetServicesByNameRequest: ServicesGetServicesByNameRequest,
): string {
  return JSON.stringify(
    ServicesGetServicesByNameRequest$outboundSchema.parse(
      servicesGetServicesByNameRequest,
    ),
  );
}

/** @internal */
export const ServicesGetServicesByNameResponse$inboundSchema: z.ZodType<
  ServicesGetServicesByNameResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3ServicesServiceResponse$inboundSchema,
});

export function servicesGetServicesByNameResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServicesGetServicesByNameResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServicesGetServicesByNameResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServicesGetServicesByNameResponse' from JSON`,
  );
}
