/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SLOCreateSLOData = {
  slo: models.V3SLOSLODetailedResponse;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type SLOCreateSLOResponse = {
  data: SLOCreateSLOData;
};

/** @internal */
export const SLOCreateSLOData$inboundSchema: z.ZodType<
  SLOCreateSLOData,
  z.ZodTypeDef,
  unknown
> = z.object({
  slo: models.V3SLOSLODetailedResponse$inboundSchema,
});

export function sloCreateSLODataFromJSON(
  jsonString: string,
): SafeParseResult<SLOCreateSLOData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SLOCreateSLOData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SLOCreateSLOData' from JSON`,
  );
}

/** @internal */
export const SLOCreateSLOResponse$inboundSchema: z.ZodType<
  SLOCreateSLOResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SLOCreateSLOData$inboundSchema),
});

export function sloCreateSLOResponseFromJSON(
  jsonString: string,
): SafeParseResult<SLOCreateSLOResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SLOCreateSLOResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SLOCreateSLOResponse' from JSON`,
  );
}
