/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SLOMarkSLOFalsePositiveRequestBody = {};

export type SLOMarkSLOFalsePositiveRequest = {
  sloID: number;
  incidentID: number;
  value: boolean;
  ownerId: string;
  requestBody: SLOMarkSLOFalsePositiveRequestBody;
};

export type SLOMarkSLOFalsePositiveData = {
  sloViolatingIncident: models.V3SLOSLOViolatingIncidentResponse;
};

/**
 * The request has succeeded.
 */
export type SLOMarkSLOFalsePositiveResponse = {
  data: SLOMarkSLOFalsePositiveData;
};

/** @internal */
export type SLOMarkSLOFalsePositiveRequestBody$Outbound = {};

/** @internal */
export const SLOMarkSLOFalsePositiveRequestBody$outboundSchema: z.ZodType<
  SLOMarkSLOFalsePositiveRequestBody$Outbound,
  z.ZodTypeDef,
  SLOMarkSLOFalsePositiveRequestBody
> = z.object({});

export function sloMarkSLOFalsePositiveRequestBodyToJSON(
  sloMarkSLOFalsePositiveRequestBody: SLOMarkSLOFalsePositiveRequestBody,
): string {
  return JSON.stringify(
    SLOMarkSLOFalsePositiveRequestBody$outboundSchema.parse(
      sloMarkSLOFalsePositiveRequestBody,
    ),
  );
}

/** @internal */
export type SLOMarkSLOFalsePositiveRequest$Outbound = {
  sloID: number;
  incidentID: number;
  value: boolean;
  owner_id: string;
  RequestBody: SLOMarkSLOFalsePositiveRequestBody$Outbound;
};

/** @internal */
export const SLOMarkSLOFalsePositiveRequest$outboundSchema: z.ZodType<
  SLOMarkSLOFalsePositiveRequest$Outbound,
  z.ZodTypeDef,
  SLOMarkSLOFalsePositiveRequest
> = z.object({
  sloID: z.number().int(),
  incidentID: z.number().int(),
  value: z.boolean(),
  ownerId: z.string(),
  requestBody: z.lazy(() => SLOMarkSLOFalsePositiveRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
    requestBody: "RequestBody",
  });
});

export function sloMarkSLOFalsePositiveRequestToJSON(
  sloMarkSLOFalsePositiveRequest: SLOMarkSLOFalsePositiveRequest,
): string {
  return JSON.stringify(
    SLOMarkSLOFalsePositiveRequest$outboundSchema.parse(
      sloMarkSLOFalsePositiveRequest,
    ),
  );
}

/** @internal */
export const SLOMarkSLOFalsePositiveData$inboundSchema: z.ZodType<
  SLOMarkSLOFalsePositiveData,
  z.ZodTypeDef,
  unknown
> = z.object({
  slo_violating_incident:
    models.V3SLOSLOViolatingIncidentResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "slo_violating_incident": "sloViolatingIncident",
  });
});

export function sloMarkSLOFalsePositiveDataFromJSON(
  jsonString: string,
): SafeParseResult<SLOMarkSLOFalsePositiveData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SLOMarkSLOFalsePositiveData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SLOMarkSLOFalsePositiveData' from JSON`,
  );
}

/** @internal */
export const SLOMarkSLOFalsePositiveResponse$inboundSchema: z.ZodType<
  SLOMarkSLOFalsePositiveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SLOMarkSLOFalsePositiveData$inboundSchema),
});

export function sloMarkSLOFalsePositiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<SLOMarkSLOFalsePositiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SLOMarkSLOFalsePositiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SLOMarkSLOFalsePositiveResponse' from JSON`,
  );
}
