/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type SquadsCreateSquadResponse = {
  data: models.V4SquadsCreateSquadResponse;
};

/** @internal */
export const SquadsCreateSquadResponse$inboundSchema: z.ZodType<
  SquadsCreateSquadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4SquadsCreateSquadResponse$inboundSchema,
});

export function squadsCreateSquadResponseFromJSON(
  jsonString: string,
): SafeParseResult<SquadsCreateSquadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SquadsCreateSquadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SquadsCreateSquadResponse' from JSON`,
  );
}
