/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SquadsGetAllSquadsRequest = {
  ownerId: string;
};

/**
 * The request has succeeded.
 */
export type SquadsGetAllSquadsResponse = {
  data: Array<models.V4SquadsSquadResponse>;
  pageInfo: models.CommonV4PageInfo;
};

/** @internal */
export type SquadsGetAllSquadsRequest$Outbound = {
  owner_id: string;
};

/** @internal */
export const SquadsGetAllSquadsRequest$outboundSchema: z.ZodType<
  SquadsGetAllSquadsRequest$Outbound,
  z.ZodTypeDef,
  SquadsGetAllSquadsRequest
> = z.object({
  ownerId: z.string(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
  });
});

export function squadsGetAllSquadsRequestToJSON(
  squadsGetAllSquadsRequest: SquadsGetAllSquadsRequest,
): string {
  return JSON.stringify(
    SquadsGetAllSquadsRequest$outboundSchema.parse(squadsGetAllSquadsRequest),
  );
}

/** @internal */
export const SquadsGetAllSquadsResponse$inboundSchema: z.ZodType<
  SquadsGetAllSquadsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.V4SquadsSquadResponse$inboundSchema),
  pageInfo: models.CommonV4PageInfo$inboundSchema,
});

export function squadsGetAllSquadsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SquadsGetAllSquadsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SquadsGetAllSquadsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SquadsGetAllSquadsResponse' from JSON`,
  );
}
