/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SquadsUpdateSquadRequest = {
  squadID: string;
  v4SquadsUpdateSquadRequest: models.V4SquadsUpdateSquadRequest;
};

/**
 * The request has succeeded.
 */
export type SquadsUpdateSquadResponse = {
  data: models.V4SquadsSquadResponse;
};

/** @internal */
export type SquadsUpdateSquadRequest$Outbound = {
  squadID: string;
  "V4.Squads.UpdateSquadRequest": models.V4SquadsUpdateSquadRequest$Outbound;
};

/** @internal */
export const SquadsUpdateSquadRequest$outboundSchema: z.ZodType<
  SquadsUpdateSquadRequest$Outbound,
  z.ZodTypeDef,
  SquadsUpdateSquadRequest
> = z.object({
  squadID: z.string(),
  v4SquadsUpdateSquadRequest: models.V4SquadsUpdateSquadRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v4SquadsUpdateSquadRequest: "V4.Squads.UpdateSquadRequest",
  });
});

export function squadsUpdateSquadRequestToJSON(
  squadsUpdateSquadRequest: SquadsUpdateSquadRequest,
): string {
  return JSON.stringify(
    SquadsUpdateSquadRequest$outboundSchema.parse(squadsUpdateSquadRequest),
  );
}

/** @internal */
export const SquadsUpdateSquadResponse$inboundSchema: z.ZodType<
  SquadsUpdateSquadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4SquadsSquadResponse$inboundSchema,
});

export function squadsUpdateSquadResponseFromJSON(
  jsonString: string,
): SafeParseResult<SquadsUpdateSquadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SquadsUpdateSquadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SquadsUpdateSquadResponse' from JSON`,
  );
}
