/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SquadsRemoveSquadMemberRequest = {
  squadID: string;
  memberID: string;
  replaceWith: string;
};

/** @internal */
export type SquadsRemoveSquadMemberRequest$Outbound = {
  squadID: string;
  memberID: string;
  replaceWith: string;
};

/** @internal */
export const SquadsRemoveSquadMemberRequest$outboundSchema: z.ZodType<
  SquadsRemoveSquadMemberRequest$Outbound,
  z.ZodTypeDef,
  SquadsRemoveSquadMemberRequest
> = z.object({
  squadID: z.string(),
  memberID: z.string(),
  replaceWith: z.string(),
});

export function squadsRemoveSquadMemberRequestToJSON(
  squadsRemoveSquadMemberRequest: SquadsRemoveSquadMemberRequest,
): string {
  return JSON.stringify(
    SquadsRemoveSquadMemberRequest$outboundSchema.parse(
      squadsRemoveSquadMemberRequest,
    ),
  );
}
