/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type StatusPagesUpdateStatusPageByIdRequest = {
  statuspageID: string;
  v4StatusPagesUpdateStatusPageByIdRequest:
    models.V4StatusPagesUpdateStatusPageByIdRequest;
};

/**
 * The request has succeeded.
 */
export type StatusPagesUpdateStatusPageByIdResponse = {
  data: models.V4StatusPagesUpdateStatusPageByIdResponse;
};

/** @internal */
export type StatusPagesUpdateStatusPageByIdRequest$Outbound = {
  statuspageID: string;
  "V4.StatusPages.UpdateStatusPageByIdRequest":
    models.V4StatusPagesUpdateStatusPageByIdRequest$Outbound;
};

/** @internal */
export const StatusPagesUpdateStatusPageByIdRequest$outboundSchema: z.ZodType<
  StatusPagesUpdateStatusPageByIdRequest$Outbound,
  z.ZodTypeDef,
  StatusPagesUpdateStatusPageByIdRequest
> = z.object({
  statuspageID: z.string(),
  v4StatusPagesUpdateStatusPageByIdRequest:
    models.V4StatusPagesUpdateStatusPageByIdRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v4StatusPagesUpdateStatusPageByIdRequest:
      "V4.StatusPages.UpdateStatusPageByIdRequest",
  });
});

export function statusPagesUpdateStatusPageByIdRequestToJSON(
  statusPagesUpdateStatusPageByIdRequest:
    StatusPagesUpdateStatusPageByIdRequest,
): string {
  return JSON.stringify(
    StatusPagesUpdateStatusPageByIdRequest$outboundSchema.parse(
      statusPagesUpdateStatusPageByIdRequest,
    ),
  );
}

/** @internal */
export const StatusPagesUpdateStatusPageByIdResponse$inboundSchema: z.ZodType<
  StatusPagesUpdateStatusPageByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4StatusPagesUpdateStatusPageByIdResponse$inboundSchema,
});

export function statusPagesUpdateStatusPageByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  StatusPagesUpdateStatusPageByIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      StatusPagesUpdateStatusPageByIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'StatusPagesUpdateStatusPageByIdResponse' from JSON`,
  );
}
