/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type StatusPagesGetStatusPageByIdRequest = {
  statuspageID: string;
};

/**
 * The request has succeeded.
 */
export type StatusPagesGetStatusPageByIdResponse = {
  data: models.V4StatusPagesGetStatusPageByIdResponse;
};

/** @internal */
export type StatusPagesGetStatusPageByIdRequest$Outbound = {
  statuspageID: string;
};

/** @internal */
export const StatusPagesGetStatusPageByIdRequest$outboundSchema: z.ZodType<
  StatusPagesGetStatusPageByIdRequest$Outbound,
  z.ZodTypeDef,
  StatusPagesGetStatusPageByIdRequest
> = z.object({
  statuspageID: z.string(),
});

export function statusPagesGetStatusPageByIdRequestToJSON(
  statusPagesGetStatusPageByIdRequest: StatusPagesGetStatusPageByIdRequest,
): string {
  return JSON.stringify(
    StatusPagesGetStatusPageByIdRequest$outboundSchema.parse(
      statusPagesGetStatusPageByIdRequest,
    ),
  );
}

/** @internal */
export const StatusPagesGetStatusPageByIdResponse$inboundSchema: z.ZodType<
  StatusPagesGetStatusPageByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V4StatusPagesGetStatusPageByIdResponse$inboundSchema,
});

export function statusPagesGetStatusPageByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<StatusPagesGetStatusPageByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      StatusPagesGetStatusPageByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusPagesGetStatusPageByIdResponse' from JSON`,
  );
}
