/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type TaggingRulesGetTaggingRulesRequest = {
  serviceID: string;
};

export type TaggingRulesGetTaggingRulesData = {
  rules: Array<models.V3ServicesTaggingRulesTaggingRuleResponse>;
};

/**
 * The request has succeeded.
 */
export type TaggingRulesGetTaggingRulesResponse = {
  data: TaggingRulesGetTaggingRulesData;
};

/** @internal */
export type TaggingRulesGetTaggingRulesRequest$Outbound = {
  serviceID: string;
};

/** @internal */
export const TaggingRulesGetTaggingRulesRequest$outboundSchema: z.ZodType<
  TaggingRulesGetTaggingRulesRequest$Outbound,
  z.ZodTypeDef,
  TaggingRulesGetTaggingRulesRequest
> = z.object({
  serviceID: z.string(),
});

export function taggingRulesGetTaggingRulesRequestToJSON(
  taggingRulesGetTaggingRulesRequest: TaggingRulesGetTaggingRulesRequest,
): string {
  return JSON.stringify(
    TaggingRulesGetTaggingRulesRequest$outboundSchema.parse(
      taggingRulesGetTaggingRulesRequest,
    ),
  );
}

/** @internal */
export const TaggingRulesGetTaggingRulesData$inboundSchema: z.ZodType<
  TaggingRulesGetTaggingRulesData,
  z.ZodTypeDef,
  unknown
> = z.object({
  rules: z.array(
    models.V3ServicesTaggingRulesTaggingRuleResponse$inboundSchema,
  ),
});

export function taggingRulesGetTaggingRulesDataFromJSON(
  jsonString: string,
): SafeParseResult<TaggingRulesGetTaggingRulesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TaggingRulesGetTaggingRulesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaggingRulesGetTaggingRulesData' from JSON`,
  );
}

/** @internal */
export const TaggingRulesGetTaggingRulesResponse$inboundSchema: z.ZodType<
  TaggingRulesGetTaggingRulesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => TaggingRulesGetTaggingRulesData$inboundSchema),
});

export function taggingRulesGetTaggingRulesResponseFromJSON(
  jsonString: string,
): SafeParseResult<TaggingRulesGetTaggingRulesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TaggingRulesGetTaggingRulesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TaggingRulesGetTaggingRulesResponse' from JSON`,
  );
}
