/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type TeamsUpdateTeamRequest = {
  teamId: string;
  v3TeamsUpdateTeamRequest: models.V3TeamsUpdateTeamRequest;
};

/**
 * The request has succeeded.
 */
export type TeamsUpdateTeamResponse = {
  data: models.V3TeamsTeamResponse;
};

/** @internal */
export type TeamsUpdateTeamRequest$Outbound = {
  teamId: string;
  "V3.Teams.UpdateTeamRequest": models.V3TeamsUpdateTeamRequest$Outbound;
};

/** @internal */
export const TeamsUpdateTeamRequest$outboundSchema: z.ZodType<
  TeamsUpdateTeamRequest$Outbound,
  z.ZodTypeDef,
  TeamsUpdateTeamRequest
> = z.object({
  teamId: z.string(),
  v3TeamsUpdateTeamRequest: models.V3TeamsUpdateTeamRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3TeamsUpdateTeamRequest: "V3.Teams.UpdateTeamRequest",
  });
});

export function teamsUpdateTeamRequestToJSON(
  teamsUpdateTeamRequest: TeamsUpdateTeamRequest,
): string {
  return JSON.stringify(
    TeamsUpdateTeamRequest$outboundSchema.parse(teamsUpdateTeamRequest),
  );
}

/** @internal */
export const TeamsUpdateTeamResponse$inboundSchema: z.ZodType<
  TeamsUpdateTeamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3TeamsTeamResponse$inboundSchema,
});

export function teamsUpdateTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<TeamsUpdateTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamsUpdateTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamsUpdateTeamResponse' from JSON`,
  );
}
