/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TeamsRemoveTeamRequest = {
  teamId: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type TeamsRemoveTeamResponseBody = {};

/** @internal */
export type TeamsRemoveTeamRequest$Outbound = {
  teamId: string;
};

/** @internal */
export const TeamsRemoveTeamRequest$outboundSchema: z.ZodType<
  TeamsRemoveTeamRequest$Outbound,
  z.ZodTypeDef,
  TeamsRemoveTeamRequest
> = z.object({
  teamId: z.string(),
});

export function teamsRemoveTeamRequestToJSON(
  teamsRemoveTeamRequest: TeamsRemoveTeamRequest,
): string {
  return JSON.stringify(
    TeamsRemoveTeamRequest$outboundSchema.parse(teamsRemoveTeamRequest),
  );
}

/** @internal */
export const TeamsRemoveTeamResponseBody$inboundSchema: z.ZodType<
  TeamsRemoveTeamResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function teamsRemoveTeamResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<TeamsRemoveTeamResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamsRemoveTeamResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamsRemoveTeamResponseBody' from JSON`,
  );
}
