/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UsersCreateTokenRequest = {
  userId: string;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type UsersCreateTokenResponse = {
  data: models.V3UsersApiTokenResponse;
};

/** @internal */
export type UsersCreateTokenRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const UsersCreateTokenRequest$outboundSchema: z.ZodType<
  UsersCreateTokenRequest$Outbound,
  z.ZodTypeDef,
  UsersCreateTokenRequest
> = z.object({
  userId: z.string(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
  });
});

export function usersCreateTokenRequestToJSON(
  usersCreateTokenRequest: UsersCreateTokenRequest,
): string {
  return JSON.stringify(
    UsersCreateTokenRequest$outboundSchema.parse(usersCreateTokenRequest),
  );
}

/** @internal */
export const UsersCreateTokenResponse$inboundSchema: z.ZodType<
  UsersCreateTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3UsersApiTokenResponse$inboundSchema,
});

export function usersCreateTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersCreateTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersCreateTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersCreateTokenResponse' from JSON`,
  );
}
