/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded.
 */
export type UsersGetAllTokensResponse = {
  data: Array<models.V3UsersApiTokenResponse>;
};

/** @internal */
export const UsersGetAllTokensResponse$inboundSchema: z.ZodType<
  UsersGetAllTokensResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.V3UsersApiTokenResponse$inboundSchema),
});

export function usersGetAllTokensResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersGetAllTokensResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersGetAllTokensResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersGetAllTokensResponse' from JSON`,
  );
}
