/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type UsersAddUserResponse = {
  data: models.V3UsersUserResponse;
};

/** @internal */
export const UsersAddUserResponse$inboundSchema: z.ZodType<
  UsersAddUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3UsersUserResponse$inboundSchema,
});

export function usersAddUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersAddUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersAddUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersAddUserResponse' from JSON`,
  );
}
