/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WebhooksDeleteWebhookRequest = {
  /**
   * (Required) event webhook ID
   */
  eventWebhookID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type WebhooksDeleteWebhookResponseBody = {};

/** @internal */
export type WebhooksDeleteWebhookRequest$Outbound = {
  eventWebhookID: string;
};

/** @internal */
export const WebhooksDeleteWebhookRequest$outboundSchema: z.ZodType<
  WebhooksDeleteWebhookRequest$Outbound,
  z.ZodTypeDef,
  WebhooksDeleteWebhookRequest
> = z.object({
  eventWebhookID: z.string(),
});

export function webhooksDeleteWebhookRequestToJSON(
  webhooksDeleteWebhookRequest: WebhooksDeleteWebhookRequest,
): string {
  return JSON.stringify(
    WebhooksDeleteWebhookRequest$outboundSchema.parse(
      webhooksDeleteWebhookRequest,
    ),
  );
}

/** @internal */
export const WebhooksDeleteWebhookResponseBody$inboundSchema: z.ZodType<
  WebhooksDeleteWebhookResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function webhooksDeleteWebhookResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<WebhooksDeleteWebhookResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhooksDeleteWebhookResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhooksDeleteWebhookResponseBody' from JSON`,
  );
}
