/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type WebhooksGetAllWebhooksRequest = {
  pageLimit?: string | undefined;
  offset?: string | undefined;
};

/** @internal */
export type WebhooksGetAllWebhooksRequest$Outbound = {
  "page-limit"?: string | undefined;
  offset?: string | undefined;
};

/** @internal */
export const WebhooksGetAllWebhooksRequest$outboundSchema: z.ZodType<
  WebhooksGetAllWebhooksRequest$Outbound,
  z.ZodTypeDef,
  WebhooksGetAllWebhooksRequest
> = z.object({
  pageLimit: z.string().optional(),
  offset: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    pageLimit: "page-limit",
  });
});

export function webhooksGetAllWebhooksRequestToJSON(
  webhooksGetAllWebhooksRequest: WebhooksGetAllWebhooksRequest,
): string {
  return JSON.stringify(
    WebhooksGetAllWebhooksRequest$outboundSchema.parse(
      webhooksGetAllWebhooksRequest,
    ),
  );
}
