/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type WorkflowsListWorkflowsRequest = {
  ownerId: string;
  pageSize?: number | undefined;
  pageNumber?: number | undefined;
  search?: string | undefined;
  event?: Array<string> | undefined;
  actions?: Array<string> | undefined;
  tags?: Array<string> | undefined;
  owner?: Array<string> | undefined;
  createdBy?: Array<string> | undefined;
  updatedBy?: Array<string> | undefined;
  enabled?: string | undefined;
};

export type WorkflowsListWorkflowsResponse = {
  result: models.V3WorkflowsListWorkflowAPIResponse;
};

/** @internal */
export type WorkflowsListWorkflowsRequest$Outbound = {
  owner_id: string;
  page_size?: number | undefined;
  page_number?: number | undefined;
  search?: string | undefined;
  event?: Array<string> | undefined;
  actions?: Array<string> | undefined;
  tags?: Array<string> | undefined;
  owner?: Array<string> | undefined;
  created_by?: Array<string> | undefined;
  updated_by?: Array<string> | undefined;
  enabled?: string | undefined;
};

/** @internal */
export const WorkflowsListWorkflowsRequest$outboundSchema: z.ZodType<
  WorkflowsListWorkflowsRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsListWorkflowsRequest
> = z.object({
  ownerId: z.string(),
  pageSize: z.number().int().optional(),
  pageNumber: z.number().int().optional(),
  search: z.string().optional(),
  event: z.array(z.string()).optional(),
  actions: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  owner: z.array(z.string()).optional(),
  createdBy: z.array(z.string()).optional(),
  updatedBy: z.array(z.string()).optional(),
  enabled: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
    pageSize: "page_size",
    pageNumber: "page_number",
    createdBy: "created_by",
    updatedBy: "updated_by",
  });
});

export function workflowsListWorkflowsRequestToJSON(
  workflowsListWorkflowsRequest: WorkflowsListWorkflowsRequest,
): string {
  return JSON.stringify(
    WorkflowsListWorkflowsRequest$outboundSchema.parse(
      workflowsListWorkflowsRequest,
    ),
  );
}

/** @internal */
export const WorkflowsListWorkflowsResponse$inboundSchema: z.ZodType<
  WorkflowsListWorkflowsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.V3WorkflowsListWorkflowAPIResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function workflowsListWorkflowsResponseFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowsListWorkflowsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkflowsListWorkflowsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowsListWorkflowsResponse' from JSON`,
  );
}
