/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkflowsDeleteWorkflowActionRequest = {
  workflowID: string;
  actionID: string;
};

/**
 * There is no content to send for this request, but the headers may be useful.
 */
export type WorkflowsDeleteWorkflowActionResponseBody = {};

/** @internal */
export type WorkflowsDeleteWorkflowActionRequest$Outbound = {
  workflowID: string;
  actionID: string;
};

/** @internal */
export const WorkflowsDeleteWorkflowActionRequest$outboundSchema: z.ZodType<
  WorkflowsDeleteWorkflowActionRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsDeleteWorkflowActionRequest
> = z.object({
  workflowID: z.string(),
  actionID: z.string(),
});

export function workflowsDeleteWorkflowActionRequestToJSON(
  workflowsDeleteWorkflowActionRequest: WorkflowsDeleteWorkflowActionRequest,
): string {
  return JSON.stringify(
    WorkflowsDeleteWorkflowActionRequest$outboundSchema.parse(
      workflowsDeleteWorkflowActionRequest,
    ),
  );
}

/** @internal */
export const WorkflowsDeleteWorkflowActionResponseBody$inboundSchema: z.ZodType<
  WorkflowsDeleteWorkflowActionResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function workflowsDeleteWorkflowActionResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkflowsDeleteWorkflowActionResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowsDeleteWorkflowActionResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkflowsDeleteWorkflowActionResponseBody' from JSON`,
  );
}
