/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type WorkflowsCreateActionRequest = {
  workflowID: string;
  v3WorkflowsActionRequest?: models.V3WorkflowsActionRequest | undefined;
};

/**
 * The request has succeeded and a new resource has been created as a result.
 */
export type WorkflowsCreateActionResponse = {
  data?: models.V3WorkflowsActionResponse | undefined;
};

/** @internal */
export type WorkflowsCreateActionRequest$Outbound = {
  workflowID: string;
  "V3.Workflows.ActionRequest"?:
    | models.V3WorkflowsActionRequest$Outbound
    | undefined;
};

/** @internal */
export const WorkflowsCreateActionRequest$outboundSchema: z.ZodType<
  WorkflowsCreateActionRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsCreateActionRequest
> = z.object({
  workflowID: z.string(),
  v3WorkflowsActionRequest: models.V3WorkflowsActionRequest$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    v3WorkflowsActionRequest: "V3.Workflows.ActionRequest",
  });
});

export function workflowsCreateActionRequestToJSON(
  workflowsCreateActionRequest: WorkflowsCreateActionRequest,
): string {
  return JSON.stringify(
    WorkflowsCreateActionRequest$outboundSchema.parse(
      workflowsCreateActionRequest,
    ),
  );
}

/** @internal */
export const WorkflowsCreateActionResponse$inboundSchema: z.ZodType<
  WorkflowsCreateActionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3WorkflowsActionResponse$inboundSchema.optional(),
});

export function workflowsCreateActionResponseFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowsCreateActionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkflowsCreateActionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowsCreateActionResponse' from JSON`,
  );
}
