/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type WorkflowsGetWorkflowByIdRequest = {
  workflowID: string;
};

/** @internal */
export type WorkflowsGetWorkflowByIdRequest$Outbound = {
  workflowID: string;
};

/** @internal */
export const WorkflowsGetWorkflowByIdRequest$outboundSchema: z.ZodType<
  WorkflowsGetWorkflowByIdRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsGetWorkflowByIdRequest
> = z.object({
  workflowID: z.string(),
});

export function workflowsGetWorkflowByIdRequestToJSON(
  workflowsGetWorkflowByIdRequest: WorkflowsGetWorkflowByIdRequest,
): string {
  return JSON.stringify(
    WorkflowsGetWorkflowByIdRequest$outboundSchema.parse(
      workflowsGetWorkflowByIdRequest,
    ),
  );
}
