/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type WorkflowsUpdateActionsOrderRequest = {
  workflowID: string;
  v3WorkflowsUpdateActionsOrderRequest:
    models.V3WorkflowsUpdateActionsOrderRequest;
};

/** @internal */
export type WorkflowsUpdateActionsOrderRequest$Outbound = {
  workflowID: string;
  "V3.Workflows.UpdateActionsOrderRequest":
    models.V3WorkflowsUpdateActionsOrderRequest$Outbound;
};

/** @internal */
export const WorkflowsUpdateActionsOrderRequest$outboundSchema: z.ZodType<
  WorkflowsUpdateActionsOrderRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsUpdateActionsOrderRequest
> = z.object({
  workflowID: z.string(),
  v3WorkflowsUpdateActionsOrderRequest:
    models.V3WorkflowsUpdateActionsOrderRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3WorkflowsUpdateActionsOrderRequest:
      "V3.Workflows.UpdateActionsOrderRequest",
  });
});

export function workflowsUpdateActionsOrderRequestToJSON(
  workflowsUpdateActionsOrderRequest: WorkflowsUpdateActionsOrderRequest,
): string {
  return JSON.stringify(
    WorkflowsUpdateActionsOrderRequest$outboundSchema.parse(
      workflowsUpdateActionsOrderRequest,
    ),
  );
}
