/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type WorkflowsUpdateWorkflowRequest = {
  workflowID: string;
  v3WorkflowsCreateWorkflowRequestUpdate:
    models.V3WorkflowsCreateWorkflowRequestUpdate;
};

/**
 * The request has succeeded.
 */
export type WorkflowsUpdateWorkflowResponse = {
  data: models.V3WorkflowsUpdateWorkflowAPIResponse;
};

/** @internal */
export type WorkflowsUpdateWorkflowRequest$Outbound = {
  workflowID: string;
  "V3.Workflows.CreateWorkflowRequestUpdate":
    models.V3WorkflowsCreateWorkflowRequestUpdate$Outbound;
};

/** @internal */
export const WorkflowsUpdateWorkflowRequest$outboundSchema: z.ZodType<
  WorkflowsUpdateWorkflowRequest$Outbound,
  z.ZodTypeDef,
  WorkflowsUpdateWorkflowRequest
> = z.object({
  workflowID: z.string(),
  v3WorkflowsCreateWorkflowRequestUpdate:
    models.V3WorkflowsCreateWorkflowRequestUpdate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    v3WorkflowsCreateWorkflowRequestUpdate:
      "V3.Workflows.CreateWorkflowRequestUpdate",
  });
});

export function workflowsUpdateWorkflowRequestToJSON(
  workflowsUpdateWorkflowRequest: WorkflowsUpdateWorkflowRequest,
): string {
  return JSON.stringify(
    WorkflowsUpdateWorkflowRequest$outboundSchema.parse(
      workflowsUpdateWorkflowRequest,
    ),
  );
}

/** @internal */
export const WorkflowsUpdateWorkflowResponse$inboundSchema: z.ZodType<
  WorkflowsUpdateWorkflowResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.V3WorkflowsUpdateWorkflowAPIResponse$inboundSchema,
});

export function workflowsUpdateWorkflowResponseFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowsUpdateWorkflowResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkflowsUpdateWorkflowResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowsUpdateWorkflowResponse' from JSON`,
  );
}
