/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @solarwinds/squadcast-sdk-typescript SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx analyticsGetOrganization.example.ts
 */

import { SquadcastSDK } from "@solarwinds/squadcast-sdk-typescript";

const squadcastSDK = new SquadcastSDK({
  serverURL: "https://api.squadcast.com",
  refreshTokenAuth: "17618c502d31d615a024d89f60ab16ea0d774adc2c30c249cb5ee0b9178541a722d8fe8bd71ddeecde127151c3e7fa6e1b56ab7ddeb873f83b2aaadb9965add4",
});

async function main() {
  const result = await squadcastSDK.users.getAllTokens();

  console.log(result);
}

main().catch(console.error);
