/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditLogsExport } from "../funcs/auditLogsExport.js";
import { auditLogsGetById } from "../funcs/auditLogsGetById.js";
import { auditLogsList } from "../funcs/auditLogsList.js";
import { auditLogsListExportHistory } from "../funcs/auditLogsListExportHistory.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { ExportHistory } from "./exporthistory.js";

export class AuditLogs extends ClientSDK {
  private _exportHistory?: ExportHistory;
  get exportHistory(): ExportHistory {
    return (this._exportHistory ??= new ExportHistory(this._options));
  }

  /**
   * List all Audit Logs
   *
   * @remarks
   * List all Audit Logs
   * Returns array of audit logs for given team and filters
   */
  async list(
    request: operations.AuditLogsListAuditLogsRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.AuditLogsListAuditLogsResponse, { page: number }>
  > {
    return unwrapResultIterator(auditLogsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Initiate an asynchronous export of audit logs based on the provided filters. The export file will be generated and available for download. Use 'Get details of Audit Logs export history by ID' API to retrieve the download URL.
   *
   * @remarks
   * Export Audit logs
   * Initiates export of audit logs based on provided filters
   */
  async export(
    request: models.V3AuditLogsExportAuditLogsRequest,
    options?: RequestOptions,
  ): Promise<models.V3AuditLogsExportAuditLogsResponse> {
    return unwrapAsync(auditLogsExport(
      this,
      request,
      options,
    ));
  }

  /**
   * List all Audit Logs export history
   *
   * @remarks
   * List all Audit Logs export history
   * Returns array of audit logs export history
   */
  async listExportHistory(
    request: operations.AuditLogsListAuditLogsExportHistoryRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.AuditLogsListAuditLogsExportHistoryResponse,
      { page: number }
    >
  > {
    return unwrapResultIterator(auditLogsListExportHistory(
      this,
      request,
      options,
    ));
  }

  /**
   * Get audit log by ID
   *
   * @remarks
   * Get audit log by ID
   * Returns audit log details for the specified ID
   */
  async getById(
    request: operations.AuditLogsGetAuditLogByIdRequest,
    options?: RequestOptions,
  ): Promise<models.V3AuditLogsGetAuditLogByIDResponse> {
    return unwrapAsync(auditLogsGetById(
      this,
      request,
      options,
    ));
  }
}
