/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentActionsCircleciRebuild } from "../funcs/incidentActionsCircleciRebuild.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Circleci extends ClientSDK {
  /**
   * Rebuild a Project In CircleCI
   */
  async rebuild(
    request: operations.IncidentActionsRebuildAProjectInCircleciRequest,
    options?: RequestOptions,
  ): Promise<operations.IncidentActionsRebuildAProjectInCircleciResponse> {
    return unwrapAsync(incidentActionsCircleciRebuild(
      this,
      request,
      options,
    ));
  }
}
