/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { communicationCardsCreateSlackChannel } from "../funcs/communicationCardsCreateSlackChannel.js";
import { communicationCardsDelete } from "../funcs/communicationCardsDelete.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CommunicationCards extends ClientSDK {
  /**
   * Create Slack Channel in Communication Card
   */
  async createSlackChannel(
    request: models.V3IncidentsCommunicationCardsCreateSlackChannelRequest,
    options?: RequestOptions,
  ): Promise<
    operations.CommunicationCardsCreateSlackChannelInCommunicationCardResponse
  > {
    return unwrapAsync(communicationCardsCreateSlackChannel(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Communication Card
   *
   * @remarks
   * Delete communication card by providing communicationCardId for incidentId mentioned in params
   *
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `service-write` scope.
   */
  async delete(
    request: operations.CommunicationCardsDeleteCommunicationCardRequest,
    options?: RequestOptions,
  ): Promise<operations.CommunicationCardsDeleteCommunicationCardResponse> {
    return unwrapAsync(communicationCardsDelete(
      this,
      request,
      options,
    ));
  }
}
