/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statusPagesComponentGroupsCreate } from "../funcs/statusPagesComponentGroupsCreate.js";
import { statusPagesComponentGroupsDeleteById } from "../funcs/statusPagesComponentGroupsDeleteById.js";
import { statusPagesComponentGroupsGetById } from "../funcs/statusPagesComponentGroupsGetById.js";
import { statusPagesComponentGroupsList } from "../funcs/statusPagesComponentGroupsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ComponentGroups extends ClientSDK {
  /**
   * List Component Groups
   */
  async list(
    request: operations.ComponentGroupsListComponentGroupsRequest,
    options?: RequestOptions,
  ): Promise<operations.ComponentGroupsListComponentGroupsResponse> {
    return unwrapAsync(statusPagesComponentGroupsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Component Group
   */
  async create(
    request: operations.ComponentGroupsCreateComponentGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.ComponentGroupsCreateComponentGroupResponse> {
    return unwrapAsync(statusPagesComponentGroupsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Component Group By ID
   */
  async deleteById(
    request: operations.ComponentGroupsDeleteComponentGroupByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.ComponentGroupsDeleteComponentGroupByIdResponse> {
    return unwrapAsync(statusPagesComponentGroupsDeleteById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Component Group By ID
   */
  async getById(
    request: operations.ComponentGroupsGetComponentGroupByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.ComponentGroupsGetComponentGroupByIdResponse> {
    return unwrapAsync(statusPagesComponentGroupsGetById(
      this,
      request,
      options,
    ));
  }
}
