/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deduplicationRulesCreateOrUpdate } from "../funcs/deduplicationRulesCreateOrUpdate.js";
import { deduplicationRulesGetRules } from "../funcs/deduplicationRulesGetRules.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DeduplicationRules extends ClientSDK {
  /**
   * Get Deduplication Rules
   */
  async getRules(
    request: operations.DeduplicationRulesGetDeduplicationRulesRequest,
    options?: RequestOptions,
  ): Promise<operations.DeduplicationRulesGetDeduplicationRulesResponse> {
    return unwrapAsync(deduplicationRulesGetRules(
      this,
      request,
      options,
    ));
  }

  /**
   * Create or Update Deduplication Rules
   */
  async createOrUpdate(
    request:
      operations.DeduplicationRulesCreateOrUpdateDeduplicationRulesRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeduplicationRulesCreateOrUpdateDeduplicationRulesResponse
  > {
    return unwrapAsync(deduplicationRulesCreateOrUpdate(
      this,
      request,
      options,
    ));
  }
}
