/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { servicesDependenciesCreateOrUpdate } from "../funcs/servicesDependenciesCreateOrUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Dependencies extends ClientSDK {
  /**
   * Create or Update Dependencies
   */
  async createOrUpdate(
    request: operations.DependenciesCreateOrUpdateDependenciesRequest,
    options?: RequestOptions,
  ): Promise<operations.DependenciesCreateOrUpdateDependenciesResponse> {
    return unwrapAsync(servicesDependenciesCreateOrUpdate(
      this,
      request,
      options,
    ));
  }
}
