/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { extensionsWebhooksCreate } from "../funcs/extensionsWebhooksCreate.js";
import { extensionsWebhooksUpdate } from "../funcs/extensionsWebhooksUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ExtensionsWebhooks extends ClientSDK {
  /**
   * Create Webhook
   *
   * @remarks
   * Add webhook to the organization. Returns the webhook object in response.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `user-write` scope.
   */
  async create(
    request: models.V3ExtensionsWebhooksWebhook,
    options?: RequestOptions,
  ): Promise<operations.WebhooksCreateWebhookResponse> {
    return unwrapAsync(extensionsWebhooksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Webhook
   *
   * @remarks
   * Update organization webhook details.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `user-write` scope.
   */
  async update(
    request: operations.WebhooksUpdateWebhookRequest,
    options?: RequestOptions,
  ): Promise<operations.WebhooksUpdateWebhookResponse> {
    return unwrapAsync(extensionsWebhooksUpdate(
      this,
      request,
      options,
    ));
  }
}
