/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { extensionsMsteamsGetConfig } from "../funcs/extensionsMsteamsGetConfig.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ExtensionsMsteams extends ClientSDK {
  /**
   * Get MSTeams Config
   *
   * @remarks
   * Returns MSTeams config of the organization.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `read` scope.
   */
  async getConfig(
    options?: RequestOptions,
  ): Promise<operations.MSTeamsGetMsteamsConfigResponse> {
    return unwrapAsync(extensionsMsteamsGetConfig(
      this,
      options,
    ));
  }
}
