/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { ExtensionsMsteams } from "./extensionsmsteams.js";
import { ExtensionsWebhooks } from "./extensionswebhooks.js";

export class Extensions extends ClientSDK {
  private _webhooks?: ExtensionsWebhooks;
  get webhooks(): ExtensionsWebhooks {
    return (this._webhooks ??= new ExtensionsWebhooks(this._options));
  }

  private _msteams?: ExtensionsMsteams;
  get msteams(): ExtensionsMsteams {
    return (this._msteams ??= new ExtensionsMsteams(this._options));
  }
}
