/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { globalEventRulesRulesetsCreate } from "../funcs/globalEventRulesRulesetsCreate.js";
import { globalEventRulesRulesetsCreateRule } from "../funcs/globalEventRulesRulesetsCreateRule.js";
import { globalEventRulesRulesetsGet } from "../funcs/globalEventRulesRulesetsGet.js";
import { globalEventRulesRulesetsListRules } from "../funcs/globalEventRulesRulesetsListRules.js";
import { globalEventRulesRulesetsReorder } from "../funcs/globalEventRulesRulesetsReorder.js";
import { globalEventRulesRulesetsUpdate } from "../funcs/globalEventRulesRulesetsUpdate.js";
import { globalEventRulesRulesetsUpdateRule } from "../funcs/globalEventRulesRulesetsUpdateRule.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { RulesetsRules } from "./rulesetsrules.js";

export class GlobalEventRulesRulesets extends ClientSDK {
  private _rules?: RulesetsRules;
  get rules(): RulesetsRules {
    return (this._rules ??= new RulesetsRules(this._options));
  }

  /**
   * Create Ruleset
   *
   * @remarks
   * Create a GER Ruleset.
   */
  async create(
    request: operations.GlobalEventRulesCreateRulesetRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesCreateRulesetResponse> {
    return unwrapAsync(globalEventRulesRulesetsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Ruleset
   *
   * @remarks
   * Get a GER Ruleset
   */
  async get(
    request: operations.GlobalEventRulesGetRulesetRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesGetRulesetResponse> {
    return unwrapAsync(globalEventRulesRulesetsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Ruleset
   *
   * @remarks
   * Update a GER Ruleset
   */
  async update(
    request: operations.GlobalEventRulesUpdateRulesetRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesUpdateRulesetResponse> {
    return unwrapAsync(globalEventRulesRulesetsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Reorder Ruleset
   *
   * @remarks
   * Reorder rules of a GER Ruleset
   */
  async reorder(
    request: operations.GlobalEventRulesReorderRulesetRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesReorderRulesetResponse> {
    return unwrapAsync(globalEventRulesRulesetsReorder(
      this,
      request,
      options,
    ));
  }

  /**
   * List Ruleset Rules
   *
   * @remarks
   * Get all rules of a GER Ruleset.
   */
  async listRules(
    request: operations.GlobalEventRulesListRulesetRulesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GlobalEventRulesListRulesetRulesResponse,
      { page: number }
    >
  > {
    return unwrapResultIterator(globalEventRulesRulesetsListRules(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Rule
   *
   * @remarks
   * Create a GER Ruleset Rule.
   */
  async createRule(
    request: operations.GlobalEventRulesCreateRuleRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesCreateRuleResponse> {
    return unwrapAsync(globalEventRulesRulesetsCreateRule(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Rule by ID
   *
   * @remarks
   * Update a GER Ruleset Rule by its ID.
   */
  async updateRule(
    request: operations.GlobalEventRulesUpdateRuleByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesUpdateRuleByIdResponse> {
    return unwrapAsync(globalEventRulesRulesetsUpdateRule(
      this,
      request,
      options,
    ));
  }
}
