/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { globalEventRulesCreate } from "../funcs/globalEventRulesCreate.js";
import { globalEventRulesDeleteById } from "../funcs/globalEventRulesDeleteById.js";
import { globalEventRulesGetById } from "../funcs/globalEventRulesGetById.js";
import { globalEventRulesList } from "../funcs/globalEventRulesList.js";
import { globalEventRulesUpdateById } from "../funcs/globalEventRulesUpdateById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { GlobalEventRulesRulesets } from "./globaleventrulesrulesets.js";

export class GlobalEventRules extends ClientSDK {
  private _rulesets?: GlobalEventRulesRulesets;
  get rulesets(): GlobalEventRulesRulesets {
    return (this._rulesets ??= new GlobalEventRulesRulesets(this._options));
  }

  /**
   * List Global Event Rules
   *
   * @remarks
   * Get a list of all GERs
   */
  async list(
    request: operations.GlobalEventRulesListGlobalEventRulesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<
      operations.GlobalEventRulesListGlobalEventRulesResponse,
      { page: number }
    >
  > {
    return unwrapResultIterator(globalEventRulesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Global Event Rule
   *
   * @remarks
   * Create a GER
   */
  async create(
    request: models.V3GlobalEventRulesCreateGlobalEventRuleRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesCreateGlobalEventRuleResponse> {
    return unwrapAsync(globalEventRulesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Global Event Rule by ID
   *
   * @remarks
   * Delete a GER by its ID
   */
  async deleteById(
    request: operations.GlobalEventRulesDeleteGlobalEventRuleByIdRequest,
    options?: RequestOptions,
  ): Promise<Uint8Array> {
    return unwrapAsync(globalEventRulesDeleteById(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Global Event Rule by ID
   *
   * @remarks
   * Get a GER by its ID
   */
  async getById(
    request: operations.GlobalEventRulesGetGlobalEventRuleByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesGetGlobalEventRuleByIdResponse> {
    return unwrapAsync(globalEventRulesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Global Event Rule by ID
   *
   * @remarks
   * Update a GER by its ID
   */
  async updateById(
    request: operations.GlobalEventRulesUpdateGlobalEventRuleByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GlobalEventRulesUpdateGlobalEventRuleByIdResponse> {
    return unwrapAsync(globalEventRulesUpdateById(
      this,
      request,
      options,
    ));
  }
}
