/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Circleci } from "./circleci.js";

export class IncidentActions extends ClientSDK {
  private _circleci?: Circleci;
  get circleci(): Circleci {
    return (this._circleci ??= new Circleci(this._options));
  }
}
