/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsPostmortemsCreate } from "../funcs/incidentsPostmortemsCreate.js";
import { incidentsPostmortemsGetAll } from "../funcs/incidentsPostmortemsGetAll.js";
import { incidentsPostmortemsGetByIncident } from "../funcs/incidentsPostmortemsGetByIncident.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class IncidentsPostmortems extends ClientSDK {
  /**
   * Get All Postmortems
   *
   * @remarks
   * *   This endpoint is used to get all postmortems.
   * *   Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header.
   */
  async getAll(
    request: operations.PostmortemsGetAllPostmortemsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostmortemsGetAllPostmortemsResponse> {
    return unwrapAsync(incidentsPostmortemsGetAll(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Postmortem By Incident
   *
   * @remarks
   * *   This endpoint is used to get a postmortem by incident.
   * *   Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header.
   */
  async getByIncident(
    request: operations.PostmortemsGetPostmortemByIncidentRequest,
    options?: RequestOptions,
  ): Promise<operations.PostmortemsGetPostmortemByIncidentResponse> {
    return unwrapAsync(incidentsPostmortemsGetByIncident(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Postmortem
   *
   * @remarks
   * *   This endpoint is used to create a postmortem.
   * *   Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header.
   */
  async create(
    request: operations.PostmortemsCreatePostmortemRequest,
    options?: RequestOptions,
  ): Promise<operations.PostmortemsCreatePostmortemResponse> {
    return unwrapAsync(incidentsPostmortemsCreate(
      this,
      request,
      options,
    ));
  }
}
