/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsNotesCreate } from "../funcs/incidentsNotesCreate.js";
import { incidentsNotesList } from "../funcs/incidentsNotesList.js";
import { incidentsNotesUpdate } from "../funcs/incidentsNotesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class IncidentsNotes extends ClientSDK {
  /**
   * Create Notes
   */
  async create(
    request: operations.NotesCreateNotesRequest,
    options?: RequestOptions,
  ): Promise<operations.NotesCreateNotesResponse> {
    return unwrapAsync(incidentsNotesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get All Notes
   *
   * @remarks
   * *   This endpoint is used to get all the note details of incidentID mentioned params.
   * *   Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header.
   */
  async list(
    request: operations.NotesGetAllNotesRequest,
    options?: RequestOptions,
  ): Promise<operations.NotesGetAllNotesResponse> {
    return unwrapAsync(incidentsNotesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Note
   *
   * @remarks
   * This API can be used to update a Note or a Resolution reason associated with an incident
   */
  async update(
    request: operations.NotesUpdateNoteRequest,
    options?: RequestOptions,
  ): Promise<operations.NotesUpdateNoteResponse> {
    return unwrapAsync(incidentsNotesUpdate(
      this,
      request,
      options,
    ));
  }
}
