/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { issueStatesList } from "../funcs/issueStatesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class IssueStates extends ClientSDK {
  /**
   * List Status Page Issue States
   */
  async list(
    request: operations.IssuesListStatusPageIssueStatesRequest,
    options?: RequestOptions,
  ): Promise<operations.IssuesListStatusPageIssueStatesResponse> {
    return unwrapAsync(issueStatesList(
      this,
      request,
      options,
    ));
  }
}
