/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsActionsJiraCloudCreateTicket } from "../funcs/incidentsActionsJiraCloudCreateTicket.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class JiraCloud extends ClientSDK {
  /**
   * Create a Ticket on Jira Cloud
   */
  async createTicket(
    request: operations.IncidentActionsCreateATicketOnJiraCloudRequest,
    options?: RequestOptions,
  ): Promise<operations.IncidentActionsCreateATicketOnJiraCloudResponse> {
    return unwrapAsync(incidentsActionsJiraCloudCreateTicket(
      this,
      request,
      options,
    ));
  }
}
