/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { msteamsCreateOrUpdateConfiguration } from "../funcs/msteamsCreateOrUpdateConfiguration.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Msteams extends ClientSDK {
  /**
   * Create Or Update MSTeams Configuration
   *
   * @remarks
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `user-write` scope.
   */
  async createOrUpdateConfiguration(
    request: models.V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.MSTeamsCreateOrUpdateMsteamsConfigurationResponse> {
    return unwrapAsync(msteamsCreateOrUpdateConfiguration(
      this,
      request,
      options,
    ));
  }
}
