/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rulesDeleteById } from "../funcs/rulesDeleteById.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rules extends ClientSDK {
  /**
   * Delete Rule by ID
   *
   * @remarks
   * Delete a GER Ruleset Rule by its ID.
   */
  async deleteById(
    request: operations.GlobalEventRulesDeleteRuleByIdRequest,
    options?: RequestOptions,
  ): Promise<Uint8Array> {
    return unwrapAsync(rulesDeleteById(
      this,
      request,
      options,
    ));
  }
}
