/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runbooksCreate } from "../funcs/runbooksCreate.js";
import { runbooksGetById } from "../funcs/runbooksGetById.js";
import { runbooksListByTeam } from "../funcs/runbooksListByTeam.js";
import { runbooksRemove } from "../funcs/runbooksRemove.js";
import { runbooksUpdate } from "../funcs/runbooksUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Runbooks extends ClientSDK {
  /**
   * Get All Runbooks By Team
   *
   * @remarks
   * Returns all the runbooks of the team.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `read` scope.
   */
  async listByTeam(
    options?: RequestOptions,
  ): Promise<operations.RunbooksGetAllRunbooksByTeamResponse> {
    return unwrapAsync(runbooksListByTeam(
      this,
      options,
    ));
  }

  /**
   * Create Runbook
   *
   * @remarks
   * Add runbook to the team. Returns the runbook object in response.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `user-write` scope.
   */
  async create(
    request: models.V3RunbooksCreateRunbookRequest,
    options?: RequestOptions,
  ): Promise<operations.RunbooksCreateRunbookResponse> {
    return unwrapAsync(runbooksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove Runbook
   *
   * @remarks
   * Remove runbook from team.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `user-write` scope.
   */
  async remove(
    request: operations.RunbooksRemoveRunbookRequest,
    options?: RequestOptions,
  ): Promise<Uint8Array> {
    return unwrapAsync(runbooksRemove(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Runbook By ID
   *
   * @remarks
   * Returns a runbook details of the given `runbookID` in the request param.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `read` scope.
   */
  async getById(
    request: operations.RunbooksGetRunbookByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.RunbooksGetRunbookByIdResponse> {
    return unwrapAsync(runbooksGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Runbook
   *
   * @remarks
   * Update runbook details.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `user-write` scope.
   */
  async update(
    request: operations.RunbooksUpdateRunbookRequest,
    options?: RequestOptions,
  ): Promise<operations.RunbooksUpdateRunbookResponse> {
    return unwrapAsync(runbooksUpdate(
      this,
      request,
      options,
    ));
  }
}
