/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schedulesChangeTimezone } from "../funcs/schedulesChangeTimezone.js";
import { schedulesClone } from "../funcs/schedulesClone.js";
import { schedulesCreate } from "../funcs/schedulesCreate.js";
import { schedulesCreateIcalLink } from "../funcs/schedulesCreateIcalLink.js";
import { schedulesCreateRotation } from "../funcs/schedulesCreateRotation.js";
import { schedulesDelete } from "../funcs/schedulesDelete.js";
import { schedulesDeleteOverride } from "../funcs/schedulesDeleteOverride.js";
import { schedulesGetById } from "../funcs/schedulesGetById.js";
import { schedulesGetOverrideById } from "../funcs/schedulesGetOverrideById.js";
import { schedulesList } from "../funcs/schedulesList.js";
import { schedulesUpdate } from "../funcs/schedulesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { SchedulesActions } from "./schedulesactions.js";
import { SchedulesExport } from "./schedulesexport.js";
import { SchedulesOverrides } from "./schedulesoverrides.js";
import { SchedulesRotations } from "./schedulesrotations.js";

export class Schedules extends ClientSDK {
  private _actions?: SchedulesActions;
  get actions(): SchedulesActions {
    return (this._actions ??= new SchedulesActions(this._options));
  }

  private _export?: SchedulesExport;
  get export(): SchedulesExport {
    return (this._export ??= new SchedulesExport(this._options));
  }

  private _overrides?: SchedulesOverrides;
  get overrides(): SchedulesOverrides {
    return (this._overrides ??= new SchedulesOverrides(this._options));
  }

  private _rotations?: SchedulesRotations;
  get rotations(): SchedulesRotations {
    return (this._rotations ??= new SchedulesRotations(this._options));
  }

  /**
   * List Schedules
   */
  async list(
    request: operations.SchedulesListSchedulesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.SchedulesListSchedulesResponse, { cursor: string }>
  > {
    return unwrapResultIterator(schedulesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Schedule
   */
  async create(
    request: models.V4CreateScheduleRequest,
    options?: RequestOptions,
  ): Promise<operations.SchedulesCreateScheduleResponse> {
    return unwrapAsync(schedulesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Schedule
   */
  async delete(
    request: operations.SchedulesDeleteScheduleRequest,
    options?: RequestOptions,
  ): Promise<Uint8Array> {
    return unwrapAsync(schedulesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Schedule by ID
   */
  async getById(
    request: operations.SchedulesGetScheduleByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.SchedulesGetScheduleByIdResponse> {
    return unwrapAsync(schedulesGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Schedule
   */
  async update(
    request: operations.SchedulesUpdateScheduleRequest,
    options?: RequestOptions,
  ): Promise<operations.SchedulesUpdateScheduleResponse> {
    return unwrapAsync(schedulesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Change Timezone
   */
  async changeTimezone(
    request: operations.SchedulesChangeTimezoneRequest,
    options?: RequestOptions,
  ): Promise<operations.SchedulesChangeTimezoneResponse> {
    return unwrapAsync(schedulesChangeTimezone(
      this,
      request,
      options,
    ));
  }

  /**
   * Clone Schedule
   */
  async clone(
    request: operations.SchedulesCloneScheduleRequest,
    options?: RequestOptions,
  ): Promise<operations.SchedulesCloneScheduleResponse> {
    return unwrapAsync(schedulesClone(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Schedule ICal Link
   */
  async createIcalLink(
    request: operations.ExportCreateScheduleIcalLinkRequest,
    options?: RequestOptions,
  ): Promise<operations.ExportCreateScheduleIcalLinkResponse> {
    return unwrapAsync(schedulesCreateIcalLink(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Schedule Override
   */
  async deleteOverride(
    request: operations.OverridesDeleteScheduleOverrideRequest,
    options?: RequestOptions,
  ): Promise<Uint8Array> {
    return unwrapAsync(schedulesDeleteOverride(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Override by ID
   */
  async getOverrideById(
    request: operations.OverridesGetOverrideByIdRequest,
    options?: RequestOptions,
  ): Promise<operations.OverridesGetOverrideByIdResponse> {
    return unwrapAsync(schedulesGetOverrideById(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Rotation
   */
  async createRotation(
    request: operations.RotationsCreateRotationRequest,
    options?: RequestOptions,
  ): Promise<operations.RotationsCreateRotationResponse> {
    return unwrapAsync(schedulesCreateRotation(
      this,
      request,
      options,
    ));
  }
}
