/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { schedulesRotationsUpdate } from "../funcs/schedulesRotationsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SchedulesRotations extends ClientSDK {
  /**
   * Update Rotation
   */
  async update(
    request: operations.RotationsUpdateRotationRequest,
    options?: RequestOptions,
  ): Promise<operations.RotationsUpdateRotationResponse> {
    return unwrapAsync(schedulesRotationsUpdate(
      this,
      request,
      options,
    ));
  }
}
