/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { squadsCreateV4 } from "../funcs/squadsCreateV4.js";
import { squadsDelete } from "../funcs/squadsDelete.js";
import { squadsList } from "../funcs/squadsList.js";
import { squadsUpdateMember } from "../funcs/squadsUpdateMember.js";
import { squadsUpdateName } from "../funcs/squadsUpdateName.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { SquadsMembers } from "./squadsmembers.js";

export class Squads extends ClientSDK {
  private _members?: SquadsMembers;
  get members(): SquadsMembers {
    return (this._members ??= new SquadsMembers(this._options));
  }

  /**
   * Get All Squads
   *
   * @remarks
   * This endpoint is used to get all the squads details of your organization.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `squad-read` scope.
   */
  async list(
    request: operations.SquadsGetAllSquadsRequest,
    options?: RequestOptions,
  ): Promise<operations.SquadsGetAllSquadsResponse> {
    return unwrapAsync(squadsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Squad
   *
   * @remarks
   * This endpoint is used to create a new squad.
   * The role will be considered only if your organization is on the OBAC permission model; otherwise, the role field will be ignored, and only the member will be added to the squad.
   *
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `squad-create` scope.
   */
  async createV4(
    request: models.V4SquadsCreateSquadRequest,
    options?: RequestOptions,
  ): Promise<operations.SquadsCreateSquadResponse> {
    return unwrapAsync(squadsCreateV4(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Squad Member
   *
   * @remarks
   * This endpoint is used to update a squad member's role and is only accessible if your organization is using the OBAC permission model.
   *
   * If you're attempting to update a member's role from 'owner' to 'member', and that 'owner' is the last squad owner, then the 'replaceWith' query parameter is required. Setting 'replaceWith' to 'member' will promote the member to the role of owner.
   *
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `squad-create` scope.
   */
  async updateMember(
    request: operations.SquadsUpdateSquadMemberRequest,
    options?: RequestOptions,
  ): Promise<models.V4SquadsUpdateSquadMemberResponse> {
    return unwrapAsync(squadsUpdateMember(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Squad Name
   *
   * @remarks
   * This endpoint is used to update squad's name.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `squad-create` scope.
   */
  async updateName(
    request: operations.SquadsUpdateSquadNameRequest,
    options?: RequestOptions,
  ): Promise<operations.SquadsUpdateSquadNameResponse> {
    return unwrapAsync(squadsUpdateName(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Squad
   *
   * @remarks
   * This endpoint is used to delete the squad. Squad should not be assigned to any incident or part of any escalation policy.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `squad-update` scope.
   */
  async delete(
    request: operations.SquadsDeleteSquadRequest,
    options?: RequestOptions,
  ): Promise<Uint8Array> {
    return unwrapAsync(squadsDelete(
      this,
      request,
      options,
    ));
  }
}
