/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { incidentsTagsAppend } from "../funcs/incidentsTagsAppend.js";
import { incidentsTagsUpdate } from "../funcs/incidentsTagsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tags extends ClientSDK {
  /**
   * Update Tag
   */
  async update(
    request: operations.TagsUpdateTagRequest,
    options?: RequestOptions,
  ): Promise<operations.TagsUpdateTagResponse> {
    return unwrapAsync(incidentsTagsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Append Tag
   */
  async append(
    request: operations.TagsAppendTagRequest,
    options?: RequestOptions,
  ): Promise<operations.TagsAppendTagResponse> {
    return unwrapAsync(incidentsTagsAppend(
      this,
      request,
      options,
    ));
  }
}
