/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tokensCreate } from "../funcs/tokensCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Tokens extends ClientSDK {
  /**
   * Create Token
   *
   * @remarks
   * Generates refresh token for a user of the organization. Returns the refresh token object in response.
   * Requires `access_token` as a `Bearer {{token}}` in the `Authorization` header with `user-write` scope.
   */
  async create(
    request: operations.UsersCreateTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.UsersCreateTokenResponse> {
    return unwrapAsync(tokensCreate(
      this,
      request,
      options,
    ));
  }
}
