/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workflowLogsGet } from "../funcs/workflowLogsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class WorkflowLogs extends ClientSDK {
  /**
   * Get Workflow Logs
   *
   * @remarks
   * Get workflow logs
   */
  async get(
    request: operations.WorkflowsGetWorkflowLogsRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.WorkflowsGetWorkflowLogsResponse, { page: number }>
  > {
    return unwrapResultIterator(workflowLogsGet(
      this,
      request,
      options,
    ));
  }
}
