/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CommonV4PageInfo = {
  pageSize: number;
  hasNext: boolean;
  hasPrevious: boolean;
  nextCursor?: string | undefined;
  previousCursor?: string | undefined;
};

/** @internal */
export const CommonV4PageInfo$inboundSchema: z.ZodType<
  CommonV4PageInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  pageSize: z.number().int(),
  hasNext: z.boolean(),
  hasPrevious: z.boolean(),
  nextCursor: z.string().optional(),
  previousCursor: z.string().optional(),
});

export function commonV4PageInfoFromJSON(
  jsonString: string,
): SafeParseResult<CommonV4PageInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommonV4PageInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommonV4PageInfo' from JSON`,
  );
}
