/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The type of the owner.
 */
export const CommonV3RBACOwnerType = {
  Team: "team",
} as const;
/**
 * The type of the owner.
 */
export type CommonV3RBACOwnerType = ClosedEnum<typeof CommonV3RBACOwnerType>;

/**
 * Represents the RBAC owner of an entity.
 */
export type CommonV3RBACOwner = {
  /**
   * The ID of the owner.
   */
  id: string;
  /**
   * The type of the owner.
   */
  type: CommonV3RBACOwnerType;
};

/** @internal */
export const CommonV3RBACOwnerType$inboundSchema: z.ZodNativeEnum<
  typeof CommonV3RBACOwnerType
> = z.nativeEnum(CommonV3RBACOwnerType);

/** @internal */
export const CommonV3RBACOwner$inboundSchema: z.ZodType<
  CommonV3RBACOwner,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: CommonV3RBACOwnerType$inboundSchema,
});

export function commonV3RBACOwnerFromJSON(
  jsonString: string,
): SafeParseResult<CommonV3RBACOwner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommonV3RBACOwner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommonV3RBACOwner' from JSON`,
  );
}
