/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3AuditLogsActor,
  V3AuditLogsActor$inboundSchema,
} from "./v3auditlogsactor.js";
import {
  V3AuditLogsFilters,
  V3AuditLogsFilters$inboundSchema,
} from "./v3auditlogsfilters.js";

/**
 * Response model for audit logs export history
 */
export type V3AuditLogsAuditLogsExportHistoryResponse = {
  id: string;
  name: string;
  description: string;
  exportedAt: string;
  /**
   * Represents an actor (user) in audit logs
   */
  requestedBy: V3AuditLogsActor;
  downloadLink: string;
  status: string;
  /**
   * Represents filters used in audit log queries
   */
  filters: V3AuditLogsFilters;
};

/** @internal */
export const V3AuditLogsAuditLogsExportHistoryResponse$inboundSchema: z.ZodType<
  V3AuditLogsAuditLogsExportHistoryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  exportedAt: z.string(),
  requestedBy: V3AuditLogsActor$inboundSchema,
  downloadLink: z.string(),
  status: z.string(),
  filters: V3AuditLogsFilters$inboundSchema,
});

export function v3AuditLogsAuditLogsExportHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3AuditLogsAuditLogsExportHistoryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3AuditLogsAuditLogsExportHistoryResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3AuditLogsAuditLogsExportHistoryResponse' from JSON`,
  );
}
