/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3AuditLogsAuditLogResponse,
  V3AuditLogsAuditLogResponse$inboundSchema,
} from "./v3auditlogsauditlogresponse.js";

export type V3AuditLogsListAuditLogsResponseMetadata = {
  totalCount: number;
};

/**
 * Response model for listing audit logs
 */
export type V3AuditLogsListAuditLogsResponse = {
  data: Array<V3AuditLogsAuditLogResponse>;
  metadata: V3AuditLogsListAuditLogsResponseMetadata;
};

/** @internal */
export const V3AuditLogsListAuditLogsResponseMetadata$inboundSchema: z.ZodType<
  V3AuditLogsListAuditLogsResponseMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  totalCount: z.number().int(),
});

export function v3AuditLogsListAuditLogsResponseMetadataFromJSON(
  jsonString: string,
): SafeParseResult<
  V3AuditLogsListAuditLogsResponseMetadata,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3AuditLogsListAuditLogsResponseMetadata$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3AuditLogsListAuditLogsResponseMetadata' from JSON`,
  );
}

/** @internal */
export const V3AuditLogsListAuditLogsResponse$inboundSchema: z.ZodType<
  V3AuditLogsListAuditLogsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(V3AuditLogsAuditLogResponse$inboundSchema),
  metadata: z.lazy(() =>
    V3AuditLogsListAuditLogsResponseMetadata$inboundSchema
  ),
});

export function v3AuditLogsListAuditLogsResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3AuditLogsListAuditLogsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3AuditLogsListAuditLogsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3AuditLogsListAuditLogsResponse' from JSON`,
  );
}
