/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a team in audit logs
 */
export type V3AuditLogsTeam = {
  id: string;
  name: string;
  isDeleted: boolean;
};

/** @internal */
export const V3AuditLogsTeam$inboundSchema: z.ZodType<
  V3AuditLogsTeam,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  isDeleted: z.boolean(),
});

export function v3AuditLogsTeamFromJSON(
  jsonString: string,
): SafeParseResult<V3AuditLogsTeam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3AuditLogsTeam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3AuditLogsTeam' from JSON`,
  );
}
