/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  CommonV3EntityOwner,
  CommonV3EntityOwner$Outbound,
  CommonV3EntityOwner$outboundSchema,
} from "./commonv3entityowner.js";
import {
  V3EscalationPoliciesEscalationPolicyRule,
  V3EscalationPoliciesEscalationPolicyRule$Outbound,
  V3EscalationPoliciesEscalationPolicyRule$outboundSchema,
} from "./v3escalationpoliciesescalationpolicyrule.js";
import {
  V3EscalationPoliciesIncidentReminderRule,
  V3EscalationPoliciesIncidentReminderRule$Outbound,
  V3EscalationPoliciesIncidentReminderRule$outboundSchema,
} from "./v3escalationpoliciesincidentreminderrule.js";

export type V3EscalationPoliciesCreateEscalationPolicyRequest = {
  /**
   * The ID of the team that owns this escalation policy.
   */
  ownerId: string;
  /**
   * The name of the escalation policy.
   */
  name: string;
  /**
   * A description of the escalation policy.
   */
  description: string;
  /**
   * The number of times the entire policy should be repeated.
   */
  repetition: number;
  /**
   * The time in minutes after which the policy should be repeated.
   */
  repeatAfter: number;
  /**
   * The rules that define the escalation steps.
   */
  rules: Array<V3EscalationPoliciesEscalationPolicyRule>;
  /**
   * Enable or disable incident reminders.
   */
  enableIncidentReminders: boolean;
  /**
   * The rules for incident reminders.
   */
  incidentReminderRules: Array<V3EscalationPoliciesIncidentReminderRule>;
  /**
   * Enable or disable automatic incident re-triggering.
   */
  enableIncidentRetrigger: boolean;
  /**
   * The time in hours after which an incident should be re-triggered.
   */
  retriggerAfter: number;
  /**
   * The owner of the entity.
   */
  entityOwner?: CommonV3EntityOwner | undefined;
};

/** @internal */
export type V3EscalationPoliciesCreateEscalationPolicyRequest$Outbound = {
  owner_id: string;
  name: string;
  description: string;
  repetition: number;
  repeat_after: number;
  rules: Array<V3EscalationPoliciesEscalationPolicyRule$Outbound>;
  enable_incident_reminders: boolean;
  incident_reminder_rules: Array<
    V3EscalationPoliciesIncidentReminderRule$Outbound
  >;
  enable_incident_retrigger: boolean;
  retrigger_after: number;
  entity_owner?: CommonV3EntityOwner$Outbound | undefined;
};

/** @internal */
export const V3EscalationPoliciesCreateEscalationPolicyRequest$outboundSchema:
  z.ZodType<
    V3EscalationPoliciesCreateEscalationPolicyRequest$Outbound,
    z.ZodTypeDef,
    V3EscalationPoliciesCreateEscalationPolicyRequest
  > = z.object({
    ownerId: z.string(),
    name: z.string(),
    description: z.string(),
    repetition: z.number().int(),
    repeatAfter: z.number().int(),
    rules: z.array(V3EscalationPoliciesEscalationPolicyRule$outboundSchema),
    enableIncidentReminders: z.boolean(),
    incidentReminderRules: z.array(
      V3EscalationPoliciesIncidentReminderRule$outboundSchema,
    ),
    enableIncidentRetrigger: z.boolean(),
    retriggerAfter: z.number().int(),
    entityOwner: CommonV3EntityOwner$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      ownerId: "owner_id",
      repeatAfter: "repeat_after",
      enableIncidentReminders: "enable_incident_reminders",
      incidentReminderRules: "incident_reminder_rules",
      enableIncidentRetrigger: "enable_incident_retrigger",
      retriggerAfter: "retrigger_after",
      entityOwner: "entity_owner",
    });
  });

export function v3EscalationPoliciesCreateEscalationPolicyRequestToJSON(
  v3EscalationPoliciesCreateEscalationPolicyRequest:
    V3EscalationPoliciesCreateEscalationPolicyRequest,
): string {
  return JSON.stringify(
    V3EscalationPoliciesCreateEscalationPolicyRequest$outboundSchema.parse(
      v3EscalationPoliciesCreateEscalationPolicyRequest,
    ),
  );
}
