/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3ExtensionsMSTeamsChannelConfiguration,
  V3ExtensionsMSTeamsChannelConfiguration$inboundSchema,
  V3ExtensionsMSTeamsChannelConfiguration$Outbound,
  V3ExtensionsMSTeamsChannelConfiguration$outboundSchema,
} from "./v3extensionsmsteamschannelconfiguration.js";

/**
 * Represents a connected MS Team and its channel configurations.
 */
export type V3ExtensionsMSTeamsConnectedTeams = {
  /**
   * The MongoDB ObjectID for this connected team entry.
   */
  id?: string | undefined;
  /**
   * The unique identifier for the team in MS Teams.
   */
  teamId: string;
  /**
   * The display name of the team in MS Teams.
   */
  teamName: string;
  /**
   * A list of channel routing configurations for this team.
   */
  channelConfigurations: Array<V3ExtensionsMSTeamsChannelConfiguration>;
};

/** @internal */
export const V3ExtensionsMSTeamsConnectedTeams$inboundSchema: z.ZodType<
  V3ExtensionsMSTeamsConnectedTeams,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  team_id: z.string(),
  team_name: z.string(),
  channel_configurations: z.array(
    V3ExtensionsMSTeamsChannelConfiguration$inboundSchema,
  ),
}).transform((v) => {
  return remap$(v, {
    "team_id": "teamId",
    "team_name": "teamName",
    "channel_configurations": "channelConfigurations",
  });
});
/** @internal */
export type V3ExtensionsMSTeamsConnectedTeams$Outbound = {
  id?: string | undefined;
  team_id: string;
  team_name: string;
  channel_configurations: Array<
    V3ExtensionsMSTeamsChannelConfiguration$Outbound
  >;
};

/** @internal */
export const V3ExtensionsMSTeamsConnectedTeams$outboundSchema: z.ZodType<
  V3ExtensionsMSTeamsConnectedTeams$Outbound,
  z.ZodTypeDef,
  V3ExtensionsMSTeamsConnectedTeams
> = z.object({
  id: z.string().optional(),
  teamId: z.string(),
  teamName: z.string(),
  channelConfigurations: z.array(
    V3ExtensionsMSTeamsChannelConfiguration$outboundSchema,
  ),
}).transform((v) => {
  return remap$(v, {
    teamId: "team_id",
    teamName: "team_name",
    channelConfigurations: "channel_configurations",
  });
});

export function v3ExtensionsMSTeamsConnectedTeamsToJSON(
  v3ExtensionsMSTeamsConnectedTeams: V3ExtensionsMSTeamsConnectedTeams,
): string {
  return JSON.stringify(
    V3ExtensionsMSTeamsConnectedTeams$outboundSchema.parse(
      v3ExtensionsMSTeamsConnectedTeams,
    ),
  );
}
export function v3ExtensionsMSTeamsConnectedTeamsFromJSON(
  jsonString: string,
): SafeParseResult<V3ExtensionsMSTeamsConnectedTeams, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ExtensionsMSTeamsConnectedTeams$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ExtensionsMSTeamsConnectedTeams' from JSON`,
  );
}
