/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  V3ExtensionsMSTeamsConnectedTeams,
  V3ExtensionsMSTeamsConnectedTeams$Outbound,
  V3ExtensionsMSTeamsConnectedTeams$outboundSchema,
} from "./v3extensionsmsteamsconnectedteams.js";
import {
  V3ExtensionsMSTeamsIncidentActionAlertState,
  V3ExtensionsMSTeamsIncidentActionAlertState$Outbound,
  V3ExtensionsMSTeamsIncidentActionAlertState$outboundSchema,
} from "./v3extensionsmsteamsincidentactionalertstate.js";
import {
  V3ExtensionsMSTeamsTriggers,
  V3ExtensionsMSTeamsTriggers$Outbound,
  V3ExtensionsMSTeamsTriggers$outboundSchema,
} from "./v3extensionsmsteamstriggers.js";

/**
 * The request body for creating or updating an MS Teams extension configuration.
 */
export type V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest = {
  /**
   * A user-friendly way to configure which incident action alerts are active. This is translated by the backend into the 'triggers.custom' array.
   */
  customIncidentAlertState?:
    | V3ExtensionsMSTeamsIncidentActionAlertState
    | undefined;
  /**
   * The MongoDB ObjectID of the extension document. Should be included for updates.
   */
  id?: string | undefined;
  /**
   * The MongoDB ObjectID of the organization this extension belongs to.
   */
  organizationId?: string | undefined;
  /**
   * The display name for the default conversation/channel.
   */
  defaultConversationName: string;
  /**
   * The unique identifier for the default MS Teams conversation/channel.
   */
  defaultConversationId: string;
  /**
   * A master switch to enable or disable the entire integration.
   */
  isActive: boolean;
  /**
   * Determines if notifications should be sent to the default channel.
   */
  isDefaultActive: boolean;
  /**
   * Determines if notifications should be sent to custom-configured channels.
   */
  isCustomChannelsActive: boolean;
  /**
   * Configuration for which alerts are sent to the MS Teams channel.
   */
  triggers: V3ExtensionsMSTeamsTriggers;
  /**
   * The Azure AD Tenant ID of the organization that owns this extension.
   */
  tenantId: string;
  /**
   * The Azure AD Object ID of the user who created this extension.
   */
  fromId: string;
  /**
   * A list of all MS Teams (teams) connected to this organization.
   */
  connectedTeams: Array<V3ExtensionsMSTeamsConnectedTeams>;
};

/** @internal */
export type V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest$Outbound = {
  custom_incident_alert_state?:
    | V3ExtensionsMSTeamsIncidentActionAlertState$Outbound
    | undefined;
  id?: string | undefined;
  organization_id?: string | undefined;
  default_conversation_name: string;
  default_conversation_id: string;
  is_active: boolean;
  is_default_active: boolean;
  is_custom_channels_active: boolean;
  triggers: V3ExtensionsMSTeamsTriggers$Outbound;
  tenant_id: string;
  from_id: string;
  connected_teams: Array<V3ExtensionsMSTeamsConnectedTeams$Outbound>;
};

/** @internal */
export const V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest$outboundSchema:
  z.ZodType<
    V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest$Outbound,
    z.ZodTypeDef,
    V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest
  > = z.object({
    customIncidentAlertState:
      V3ExtensionsMSTeamsIncidentActionAlertState$outboundSchema.optional(),
    id: z.string().optional(),
    organizationId: z.string().optional(),
    defaultConversationName: z.string(),
    defaultConversationId: z.string(),
    isActive: z.boolean(),
    isDefaultActive: z.boolean(),
    isCustomChannelsActive: z.boolean(),
    triggers: V3ExtensionsMSTeamsTriggers$outboundSchema,
    tenantId: z.string(),
    fromId: z.string(),
    connectedTeams: z.array(V3ExtensionsMSTeamsConnectedTeams$outboundSchema),
  }).transform((v) => {
    return remap$(v, {
      customIncidentAlertState: "custom_incident_alert_state",
      organizationId: "organization_id",
      defaultConversationName: "default_conversation_name",
      defaultConversationId: "default_conversation_id",
      isActive: "is_active",
      isDefaultActive: "is_default_active",
      isCustomChannelsActive: "is_custom_channels_active",
      tenantId: "tenant_id",
      fromId: "from_id",
      connectedTeams: "connected_teams",
    });
  });

export function v3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequestToJSON(
  v3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest:
    V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest,
): string {
  return JSON.stringify(
    V3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest$outboundSchema.parse(
      v3ExtensionsMSTeamsCreateOrUpdateMSTeamsConfigRequest,
    ),
  );
}
