/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ExtensionsWebhooksWebhookTrigger = {
  eventClass: string;
  eventType: string;
};

/** @internal */
export const V3ExtensionsWebhooksWebhookTrigger$inboundSchema: z.ZodType<
  V3ExtensionsWebhooksWebhookTrigger,
  z.ZodTypeDef,
  unknown
> = z.object({
  event_class: z.string(),
  event_type: z.string(),
}).transform((v) => {
  return remap$(v, {
    "event_class": "eventClass",
    "event_type": "eventType",
  });
});
/** @internal */
export type V3ExtensionsWebhooksWebhookTrigger$Outbound = {
  event_class: string;
  event_type: string;
};

/** @internal */
export const V3ExtensionsWebhooksWebhookTrigger$outboundSchema: z.ZodType<
  V3ExtensionsWebhooksWebhookTrigger$Outbound,
  z.ZodTypeDef,
  V3ExtensionsWebhooksWebhookTrigger
> = z.object({
  eventClass: z.string(),
  eventType: z.string(),
}).transform((v) => {
  return remap$(v, {
    eventClass: "event_class",
    eventType: "event_type",
  });
});

export function v3ExtensionsWebhooksWebhookTriggerToJSON(
  v3ExtensionsWebhooksWebhookTrigger: V3ExtensionsWebhooksWebhookTrigger,
): string {
  return JSON.stringify(
    V3ExtensionsWebhooksWebhookTrigger$outboundSchema.parse(
      v3ExtensionsWebhooksWebhookTrigger,
    ),
  );
}
export function v3ExtensionsWebhooksWebhookTriggerFromJSON(
  jsonString: string,
): SafeParseResult<V3ExtensionsWebhooksWebhookTrigger, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3ExtensionsWebhooksWebhookTrigger$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ExtensionsWebhooksWebhookTrigger' from JSON`,
  );
}
