/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3ExtensionsMSTeamsConnectedTeams,
  V3ExtensionsMSTeamsConnectedTeams$inboundSchema,
} from "./v3extensionsmsteamsconnectedteams.js";
import {
  V3ExtensionsMSTeamsIncidentActionAlertState,
  V3ExtensionsMSTeamsIncidentActionAlertState$inboundSchema,
} from "./v3extensionsmsteamsincidentactionalertstate.js";
import {
  V3ExtensionsMSTeamsTriggers,
  V3ExtensionsMSTeamsTriggers$inboundSchema,
} from "./v3extensionsmsteamstriggers.js";

/**
 * The request body for creating or updating an MS Teams extension configuration.
 */
export type V3ExtensionsMSTeamsMSTeamsConfigResponse = {
  /**
   * A user-friendly way to configure which incident action alerts are active. This is translated by the backend into the 'triggers.custom' array.
   */
  customIncidentAlertState?:
    | V3ExtensionsMSTeamsIncidentActionAlertState
    | undefined;
  /**
   * The MongoDB ObjectID of the extension document. Should be included for updates.
   */
  id?: string | undefined;
  /**
   * The MongoDB ObjectID of the organization this extension belongs to.
   */
  organizationId?: string | undefined;
  /**
   * The display name for the default conversation/channel.
   */
  defaultConversationName: string;
  /**
   * The unique identifier for the default MS Teams conversation/channel.
   */
  defaultConversationId: string;
  /**
   * A master switch to enable or disable the entire integration.
   */
  isActive: boolean;
  /**
   * Determines if notifications should be sent to the default channel.
   */
  isDefaultActive: boolean;
  /**
   * Determines if notifications should be sent to custom-configured channels.
   */
  isCustomChannelsActive: boolean;
  /**
   * Configuration for which alerts are sent to the MS Teams channel.
   */
  triggers: V3ExtensionsMSTeamsTriggers;
  /**
   * The Azure AD Tenant ID of the organization that owns this extension.
   */
  tenantId: string;
  /**
   * The Azure AD Object ID of the user who created this extension.
   */
  fromId: string;
  /**
   * A list of all MS Teams (teams) connected to this organization.
   */
  connectedTeams: Array<V3ExtensionsMSTeamsConnectedTeams>;
};

/** @internal */
export const V3ExtensionsMSTeamsMSTeamsConfigResponse$inboundSchema: z.ZodType<
  V3ExtensionsMSTeamsMSTeamsConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  custom_incident_alert_state:
    V3ExtensionsMSTeamsIncidentActionAlertState$inboundSchema.optional(),
  id: z.string().optional(),
  organization_id: z.string().optional(),
  default_conversation_name: z.string(),
  default_conversation_id: z.string(),
  is_active: z.boolean(),
  is_default_active: z.boolean(),
  is_custom_channels_active: z.boolean(),
  triggers: V3ExtensionsMSTeamsTriggers$inboundSchema,
  tenant_id: z.string(),
  from_id: z.string(),
  connected_teams: z.array(V3ExtensionsMSTeamsConnectedTeams$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "custom_incident_alert_state": "customIncidentAlertState",
    "organization_id": "organizationId",
    "default_conversation_name": "defaultConversationName",
    "default_conversation_id": "defaultConversationId",
    "is_active": "isActive",
    "is_default_active": "isDefaultActive",
    "is_custom_channels_active": "isCustomChannelsActive",
    "tenant_id": "tenantId",
    "from_id": "fromId",
    "connected_teams": "connectedTeams",
  });
});

export function v3ExtensionsMSTeamsMSTeamsConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ExtensionsMSTeamsMSTeamsConfigResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ExtensionsMSTeamsMSTeamsConfigResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ExtensionsMSTeamsMSTeamsConfigResponse' from JSON`,
  );
}
