/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A set of booleans to easily configure which incident-related alerts are sent to MS Teams.
 */
export type V3ExtensionsMSTeamsIncidentActionAlertState = {
  isTriggerActive: boolean;
  isRetriggerActive: boolean;
  isAcknowledgeActive: boolean;
  isResolveActive: boolean;
  isReassignActive: boolean;
  isNotesAddedActive: boolean;
  isPostmortemActive: boolean;
  isPriorityUpdatedActive: boolean;
};

/** @internal */
export const V3ExtensionsMSTeamsIncidentActionAlertState$inboundSchema:
  z.ZodType<
    V3ExtensionsMSTeamsIncidentActionAlertState,
    z.ZodTypeDef,
    unknown
  > = z.object({
    is_trigger_active: z.boolean(),
    is_retrigger_active: z.boolean(),
    is_acknowledge_active: z.boolean(),
    is_resolve_active: z.boolean(),
    is_reassign_active: z.boolean(),
    is_notes_added_active: z.boolean(),
    is_postmortem_active: z.boolean(),
    is_priority_updated_active: z.boolean(),
  }).transform((v) => {
    return remap$(v, {
      "is_trigger_active": "isTriggerActive",
      "is_retrigger_active": "isRetriggerActive",
      "is_acknowledge_active": "isAcknowledgeActive",
      "is_resolve_active": "isResolveActive",
      "is_reassign_active": "isReassignActive",
      "is_notes_added_active": "isNotesAddedActive",
      "is_postmortem_active": "isPostmortemActive",
      "is_priority_updated_active": "isPriorityUpdatedActive",
    });
  });
/** @internal */
export type V3ExtensionsMSTeamsIncidentActionAlertState$Outbound = {
  is_trigger_active: boolean;
  is_retrigger_active: boolean;
  is_acknowledge_active: boolean;
  is_resolve_active: boolean;
  is_reassign_active: boolean;
  is_notes_added_active: boolean;
  is_postmortem_active: boolean;
  is_priority_updated_active: boolean;
};

/** @internal */
export const V3ExtensionsMSTeamsIncidentActionAlertState$outboundSchema:
  z.ZodType<
    V3ExtensionsMSTeamsIncidentActionAlertState$Outbound,
    z.ZodTypeDef,
    V3ExtensionsMSTeamsIncidentActionAlertState
  > = z.object({
    isTriggerActive: z.boolean(),
    isRetriggerActive: z.boolean(),
    isAcknowledgeActive: z.boolean(),
    isResolveActive: z.boolean(),
    isReassignActive: z.boolean(),
    isNotesAddedActive: z.boolean(),
    isPostmortemActive: z.boolean(),
    isPriorityUpdatedActive: z.boolean(),
  }).transform((v) => {
    return remap$(v, {
      isTriggerActive: "is_trigger_active",
      isRetriggerActive: "is_retrigger_active",
      isAcknowledgeActive: "is_acknowledge_active",
      isResolveActive: "is_resolve_active",
      isReassignActive: "is_reassign_active",
      isNotesAddedActive: "is_notes_added_active",
      isPostmortemActive: "is_postmortem_active",
      isPriorityUpdatedActive: "is_priority_updated_active",
    });
  });

export function v3ExtensionsMSTeamsIncidentActionAlertStateToJSON(
  v3ExtensionsMSTeamsIncidentActionAlertState:
    V3ExtensionsMSTeamsIncidentActionAlertState,
): string {
  return JSON.stringify(
    V3ExtensionsMSTeamsIncidentActionAlertState$outboundSchema.parse(
      v3ExtensionsMSTeamsIncidentActionAlertState,
    ),
  );
}
export function v3ExtensionsMSTeamsIncidentActionAlertStateFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ExtensionsMSTeamsIncidentActionAlertState,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ExtensionsMSTeamsIncidentActionAlertState$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ExtensionsMSTeamsIncidentActionAlertState' from JSON`,
  );
}
