/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  V3GlobalOncallReminderRulesRule,
  V3GlobalOncallReminderRulesRule$Outbound,
  V3GlobalOncallReminderRulesRule$outboundSchema,
} from "./v3globaloncallreminderrulesrule.js";

export type V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest =
  {
    isEnabled: boolean;
    rules: Array<V3GlobalOncallReminderRulesRule>;
  };

/** @internal */
export type V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$Outbound =
  {
    is_enabled: boolean;
    rules: Array<V3GlobalOncallReminderRulesRule$Outbound>;
  };

/** @internal */
export const V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$outboundSchema:
  z.ZodType<
    V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$Outbound,
    z.ZodTypeDef,
    V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest
  > = z.object({
    isEnabled: z.boolean(),
    rules: z.array(V3GlobalOncallReminderRulesRule$outboundSchema),
  }).transform((v) => {
    return remap$(v, {
      isEnabled: "is_enabled",
    });
  });

export function v3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequestToJSON(
  v3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest:
    V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest,
): string {
  return JSON.stringify(
    V3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest$outboundSchema
      .parse(v3GlobalOncallReminderRulesUpdateGlobalOncallReminderRulesRequest),
  );
}
