/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type V3GlobalEventRulesRuleActionUpdate = {
  /**
   * The service ID to which the alert should be routed.
   */
  routeTo?: string | undefined;
};

/** @internal */
export type V3GlobalEventRulesRuleActionUpdate$Outbound = {
  route_to?: string | undefined;
};

/** @internal */
export const V3GlobalEventRulesRuleActionUpdate$outboundSchema: z.ZodType<
  V3GlobalEventRulesRuleActionUpdate$Outbound,
  z.ZodTypeDef,
  V3GlobalEventRulesRuleActionUpdate
> = z.object({
  routeTo: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    routeTo: "route_to",
  });
});

export function v3GlobalEventRulesRuleActionUpdateToJSON(
  v3GlobalEventRulesRuleActionUpdate: V3GlobalEventRulesRuleActionUpdate,
): string {
  return JSON.stringify(
    V3GlobalEventRulesRuleActionUpdate$outboundSchema.parse(
      v3GlobalEventRulesRuleActionUpdate,
    ),
  );
}
