/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3GlobalEventRulesEntityOwnerType = {
  Team: "team",
  User: "user",
  Squad: "squad",
} as const;
export type V3GlobalEventRulesEntityOwnerType = ClosedEnum<
  typeof V3GlobalEventRulesEntityOwnerType
>;

export type V3GlobalEventRulesEntityOwner = {
  id: string;
  type: V3GlobalEventRulesEntityOwnerType;
};

/** @internal */
export const V3GlobalEventRulesEntityOwnerType$inboundSchema: z.ZodNativeEnum<
  typeof V3GlobalEventRulesEntityOwnerType
> = z.nativeEnum(V3GlobalEventRulesEntityOwnerType);
/** @internal */
export const V3GlobalEventRulesEntityOwnerType$outboundSchema: z.ZodNativeEnum<
  typeof V3GlobalEventRulesEntityOwnerType
> = V3GlobalEventRulesEntityOwnerType$inboundSchema;

/** @internal */
export const V3GlobalEventRulesEntityOwner$inboundSchema: z.ZodType<
  V3GlobalEventRulesEntityOwner,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: V3GlobalEventRulesEntityOwnerType$inboundSchema,
});
/** @internal */
export type V3GlobalEventRulesEntityOwner$Outbound = {
  id: string;
  type: string;
};

/** @internal */
export const V3GlobalEventRulesEntityOwner$outboundSchema: z.ZodType<
  V3GlobalEventRulesEntityOwner$Outbound,
  z.ZodTypeDef,
  V3GlobalEventRulesEntityOwner
> = z.object({
  id: z.string(),
  type: V3GlobalEventRulesEntityOwnerType$outboundSchema,
});

export function v3GlobalEventRulesEntityOwnerToJSON(
  v3GlobalEventRulesEntityOwner: V3GlobalEventRulesEntityOwner,
): string {
  return JSON.stringify(
    V3GlobalEventRulesEntityOwner$outboundSchema.parse(
      v3GlobalEventRulesEntityOwner,
    ),
  );
}
export function v3GlobalEventRulesEntityOwnerFromJSON(
  jsonString: string,
): SafeParseResult<V3GlobalEventRulesEntityOwner, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3GlobalEventRulesEntityOwner$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3GlobalEventRulesEntityOwner' from JSON`,
  );
}
