/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  V3GlobalEventRulesRuleAction,
  V3GlobalEventRulesRuleAction$Outbound,
  V3GlobalEventRulesRuleAction$outboundSchema,
} from "./v3globaleventrulesruleaction.js";

export type V3GlobalEventRulesCreateOrUpdateRuleRequest = {
  description: string;
  expression: string;
  action: V3GlobalEventRulesRuleAction;
};

/** @internal */
export type V3GlobalEventRulesCreateOrUpdateRuleRequest$Outbound = {
  description: string;
  expression: string;
  action: V3GlobalEventRulesRuleAction$Outbound;
};

/** @internal */
export const V3GlobalEventRulesCreateOrUpdateRuleRequest$outboundSchema:
  z.ZodType<
    V3GlobalEventRulesCreateOrUpdateRuleRequest$Outbound,
    z.ZodTypeDef,
    V3GlobalEventRulesCreateOrUpdateRuleRequest
  > = z.object({
    description: z.string(),
    expression: z.string(),
    action: V3GlobalEventRulesRuleAction$outboundSchema,
  });

export function v3GlobalEventRulesCreateOrUpdateRuleRequestToJSON(
  v3GlobalEventRulesCreateOrUpdateRuleRequest:
    V3GlobalEventRulesCreateOrUpdateRuleRequest,
): string {
  return JSON.stringify(
    V3GlobalEventRulesCreateOrUpdateRuleRequest$outboundSchema.parse(
      v3GlobalEventRulesCreateOrUpdateRuleRequest,
    ),
  );
}
