/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V3IncidentsRunbooksAttachRunbooksRequest = {
  runbooks: Array<string>;
};

/** @internal */
export type V3IncidentsRunbooksAttachRunbooksRequest$Outbound = {
  runbooks: Array<string>;
};

/** @internal */
export const V3IncidentsRunbooksAttachRunbooksRequest$outboundSchema: z.ZodType<
  V3IncidentsRunbooksAttachRunbooksRequest$Outbound,
  z.ZodTypeDef,
  V3IncidentsRunbooksAttachRunbooksRequest
> = z.object({
  runbooks: z.array(z.string()),
});

export function v3IncidentsRunbooksAttachRunbooksRequestToJSON(
  v3IncidentsRunbooksAttachRunbooksRequest:
    V3IncidentsRunbooksAttachRunbooksRequest,
): string {
  return JSON.stringify(
    V3IncidentsRunbooksAttachRunbooksRequest$outboundSchema.parse(
      v3IncidentsRunbooksAttachRunbooksRequest,
    ),
  );
}
