/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Represents the priority of an incident.
 */
export const V3IncidentsIncidentPriority = {
  P1: "P1",
  P2: "P2",
  P3: "P3",
  P4: "P4",
  P5: "P5",
} as const;
/**
 * Represents the priority of an incident.
 */
export type V3IncidentsIncidentPriority = ClosedEnum<
  typeof V3IncidentsIncidentPriority
>;

/** @internal */
export const V3IncidentsIncidentPriority$inboundSchema: z.ZodNativeEnum<
  typeof V3IncidentsIncidentPriority
> = z.nativeEnum(V3IncidentsIncidentPriority);
/** @internal */
export const V3IncidentsIncidentPriority$outboundSchema: z.ZodNativeEnum<
  typeof V3IncidentsIncidentPriority
> = V3IncidentsIncidentPriority$inboundSchema;
