/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V3IncidentsTagsUpdateTagRequestTags = {};

export type V3IncidentsTagsUpdateTagRequest = {
  tags: V3IncidentsTagsUpdateTagRequestTags;
};

/** @internal */
export type V3IncidentsTagsUpdateTagRequestTags$Outbound = {};

/** @internal */
export const V3IncidentsTagsUpdateTagRequestTags$outboundSchema: z.ZodType<
  V3IncidentsTagsUpdateTagRequestTags$Outbound,
  z.ZodTypeDef,
  V3IncidentsTagsUpdateTagRequestTags
> = z.object({});

export function v3IncidentsTagsUpdateTagRequestTagsToJSON(
  v3IncidentsTagsUpdateTagRequestTags: V3IncidentsTagsUpdateTagRequestTags,
): string {
  return JSON.stringify(
    V3IncidentsTagsUpdateTagRequestTags$outboundSchema.parse(
      v3IncidentsTagsUpdateTagRequestTags,
    ),
  );
}

/** @internal */
export type V3IncidentsTagsUpdateTagRequest$Outbound = {
  tags: V3IncidentsTagsUpdateTagRequestTags$Outbound;
};

/** @internal */
export const V3IncidentsTagsUpdateTagRequest$outboundSchema: z.ZodType<
  V3IncidentsTagsUpdateTagRequest$Outbound,
  z.ZodTypeDef,
  V3IncidentsTagsUpdateTagRequest
> = z.object({
  tags: z.lazy(() => V3IncidentsTagsUpdateTagRequestTags$outboundSchema),
});

export function v3IncidentsTagsUpdateTagRequestToJSON(
  v3IncidentsTagsUpdateTagRequest: V3IncidentsTagsUpdateTagRequest,
): string {
  return JSON.stringify(
    V3IncidentsTagsUpdateTagRequest$outboundSchema.parse(
      v3IncidentsTagsUpdateTagRequest,
    ),
  );
}
