/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3IncidentsAdditionalRespondersAdditionalResponder,
  V3IncidentsAdditionalRespondersAdditionalResponder$inboundSchema,
} from "./v3incidentsadditionalrespondersadditionalresponder.js";

export type V3IncidentsAdditionalRespondersAdditionalResponderResponse = {
  additionalResponders: Array<
    V3IncidentsAdditionalRespondersAdditionalResponder
  >;
};

/** @internal */
export const V3IncidentsAdditionalRespondersAdditionalResponderResponse$inboundSchema:
  z.ZodType<
    V3IncidentsAdditionalRespondersAdditionalResponderResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    additional_responders: z.array(
      V3IncidentsAdditionalRespondersAdditionalResponder$inboundSchema,
    ),
  }).transform((v) => {
    return remap$(v, {
      "additional_responders": "additionalResponders",
    });
  });

export function v3IncidentsAdditionalRespondersAdditionalResponderResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsAdditionalRespondersAdditionalResponderResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsAdditionalRespondersAdditionalResponderResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsAdditionalRespondersAdditionalResponderResponse' from JSON`,
  );
}
