/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a communication card.
 */
export type V3IncidentsCommunicationCardsCommunicationCardResponse = {
  createdAt: string;
  updatedAt: string;
  deletedAt?: any | undefined;
  id: number;
  incidentId: string;
  url: string;
  type: string;
  title: string;
  channelId: string;
  archivedAt?: any | undefined;
};

/** @internal */
export const V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema:
  z.ZodType<
    V3IncidentsCommunicationCardsCommunicationCardResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    created_at: z.string(),
    updated_at: z.string(),
    deleted_at: z.any().optional(),
    id: z.number().int(),
    incident_id: z.string(),
    url: z.string(),
    type: z.string(),
    title: z.string(),
    channel_id: z.string(),
    archived_at: z.any().optional(),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "deleted_at": "deletedAt",
      "incident_id": "incidentId",
      "channel_id": "channelId",
      "archived_at": "archivedAt",
    });
  });

export function v3IncidentsCommunicationCardsCommunicationCardResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsCommunicationCardsCommunicationCardResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsCommunicationCardsCommunicationCardResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsCommunicationCardsCommunicationCardResponse' from JSON`,
  );
}
