/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a single follow-up task in a postmortem.
 */
export type V3IncidentsPostmortemsPostmortemFollowUp = {
  task: string;
  isDone: boolean;
};

/** @internal */
export const V3IncidentsPostmortemsPostmortemFollowUp$inboundSchema: z.ZodType<
  V3IncidentsPostmortemsPostmortemFollowUp,
  z.ZodTypeDef,
  unknown
> = z.object({
  task: z.string(),
  is_done: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "is_done": "isDone",
  });
});
/** @internal */
export type V3IncidentsPostmortemsPostmortemFollowUp$Outbound = {
  task: string;
  is_done: boolean;
};

/** @internal */
export const V3IncidentsPostmortemsPostmortemFollowUp$outboundSchema: z.ZodType<
  V3IncidentsPostmortemsPostmortemFollowUp$Outbound,
  z.ZodTypeDef,
  V3IncidentsPostmortemsPostmortemFollowUp
> = z.object({
  task: z.string(),
  isDone: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    isDone: "is_done",
  });
});

export function v3IncidentsPostmortemsPostmortemFollowUpToJSON(
  v3IncidentsPostmortemsPostmortemFollowUp:
    V3IncidentsPostmortemsPostmortemFollowUp,
): string {
  return JSON.stringify(
    V3IncidentsPostmortemsPostmortemFollowUp$outboundSchema.parse(
      v3IncidentsPostmortemsPostmortemFollowUp,
    ),
  );
}
export function v3IncidentsPostmortemsPostmortemFollowUpFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsPostmortemsPostmortemFollowUp,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsPostmortemsPostmortemFollowUp$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3IncidentsPostmortemsPostmortemFollowUp' from JSON`,
  );
}
