/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Request body for creating a new note.
 */
export type V3IncidentsNotesCreateNoteRequest = {
  message: string;
  attachments: Array<string>;
};

/** @internal */
export type V3IncidentsNotesCreateNoteRequest$Outbound = {
  message: string;
  attachments: Array<string>;
};

/** @internal */
export const V3IncidentsNotesCreateNoteRequest$outboundSchema: z.ZodType<
  V3IncidentsNotesCreateNoteRequest$Outbound,
  z.ZodTypeDef,
  V3IncidentsNotesCreateNoteRequest
> = z.object({
  message: z.string(),
  attachments: z.array(z.string()),
});

export function v3IncidentsNotesCreateNoteRequestToJSON(
  v3IncidentsNotesCreateNoteRequest: V3IncidentsNotesCreateNoteRequest,
): string {
  return JSON.stringify(
    V3IncidentsNotesCreateNoteRequest$outboundSchema.parse(
      v3IncidentsNotesCreateNoteRequest,
    ),
  );
}
