/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a webhook trigger with event class and type.
 */
export type V3IncidentsIncidentActionsEventWebhookTrigger = {
  eventClass: string;
  eventType: string;
};

/** @internal */
export const V3IncidentsIncidentActionsEventWebhookTrigger$inboundSchema:
  z.ZodType<
    V3IncidentsIncidentActionsEventWebhookTrigger,
    z.ZodTypeDef,
    unknown
  > = z.object({
    event_class: z.string(),
    event_type: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "event_class": "eventClass",
      "event_type": "eventType",
    });
  });

export function v3IncidentsIncidentActionsEventWebhookTriggerFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsIncidentActionsEventWebhookTrigger,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsIncidentActionsEventWebhookTrigger$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3IncidentsIncidentActionsEventWebhookTrigger' from JSON`,
  );
}
