/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const V3IncidentsIncidentExportRequestSloAffecting = {
  Yes: "yes",
  No: "no",
  Unknown: "",
} as const;
export type V3IncidentsIncidentExportRequestSloAffecting = ClosedEnum<
  typeof V3IncidentsIncidentExportRequestSloAffecting
>;

/** @internal */
export const V3IncidentsIncidentExportRequestSloAffecting$outboundSchema:
  z.ZodNativeEnum<typeof V3IncidentsIncidentExportRequestSloAffecting> = z
    .nativeEnum(V3IncidentsIncidentExportRequestSloAffecting);
