/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents the total count of postmortems.
 */
export type V3IncidentsPostmortemsTotalPostmortemCount = {
  count: number;
};

/** @internal */
export const V3IncidentsPostmortemsTotalPostmortemCount$inboundSchema:
  z.ZodType<V3IncidentsPostmortemsTotalPostmortemCount, z.ZodTypeDef, unknown> =
    z.object({
      count: z.number().int(),
    });

export function v3IncidentsPostmortemsTotalPostmortemCountFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsPostmortemsTotalPostmortemCount,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsPostmortemsTotalPostmortemCount$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3IncidentsPostmortemsTotalPostmortemCount' from JSON`,
  );
}
