/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  V3IncidentsAssignee,
  V3IncidentsAssignee$Outbound,
  V3IncidentsAssignee$outboundSchema,
} from "./v3incidentsassignee.js";

/**
 * Request body for reassigning an incident.
 */
export type V3IncidentsReassignIncidentRequest = {
  /**
   * Assignment target for an incident.
   */
  reassignTo: V3IncidentsAssignee;
};

/** @internal */
export type V3IncidentsReassignIncidentRequest$Outbound = {
  reassignTo: V3IncidentsAssignee$Outbound;
};

/** @internal */
export const V3IncidentsReassignIncidentRequest$outboundSchema: z.ZodType<
  V3IncidentsReassignIncidentRequest$Outbound,
  z.ZodTypeDef,
  V3IncidentsReassignIncidentRequest
> = z.object({
  reassignTo: V3IncidentsAssignee$outboundSchema,
});

export function v3IncidentsReassignIncidentRequestToJSON(
  v3IncidentsReassignIncidentRequest: V3IncidentsReassignIncidentRequest,
): string {
  return JSON.stringify(
    V3IncidentsReassignIncidentRequest$outboundSchema.parse(
      v3IncidentsReassignIncidentRequest,
    ),
  );
}
