/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3IncidentsSnoozeNotificationsReassignTo,
  V3IncidentsSnoozeNotificationsReassignTo$inboundSchema,
} from "./v3incidentssnoozenotificationsreassignto.js";

export type V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse = {
  incidentId: string;
  isSnoozed: boolean;
  reassignTo: V3IncidentsSnoozeNotificationsReassignTo;
};

/** @internal */
export const V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse$inboundSchema:
  z.ZodType<
    V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    incident_id: z.string(),
    is_snoozed: z.boolean(),
    reassign_to: V3IncidentsSnoozeNotificationsReassignTo$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "incident_id": "incidentId",
      "is_snoozed": "isSnoozed",
      "reassign_to": "reassignTo",
    });
  });

export function v3IncidentsSnoozeNotificationsUnsnoozeIncidentResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsSnoozeNotificationsUnsnoozeIncidentResponse' from JSON`,
  );
}
