/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  V3IncidentsIncidentPriority,
  V3IncidentsIncidentPriority$outboundSchema,
} from "./v3incidentsincidentpriority.js";
import {
  V3IncidentsServiceOwnerFilter,
  V3IncidentsServiceOwnerFilter$Outbound,
  V3IncidentsServiceOwnerFilter$outboundSchema,
} from "./v3incidentsserviceownerfilter.js";

/**
 * Filter criteria for incidents in an export.
 */
export type V3IncidentsExportIncidentsFilter = {
  services: Array<string>;
  sources: Array<string>;
  /**
   * Filter criteria for service owner in an export.
   */
  serviceOwner: V3IncidentsServiceOwnerFilter;
  assignedTo: Array<string>;
  assignedToUserIDsAndTheirSquads: Array<string>;
  statuses: Array<string>;
  priority: Array<V3IncidentsIncidentPriority>;
  tags: Array<string>;
  notes: string;
};

/** @internal */
export type V3IncidentsExportIncidentsFilter$Outbound = {
  services: Array<string>;
  sources: Array<string>;
  serviceOwner: V3IncidentsServiceOwnerFilter$Outbound;
  assigned_to: Array<string>;
  assignedToUserIDsAndTheirSquads: Array<string>;
  statuses: Array<string>;
  priority: Array<string>;
  tags: Array<string>;
  notes: string;
};

/** @internal */
export const V3IncidentsExportIncidentsFilter$outboundSchema: z.ZodType<
  V3IncidentsExportIncidentsFilter$Outbound,
  z.ZodTypeDef,
  V3IncidentsExportIncidentsFilter
> = z.object({
  services: z.array(z.string()),
  sources: z.array(z.string()),
  serviceOwner: V3IncidentsServiceOwnerFilter$outboundSchema,
  assignedTo: z.array(z.string()),
  assignedToUserIDsAndTheirSquads: z.array(z.string()),
  statuses: z.array(z.string()),
  priority: z.array(V3IncidentsIncidentPriority$outboundSchema),
  tags: z.array(z.string()),
  notes: z.string(),
}).transform((v) => {
  return remap$(v, {
    assignedTo: "assigned_to",
  });
});

export function v3IncidentsExportIncidentsFilterToJSON(
  v3IncidentsExportIncidentsFilter: V3IncidentsExportIncidentsFilter,
): string {
  return JSON.stringify(
    V3IncidentsExportIncidentsFilter$outboundSchema.parse(
      v3IncidentsExportIncidentsFilter,
    ),
  );
}
