/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3IncidentsIncidentPriorityUpdateResponse = {
  incidentId: string;
  priority: string;
};

/** @internal */
export const V3IncidentsIncidentPriorityUpdateResponse$inboundSchema: z.ZodType<
  V3IncidentsIncidentPriorityUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  incident_id: z.string(),
  priority: z.string(),
}).transform((v) => {
  return remap$(v, {
    "incident_id": "incidentId",
  });
});

export function v3IncidentsIncidentPriorityUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsIncidentPriorityUpdateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsIncidentPriorityUpdateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3IncidentsIncidentPriorityUpdateResponse' from JSON`,
  );
}
