/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Request body for unmerging a child incident from its parent.
 */
export type V3IncidentsUnmergeIncidentRequest = {
  sendNotification: boolean;
  assignMe: boolean;
};

/** @internal */
export type V3IncidentsUnmergeIncidentRequest$Outbound = {
  send_notification: boolean;
  assign_me: boolean;
};

/** @internal */
export const V3IncidentsUnmergeIncidentRequest$outboundSchema: z.ZodType<
  V3IncidentsUnmergeIncidentRequest$Outbound,
  z.ZodTypeDef,
  V3IncidentsUnmergeIncidentRequest
> = z.object({
  sendNotification: z.boolean(),
  assignMe: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    sendNotification: "send_notification",
    assignMe: "assign_me",
  });
});

export function v3IncidentsUnmergeIncidentRequestToJSON(
  v3IncidentsUnmergeIncidentRequest: V3IncidentsUnmergeIncidentRequest,
): string {
  return JSON.stringify(
    V3IncidentsUnmergeIncidentRequest$outboundSchema.parse(
      v3IncidentsUnmergeIncidentRequest,
    ),
  );
}
