/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Request body for bulk updating incident priority.
 */
export type V3IncidentsBulkIncidentsPriorityUpdateRequest = {
  incidentIds: Array<string>;
  priority: string;
};

/** @internal */
export type V3IncidentsBulkIncidentsPriorityUpdateRequest$Outbound = {
  incident_ids: Array<string>;
  priority: string;
};

/** @internal */
export const V3IncidentsBulkIncidentsPriorityUpdateRequest$outboundSchema:
  z.ZodType<
    V3IncidentsBulkIncidentsPriorityUpdateRequest$Outbound,
    z.ZodTypeDef,
    V3IncidentsBulkIncidentsPriorityUpdateRequest
  > = z.object({
    incidentIds: z.array(z.string()),
    priority: z.string(),
  }).transform((v) => {
    return remap$(v, {
      incidentIds: "incident_ids",
    });
  });

export function v3IncidentsBulkIncidentsPriorityUpdateRequestToJSON(
  v3IncidentsBulkIncidentsPriorityUpdateRequest:
    V3IncidentsBulkIncidentsPriorityUpdateRequest,
): string {
  return JSON.stringify(
    V3IncidentsBulkIncidentsPriorityUpdateRequest$outboundSchema.parse(
      v3IncidentsBulkIncidentsPriorityUpdateRequest,
    ),
  );
}
