/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Represents an attachment in a postmortem request.
 */
export type V3IncidentsPostmortemsPostmortemAttachmentRequest = {
  key?: string | undefined;
  mimeType?: string | undefined;
  fileSize?: string | undefined;
};

/** @internal */
export type V3IncidentsPostmortemsPostmortemAttachmentRequest$Outbound = {
  key?: string | undefined;
  mime_type?: string | undefined;
  file_size?: string | undefined;
};

/** @internal */
export const V3IncidentsPostmortemsPostmortemAttachmentRequest$outboundSchema:
  z.ZodType<
    V3IncidentsPostmortemsPostmortemAttachmentRequest$Outbound,
    z.ZodTypeDef,
    V3IncidentsPostmortemsPostmortemAttachmentRequest
  > = z.object({
    key: z.string().optional(),
    mimeType: z.string().optional(),
    fileSize: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      mimeType: "mime_type",
      fileSize: "file_size",
    });
  });

export function v3IncidentsPostmortemsPostmortemAttachmentRequestToJSON(
  v3IncidentsPostmortemsPostmortemAttachmentRequest:
    V3IncidentsPostmortemsPostmortemAttachmentRequest,
): string {
  return JSON.stringify(
    V3IncidentsPostmortemsPostmortemAttachmentRequest$outboundSchema.parse(
      v3IncidentsPostmortemsPostmortemAttachmentRequest,
    ),
  );
}
