/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Reference to a merged incident entity.
 */
export type V3IncidentsTagsMergeIncidentEntityReference = {
  id: string;
};

/** @internal */
export const V3IncidentsTagsMergeIncidentEntityReference$inboundSchema:
  z.ZodType<
    V3IncidentsTagsMergeIncidentEntityReference,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
  });

export function v3IncidentsTagsMergeIncidentEntityReferenceFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsTagsMergeIncidentEntityReference,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsTagsMergeIncidentEntityReference$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3IncidentsTagsMergeIncidentEntityReference' from JSON`,
  );
}
