/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents the assignment target for delayed notifications.
 */
export type V3IncidentsAssignTo = {
  id: string;
  type?: string | undefined;
};

/** @internal */
export const V3IncidentsAssignTo$inboundSchema: z.ZodType<
  V3IncidentsAssignTo,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string().optional(),
});

export function v3IncidentsAssignToFromJSON(
  jsonString: string,
): SafeParseResult<V3IncidentsAssignTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3IncidentsAssignTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsAssignTo' from JSON`,
  );
}
