/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

/**
 * Represents the status of a postmortem.
 */
export const V3IncidentsPostmortemsPostmortemStatus = {
  InProgress: "in_progress",
  UnderReview: "under_review",
  Published: "published",
} as const;
/**
 * Represents the status of a postmortem.
 */
export type V3IncidentsPostmortemsPostmortemStatus = ClosedEnum<
  typeof V3IncidentsPostmortemsPostmortemStatus
>;

/** @internal */
export const V3IncidentsPostmortemsPostmortemStatus$inboundSchema:
  z.ZodNativeEnum<typeof V3IncidentsPostmortemsPostmortemStatus> = z.nativeEnum(
    V3IncidentsPostmortemsPostmortemStatus,
  );
/** @internal */
export const V3IncidentsPostmortemsPostmortemStatus$outboundSchema:
  z.ZodNativeEnum<typeof V3IncidentsPostmortemsPostmortemStatus> =
    V3IncidentsPostmortemsPostmortemStatus$inboundSchema;
