/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3IncidentsSnoozeNotificationsSnoozeIncidentResponse = {
  incidentId: string;
  isSnoozed: boolean;
  snoozeEndTime: string;
};

/** @internal */
export const V3IncidentsSnoozeNotificationsSnoozeIncidentResponse$inboundSchema:
  z.ZodType<
    V3IncidentsSnoozeNotificationsSnoozeIncidentResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    incident_id: z.string(),
    is_snoozed: z.boolean(),
    snooze_end_time: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "incident_id": "incidentId",
      "is_snoozed": "isSnoozed",
      "snooze_end_time": "snoozeEndTime",
    });
  });

export function v3IncidentsSnoozeNotificationsSnoozeIncidentResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3IncidentsSnoozeNotificationsSnoozeIncidentResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3IncidentsSnoozeNotificationsSnoozeIncidentResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3IncidentsSnoozeNotificationsSnoozeIncidentResponse' from JSON`,
  );
}
