/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Analytics metrics for TTA (Time to Acknowledge) and TTR (Time to Resolve).
 */
export type V3IncidentsTagsAnalyticsMetrics = {
  time: number;
  userId: string;
  escalationPolicyId: string;
  squadId: string;
};

/** @internal */
export const V3IncidentsTagsAnalyticsMetrics$inboundSchema: z.ZodType<
  V3IncidentsTagsAnalyticsMetrics,
  z.ZodTypeDef,
  unknown
> = z.object({
  time: z.number().int(),
  userId: z.string(),
  escalationPolicyId: z.string(),
  squadId: z.string(),
});

export function v3IncidentsTagsAnalyticsMetricsFromJSON(
  jsonString: string,
): SafeParseResult<V3IncidentsTagsAnalyticsMetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3IncidentsTagsAnalyticsMetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3IncidentsTagsAnalyticsMetrics' from JSON`,
  );
}
