/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Represents a single step in a runbook.
 */
export type V3RunbooksStep = {
  /**
   * The content of the step, in Markdown format.
   */
  content: string;
};

/** @internal */
export const V3RunbooksStep$inboundSchema: z.ZodType<
  V3RunbooksStep,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string(),
});
/** @internal */
export type V3RunbooksStep$Outbound = {
  content: string;
};

/** @internal */
export const V3RunbooksStep$outboundSchema: z.ZodType<
  V3RunbooksStep$Outbound,
  z.ZodTypeDef,
  V3RunbooksStep
> = z.object({
  content: z.string(),
});

export function v3RunbooksStepToJSON(v3RunbooksStep: V3RunbooksStep): string {
  return JSON.stringify(V3RunbooksStep$outboundSchema.parse(v3RunbooksStep));
}
export function v3RunbooksStepFromJSON(
  jsonString: string,
): SafeParseResult<V3RunbooksStep, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3RunbooksStep$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3RunbooksStep' from JSON`,
  );
}
