/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  CommonV3EntityOwner,
  CommonV3EntityOwner$Outbound,
  CommonV3EntityOwner$outboundSchema,
} from "./commonv3entityowner.js";
import {
  V3RunbooksStep,
  V3RunbooksStep$Outbound,
  V3RunbooksStep$outboundSchema,
} from "./v3runbooksstep.js";

/**
 * Represents the request body for updating a runbook.
 */
export type V3RunbooksUpdateRunbookRequest = {
  /**
   * The name of the runbook.
   */
  name: string;
  /**
   * The steps that make up the runbook.
   */
  steps: Array<V3RunbooksStep>;
  /**
   * The owner of the entity.
   */
  entityOwner?: CommonV3EntityOwner | undefined;
};

/** @internal */
export type V3RunbooksUpdateRunbookRequest$Outbound = {
  name: string;
  steps: Array<V3RunbooksStep$Outbound>;
  entity_owner?: CommonV3EntityOwner$Outbound | undefined;
};

/** @internal */
export const V3RunbooksUpdateRunbookRequest$outboundSchema: z.ZodType<
  V3RunbooksUpdateRunbookRequest$Outbound,
  z.ZodTypeDef,
  V3RunbooksUpdateRunbookRequest
> = z.object({
  name: z.string(),
  steps: z.array(V3RunbooksStep$outboundSchema),
  entityOwner: CommonV3EntityOwner$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    entityOwner: "entity_owner",
  });
});

export function v3RunbooksUpdateRunbookRequestToJSON(
  v3RunbooksUpdateRunbookRequest: V3RunbooksUpdateRunbookRequest,
): string {
  return JSON.stringify(
    V3RunbooksUpdateRunbookRequest$outboundSchema.parse(
      v3RunbooksUpdateRunbookRequest,
    ),
  );
}
