/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesOverlayDedupKeyOverlay = {
  template: string;
  duration: number;
};

/** @internal */
export const V3ServicesOverlayDedupKeyOverlay$inboundSchema: z.ZodType<
  V3ServicesOverlayDedupKeyOverlay,
  z.ZodTypeDef,
  unknown
> = z.object({
  template: z.string(),
  duration: z.number().int(),
});

export function v3ServicesOverlayDedupKeyOverlayFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesOverlayDedupKeyOverlay, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesOverlayDedupKeyOverlay$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesOverlayDedupKeyOverlay' from JSON`,
  );
}
