/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesSuppressionRulesCustomRepetition = {
  repeatsCount: number;
  repeats: string;
  repeatsOnWeekdays: Array<number>;
  repeatsOnMonth: string;
};

/** @internal */
export const V3ServicesSuppressionRulesCustomRepetition$inboundSchema:
  z.ZodType<V3ServicesSuppressionRulesCustomRepetition, z.ZodTypeDef, unknown> =
    z.object({
      repeats_count: z.number().int(),
      repeats: z.string(),
      repeats_on_weekdays: z.array(z.number().int()),
      repeats_on_month: z.string(),
    }).transform((v) => {
      return remap$(v, {
        "repeats_count": "repeatsCount",
        "repeats_on_weekdays": "repeatsOnWeekdays",
        "repeats_on_month": "repeatsOnMonth",
      });
    });
/** @internal */
export type V3ServicesSuppressionRulesCustomRepetition$Outbound = {
  repeats_count: number;
  repeats: string;
  repeats_on_weekdays: Array<number>;
  repeats_on_month: string;
};

/** @internal */
export const V3ServicesSuppressionRulesCustomRepetition$outboundSchema:
  z.ZodType<
    V3ServicesSuppressionRulesCustomRepetition$Outbound,
    z.ZodTypeDef,
    V3ServicesSuppressionRulesCustomRepetition
  > = z.object({
    repeatsCount: z.number().int(),
    repeats: z.string(),
    repeatsOnWeekdays: z.array(z.number().int()),
    repeatsOnMonth: z.string(),
  }).transform((v) => {
    return remap$(v, {
      repeatsCount: "repeats_count",
      repeatsOnWeekdays: "repeats_on_weekdays",
      repeatsOnMonth: "repeats_on_month",
    });
  });

export function v3ServicesSuppressionRulesCustomRepetitionToJSON(
  v3ServicesSuppressionRulesCustomRepetition:
    V3ServicesSuppressionRulesCustomRepetition,
): string {
  return JSON.stringify(
    V3ServicesSuppressionRulesCustomRepetition$outboundSchema.parse(
      v3ServicesSuppressionRulesCustomRepetition,
    ),
  );
}
export function v3ServicesSuppressionRulesCustomRepetitionFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesSuppressionRulesCustomRepetition,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesSuppressionRulesCustomRepetition$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesSuppressionRulesCustomRepetition' from JSON`,
  );
}
