/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesOverlayCustomContent = {
  message: string;
  description: string;
};

/** @internal */
export const V3ServicesOverlayCustomContent$inboundSchema: z.ZodType<
  V3ServicesOverlayCustomContent,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  description: z.string(),
});

export function v3ServicesOverlayCustomContentFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesOverlayCustomContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesOverlayCustomContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesOverlayCustomContent' from JSON`,
  );
}
