/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  V3ServicesDeduplicationRulesExpressionBranch,
  V3ServicesDeduplicationRulesExpressionBranch$Outbound,
  V3ServicesDeduplicationRulesExpressionBranch$outboundSchema,
} from "./v3servicesdeduplicationrulesexpressionbranch.js";

export const V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit = {
  Minute: "minute",
  Hour: "hour",
} as const;
export type V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit = ClosedEnum<
  typeof V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit
>;

export type V3ServicesDeduplicationRulesDeduplicationRule = {
  expression: string;
  timeWindow: number;
  timeUnit: V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit;
  isBasic: boolean;
  basicExpression?:
    | Array<V3ServicesDeduplicationRulesExpressionBranch>
    | undefined;
  dependencyDeduplication?: boolean | undefined;
  description?: string | undefined;
};

/** @internal */
export const V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit$outboundSchema:
  z.ZodNativeEnum<
    typeof V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit
  > = z.nativeEnum(V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit);

/** @internal */
export type V3ServicesDeduplicationRulesDeduplicationRule$Outbound = {
  expression: string;
  time_window: number;
  time_unit: string;
  is_basic: boolean;
  basic_expression?:
    | Array<V3ServicesDeduplicationRulesExpressionBranch$Outbound>
    | undefined;
  dependency_deduplication?: boolean | undefined;
  description?: string | undefined;
};

/** @internal */
export const V3ServicesDeduplicationRulesDeduplicationRule$outboundSchema:
  z.ZodType<
    V3ServicesDeduplicationRulesDeduplicationRule$Outbound,
    z.ZodTypeDef,
    V3ServicesDeduplicationRulesDeduplicationRule
  > = z.object({
    expression: z.string(),
    timeWindow: z.number().int(),
    timeUnit:
      V3ServicesDeduplicationRulesDeduplicationRuleTimeUnit$outboundSchema,
    isBasic: z.boolean(),
    basicExpression: z.array(
      V3ServicesDeduplicationRulesExpressionBranch$outboundSchema,
    ).optional(),
    dependencyDeduplication: z.boolean().optional(),
    description: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      timeWindow: "time_window",
      timeUnit: "time_unit",
      isBasic: "is_basic",
      basicExpression: "basic_expression",
      dependencyDeduplication: "dependency_deduplication",
    });
  });

export function v3ServicesDeduplicationRulesDeduplicationRuleToJSON(
  v3ServicesDeduplicationRulesDeduplicationRule:
    V3ServicesDeduplicationRulesDeduplicationRule,
): string {
  return JSON.stringify(
    V3ServicesDeduplicationRulesDeduplicationRule$outboundSchema.parse(
      v3ServicesDeduplicationRulesDeduplicationRule,
    ),
  );
}
