/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CommonV3RBACOwner,
  CommonV3RBACOwner$inboundSchema,
} from "./commonv3rbacowner.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3ServicesAPTAConfig,
  V3ServicesAPTAConfig$inboundSchema,
} from "./v3servicesaptaconfig.js";
import {
  V3ServicesEscalationPolicyBasic,
  V3ServicesEscalationPolicyBasic$inboundSchema,
} from "./v3servicesescalationpolicybasic.js";
import {
  V3ServicesIAGConfig,
  V3ServicesIAGConfig$inboundSchema,
} from "./v3servicesiagconfig.js";
import {
  V3ServicesJiraCloudExtension,
  V3ServicesJiraCloudExtension$inboundSchema,
} from "./v3servicesjiracloudextension.js";
import {
  V3ServicesNotificationDelayConfig,
  V3ServicesNotificationDelayConfig$inboundSchema,
} from "./v3servicesnotificationdelayconfig.js";
import {
  V3ServicesServiceMaintainer,
  V3ServicesServiceMaintainer$inboundSchema,
} from "./v3servicesservicemaintainer.js";
import {
  V3ServicesServiceSlack,
  V3ServicesServiceSlack$inboundSchema,
} from "./v3servicesserviceslack.js";
import {
  V3ServicesServiceTag,
  V3ServicesServiceTag$inboundSchema,
} from "./v3servicesservicetag.js";

export type Config = {
  dedupKeyEnabled: boolean;
};

export type V3ServicesServiceResponse = {
  id: string;
  name: string;
  slug: string;
  email: string;
  escalationPolicyId: string;
  organizationId: string;
  apiKey: string;
  description: string;
  depends?: Array<string> | null | undefined;
  /**
   * Represents the RBAC owner of an entity.
   */
  owner: CommonV3RBACOwner;
  onMaintenance?: boolean | undefined;
  slack?: V3ServicesServiceSlack | undefined;
  /**
   * Represents the basic details of an Escalation Policy for a service.
   */
  escalationPolicy?: V3ServicesEscalationPolicyBasic | undefined;
  jiraCloud?: V3ServicesJiraCloudExtension | undefined;
  maintainer: V3ServicesServiceMaintainer;
  tags: Array<V3ServicesServiceTag>;
  autoPauseTransientAlertsConfig: V3ServicesAPTAConfig;
  intelligentAlertsGroupingConfig: V3ServicesIAGConfig;
  delayNotificationConfig: V3ServicesNotificationDelayConfig;
  config: Config;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Config$inboundSchema: z.ZodType<Config, z.ZodTypeDef, unknown> = z
  .object({
    dedup_key_enabled: z.boolean(),
  }).transform((v) => {
    return remap$(v, {
      "dedup_key_enabled": "dedupKeyEnabled",
    });
  });

export function configFromJSON(
  jsonString: string,
): SafeParseResult<Config, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Config$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Config' from JSON`,
  );
}

/** @internal */
export const V3ServicesServiceResponse$inboundSchema: z.ZodType<
  V3ServicesServiceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  email: z.string(),
  escalation_policy_id: z.string(),
  organization_id: z.string(),
  api_key: z.string(),
  description: z.string(),
  depends: z.nullable(z.array(z.string())).optional(),
  owner: CommonV3RBACOwner$inboundSchema,
  on_maintenance: z.boolean().optional(),
  slack: V3ServicesServiceSlack$inboundSchema.optional(),
  escalation_policy: V3ServicesEscalationPolicyBasic$inboundSchema.optional(),
  jira_cloud: V3ServicesJiraCloudExtension$inboundSchema.optional(),
  maintainer: V3ServicesServiceMaintainer$inboundSchema,
  tags: z.array(V3ServicesServiceTag$inboundSchema),
  auto_pause_transient_alerts_config: V3ServicesAPTAConfig$inboundSchema,
  intelligent_alerts_grouping_config: V3ServicesIAGConfig$inboundSchema,
  delay_notification_config: V3ServicesNotificationDelayConfig$inboundSchema,
  config: z.lazy(() => Config$inboundSchema),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "escalation_policy_id": "escalationPolicyId",
    "organization_id": "organizationId",
    "api_key": "apiKey",
    "on_maintenance": "onMaintenance",
    "escalation_policy": "escalationPolicy",
    "jira_cloud": "jiraCloud",
    "auto_pause_transient_alerts_config": "autoPauseTransientAlertsConfig",
    "intelligent_alerts_grouping_config": "intelligentAlertsGroupingConfig",
    "delay_notification_config": "delayNotificationConfig",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function v3ServicesServiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesServiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesServiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesServiceResponse' from JSON`,
  );
}
