/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesNotificationDelayConfigFixedTimeslotConfig = {
  startTime?: string | undefined;
  endTime?: string | undefined;
  repeatDays?: Array<number> | undefined;
};

export type V3ServicesNotificationDelayConfigCustomTimeslots = {};

export type V3ServicesNotificationDelayConfigAssignedTo = {
  id?: string | undefined;
  type?: string | undefined;
};

export type V3ServicesNotificationDelayConfig = {
  isEnabled: boolean;
  timezone?: string | undefined;
  fixedTimeslotConfig?:
    | V3ServicesNotificationDelayConfigFixedTimeslotConfig
    | undefined;
  customTimeslotsEnabled?: boolean | undefined;
  customTimeslots?:
    | V3ServicesNotificationDelayConfigCustomTimeslots
    | undefined;
  assignedTo?: V3ServicesNotificationDelayConfigAssignedTo | undefined;
};

/** @internal */
export const V3ServicesNotificationDelayConfigFixedTimeslotConfig$inboundSchema:
  z.ZodType<
    V3ServicesNotificationDelayConfigFixedTimeslotConfig,
    z.ZodTypeDef,
    unknown
  > = z.object({
    start_time: z.string().optional(),
    end_time: z.string().optional(),
    repeat_days: z.array(z.number().int()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "start_time": "startTime",
      "end_time": "endTime",
      "repeat_days": "repeatDays",
    });
  });

export function v3ServicesNotificationDelayConfigFixedTimeslotConfigFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesNotificationDelayConfigFixedTimeslotConfig,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesNotificationDelayConfigFixedTimeslotConfig$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesNotificationDelayConfigFixedTimeslotConfig' from JSON`,
  );
}

/** @internal */
export const V3ServicesNotificationDelayConfigCustomTimeslots$inboundSchema:
  z.ZodType<
    V3ServicesNotificationDelayConfigCustomTimeslots,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function v3ServicesNotificationDelayConfigCustomTimeslotsFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesNotificationDelayConfigCustomTimeslots,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesNotificationDelayConfigCustomTimeslots$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesNotificationDelayConfigCustomTimeslots' from JSON`,
  );
}

/** @internal */
export const V3ServicesNotificationDelayConfigAssignedTo$inboundSchema:
  z.ZodType<
    V3ServicesNotificationDelayConfigAssignedTo,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    type: z.string().optional(),
  });

export function v3ServicesNotificationDelayConfigAssignedToFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesNotificationDelayConfigAssignedTo,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesNotificationDelayConfigAssignedTo$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesNotificationDelayConfigAssignedTo' from JSON`,
  );
}

/** @internal */
export const V3ServicesNotificationDelayConfig$inboundSchema: z.ZodType<
  V3ServicesNotificationDelayConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  is_enabled: z.boolean(),
  timezone: z.string().optional(),
  fixed_timeslot_config: z.lazy(() =>
    V3ServicesNotificationDelayConfigFixedTimeslotConfig$inboundSchema
  ).optional(),
  custom_timeslots_enabled: z.boolean().optional(),
  custom_timeslots: z.lazy(() =>
    V3ServicesNotificationDelayConfigCustomTimeslots$inboundSchema
  ).optional(),
  assigned_to: z.lazy(() =>
    V3ServicesNotificationDelayConfigAssignedTo$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "is_enabled": "isEnabled",
    "fixed_timeslot_config": "fixedTimeslotConfig",
    "custom_timeslots_enabled": "customTimeslotsEnabled",
    "custom_timeslots": "customTimeslots",
    "assigned_to": "assignedTo",
  });
});

export function v3ServicesNotificationDelayConfigFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesNotificationDelayConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesNotificationDelayConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesNotificationDelayConfig' from JSON`,
  );
}
