/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3ServicesOverlayDedupKeyOverlay,
  V3ServicesOverlayDedupKeyOverlay$inboundSchema,
} from "./v3servicesoverlaydedupkeyoverlay.js";

export const V3ServicesOverlayOverlayResponseOverlayTemplateType = {
  DedupKey: "dedup_key",
} as const;
export type V3ServicesOverlayOverlayResponseOverlayTemplateType = ClosedEnum<
  typeof V3ServicesOverlayOverlayResponseOverlayTemplateType
>;

export type V3ServicesOverlayOverlayResponse = {
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
  orgId: string;
  serviceId: string;
  alertSourceVersion: string;
  alertSourceShortname: string;
  overlayTemplateType: V3ServicesOverlayOverlayResponseOverlayTemplateType;
  overlay: V3ServicesOverlayDedupKeyOverlay;
  createdBy: string;
  updatedBy: string;
  alertSourceType: string;
};

/** @internal */
export const V3ServicesOverlayOverlayResponseOverlayTemplateType$inboundSchema:
  z.ZodNativeEnum<typeof V3ServicesOverlayOverlayResponseOverlayTemplateType> =
    z.nativeEnum(V3ServicesOverlayOverlayResponseOverlayTemplateType);

/** @internal */
export const V3ServicesOverlayOverlayResponse$inboundSchema: z.ZodType<
  V3ServicesOverlayOverlayResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
  org_id: z.string(),
  service_id: z.string(),
  alert_source_version: z.string(),
  alert_source_shortname: z.string(),
  overlay_template_type:
    V3ServicesOverlayOverlayResponseOverlayTemplateType$inboundSchema,
  overlay: V3ServicesOverlayDedupKeyOverlay$inboundSchema,
  created_by: z.string(),
  updated_by: z.string(),
  alert_source_type: z.string(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "deleted_at": "deletedAt",
    "org_id": "orgId",
    "service_id": "serviceId",
    "alert_source_version": "alertSourceVersion",
    "alert_source_shortname": "alertSourceShortname",
    "overlay_template_type": "overlayTemplateType",
    "created_by": "createdBy",
    "updated_by": "updatedBy",
    "alert_source_type": "alertSourceType",
  });
});

export function v3ServicesOverlayOverlayResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesOverlayOverlayResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesOverlayOverlayResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesOverlayOverlayResponse' from JSON`,
  );
}
