/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V3ServicesMaintenanceModeServiceMaintenance = {
  maintenanceStartDate: string;
  maintenanceEndDate?: string | undefined;
  daily: boolean;
  weekly: boolean;
  twoWeekly: boolean;
  threeWeekly: boolean;
  monthly: boolean;
  deleted: boolean;
  repeatTill: string;
};

/** @internal */
export type V3ServicesMaintenanceModeServiceMaintenance$Outbound = {
  maintenanceStartDate: string;
  maintenanceEndDate?: string | undefined;
  daily: boolean;
  weekly: boolean;
  twoWeekly: boolean;
  threeWeekly: boolean;
  monthly: boolean;
  deleted: boolean;
  repeatTill: string;
};

/** @internal */
export const V3ServicesMaintenanceModeServiceMaintenance$outboundSchema:
  z.ZodType<
    V3ServicesMaintenanceModeServiceMaintenance$Outbound,
    z.ZodTypeDef,
    V3ServicesMaintenanceModeServiceMaintenance
  > = z.object({
    maintenanceStartDate: z.string(),
    maintenanceEndDate: z.string().optional(),
    daily: z.boolean(),
    weekly: z.boolean(),
    twoWeekly: z.boolean(),
    threeWeekly: z.boolean(),
    monthly: z.boolean(),
    deleted: z.boolean(),
    repeatTill: z.string(),
  });

export function v3ServicesMaintenanceModeServiceMaintenanceToJSON(
  v3ServicesMaintenanceModeServiceMaintenance:
    V3ServicesMaintenanceModeServiceMaintenance,
): string {
  return JSON.stringify(
    V3ServicesMaintenanceModeServiceMaintenance$outboundSchema.parse(
      v3ServicesMaintenanceModeServiceMaintenance,
    ),
  );
}
