/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesExtensionsSlackExtensionResponse = {
  id: number;
  serviceId: string;
  organizationId: string;
  channelId: string;
  createdAt: string;
  name: string;
};

/** @internal */
export const V3ServicesExtensionsSlackExtensionResponse$inboundSchema:
  z.ZodType<V3ServicesExtensionsSlackExtensionResponse, z.ZodTypeDef, unknown> =
    z.object({
      id: z.number().int(),
      service_id: z.string(),
      organization_id: z.string(),
      channel_id: z.string(),
      created_at: z.string(),
      name: z.string(),
    }).transform((v) => {
      return remap$(v, {
        "service_id": "serviceId",
        "organization_id": "organizationId",
        "channel_id": "channelId",
        "created_at": "createdAt",
      });
    });

export function v3ServicesExtensionsSlackExtensionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesExtensionsSlackExtensionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesExtensionsSlackExtensionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesExtensionsSlackExtensionResponse' from JSON`,
  );
}
