/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesServiceSlack = {
  channelId: string;
  name: string;
  time: number;
};

/** @internal */
export const V3ServicesServiceSlack$inboundSchema: z.ZodType<
  V3ServicesServiceSlack,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  name: z.string(),
  time: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});

export function v3ServicesServiceSlackFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesServiceSlack, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesServiceSlack$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesServiceSlack' from JSON`,
  );
}
