/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  V3ServicesAPTAConfig,
  V3ServicesAPTAConfig$Outbound,
  V3ServicesAPTAConfig$outboundSchema,
} from "./v3servicesaptaconfig.js";
import {
  V3ServicesDedupInitConfig,
  V3ServicesDedupInitConfig$Outbound,
  V3ServicesDedupInitConfig$outboundSchema,
} from "./v3servicesdedupinitconfig.js";
import {
  V3ServicesIAGConfig,
  V3ServicesIAGConfig$Outbound,
  V3ServicesIAGConfig$outboundSchema,
} from "./v3servicesiagconfig.js";
import {
  V3ServicesNotificationDelayConfigRequest,
  V3ServicesNotificationDelayConfigRequest$Outbound,
  V3ServicesNotificationDelayConfigRequest$outboundSchema,
} from "./v3servicesnotificationdelayconfigrequest.js";
import {
  V3ServicesServiceMaintainer,
  V3ServicesServiceMaintainer$Outbound,
  V3ServicesServiceMaintainer$outboundSchema,
} from "./v3servicesservicemaintainer.js";
import {
  V3ServicesServiceTag,
  V3ServicesServiceTag$Outbound,
  V3ServicesServiceTag$outboundSchema,
} from "./v3servicesservicetag.js";

export type V3ServicesCreateServiceRequest = {
  name: string;
  escalationPolicyId: string;
  description?: string | undefined;
  emailPrefix?: string | undefined;
  maintainer?: V3ServicesServiceMaintainer | undefined;
  tags?: Array<V3ServicesServiceTag> | undefined;
  autoPauseTransientAlertsConfig?: V3ServicesAPTAConfig | undefined;
  intelligentAlertsGroupingConfig?: V3ServicesIAGConfig | undefined;
  delayNotificationConfig?:
    | V3ServicesNotificationDelayConfigRequest
    | undefined;
  dedupInitConfig?: V3ServicesDedupInitConfig | undefined;
};

/** @internal */
export type V3ServicesCreateServiceRequest$Outbound = {
  name: string;
  escalation_policy_id: string;
  description?: string | undefined;
  email_prefix?: string | undefined;
  maintainer?: V3ServicesServiceMaintainer$Outbound | undefined;
  tags?: Array<V3ServicesServiceTag$Outbound> | undefined;
  auto_pause_transient_alerts_config?:
    | V3ServicesAPTAConfig$Outbound
    | undefined;
  intelligent_alerts_grouping_config?: V3ServicesIAGConfig$Outbound | undefined;
  delay_notification_config?:
    | V3ServicesNotificationDelayConfigRequest$Outbound
    | undefined;
  dedup_init_config?: V3ServicesDedupInitConfig$Outbound | undefined;
};

/** @internal */
export const V3ServicesCreateServiceRequest$outboundSchema: z.ZodType<
  V3ServicesCreateServiceRequest$Outbound,
  z.ZodTypeDef,
  V3ServicesCreateServiceRequest
> = z.object({
  name: z.string(),
  escalationPolicyId: z.string(),
  description: z.string().optional(),
  emailPrefix: z.string().optional(),
  maintainer: V3ServicesServiceMaintainer$outboundSchema.optional(),
  tags: z.array(V3ServicesServiceTag$outboundSchema).optional(),
  autoPauseTransientAlertsConfig: V3ServicesAPTAConfig$outboundSchema
    .optional(),
  intelligentAlertsGroupingConfig: V3ServicesIAGConfig$outboundSchema
    .optional(),
  delayNotificationConfig:
    V3ServicesNotificationDelayConfigRequest$outboundSchema.optional(),
  dedupInitConfig: V3ServicesDedupInitConfig$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    escalationPolicyId: "escalation_policy_id",
    emailPrefix: "email_prefix",
    autoPauseTransientAlertsConfig: "auto_pause_transient_alerts_config",
    intelligentAlertsGroupingConfig: "intelligent_alerts_grouping_config",
    delayNotificationConfig: "delay_notification_config",
    dedupInitConfig: "dedup_init_config",
  });
});

export function v3ServicesCreateServiceRequestToJSON(
  v3ServicesCreateServiceRequest: V3ServicesCreateServiceRequest,
): string {
  return JSON.stringify(
    V3ServicesCreateServiceRequest$outboundSchema.parse(
      v3ServicesCreateServiceRequest,
    ),
  );
}
