/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type DedupKeyOverlay = {
  template: string;
  duration: number;
};

export type V3ServicesOverlayUpdateDedupKeyOverlayRequest = {
  overlayTemplateType: string;
  dedupKeyOverlay: DedupKeyOverlay;
};

/** @internal */
export type DedupKeyOverlay$Outbound = {
  template: string;
  duration: number;
};

/** @internal */
export const DedupKeyOverlay$outboundSchema: z.ZodType<
  DedupKeyOverlay$Outbound,
  z.ZodTypeDef,
  DedupKeyOverlay
> = z.object({
  template: z.string(),
  duration: z.number().int(),
});

export function dedupKeyOverlayToJSON(
  dedupKeyOverlay: DedupKeyOverlay,
): string {
  return JSON.stringify(DedupKeyOverlay$outboundSchema.parse(dedupKeyOverlay));
}

/** @internal */
export type V3ServicesOverlayUpdateDedupKeyOverlayRequest$Outbound = {
  overlay_template_type: string;
  dedup_key_overlay: DedupKeyOverlay$Outbound;
};

/** @internal */
export const V3ServicesOverlayUpdateDedupKeyOverlayRequest$outboundSchema:
  z.ZodType<
    V3ServicesOverlayUpdateDedupKeyOverlayRequest$Outbound,
    z.ZodTypeDef,
    V3ServicesOverlayUpdateDedupKeyOverlayRequest
  > = z.object({
    overlayTemplateType: z.string(),
    dedupKeyOverlay: z.lazy(() => DedupKeyOverlay$outboundSchema),
  }).transform((v) => {
    return remap$(v, {
      overlayTemplateType: "overlay_template_type",
      dedupKeyOverlay: "dedup_key_overlay",
    });
  });

export function v3ServicesOverlayUpdateDedupKeyOverlayRequestToJSON(
  v3ServicesOverlayUpdateDedupKeyOverlayRequest:
    V3ServicesOverlayUpdateDedupKeyOverlayRequest,
): string {
  return JSON.stringify(
    V3ServicesOverlayUpdateDedupKeyOverlayRequest$outboundSchema.parse(
      v3ServicesOverlayUpdateDedupKeyOverlayRequest,
    ),
  );
}
