/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3ServicesSuppressionRulesBasicExpression = {
  lhs: string;
  op: string;
  rhs: string;
};

/** @internal */
export const V3ServicesSuppressionRulesBasicExpression$inboundSchema: z.ZodType<
  V3ServicesSuppressionRulesBasicExpression,
  z.ZodTypeDef,
  unknown
> = z.object({
  lhs: z.string(),
  op: z.string(),
  rhs: z.string(),
});
/** @internal */
export type V3ServicesSuppressionRulesBasicExpression$Outbound = {
  lhs: string;
  op: string;
  rhs: string;
};

/** @internal */
export const V3ServicesSuppressionRulesBasicExpression$outboundSchema:
  z.ZodType<
    V3ServicesSuppressionRulesBasicExpression$Outbound,
    z.ZodTypeDef,
    V3ServicesSuppressionRulesBasicExpression
  > = z.object({
    lhs: z.string(),
    op: z.string(),
    rhs: z.string(),
  });

export function v3ServicesSuppressionRulesBasicExpressionToJSON(
  v3ServicesSuppressionRulesBasicExpression:
    V3ServicesSuppressionRulesBasicExpression,
): string {
  return JSON.stringify(
    V3ServicesSuppressionRulesBasicExpression$outboundSchema.parse(
      v3ServicesSuppressionRulesBasicExpression,
    ),
  );
}
export function v3ServicesSuppressionRulesBasicExpressionFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesSuppressionRulesBasicExpression,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesSuppressionRulesBasicExpression$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesSuppressionRulesBasicExpression' from JSON`,
  );
}
