/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3ServicesTaggingRulesExpressionBranchOp = {
  Is: "is",
  IsNot: "is_not",
  Matches: "matches",
  NotContains: "not_contains",
  Gt: "gt",
  Lt: "lt",
  GtEq: "gt_eq",
  LtEq: "lt_eq",
  Call: "call",
  FieldIs: "field_is",
  FieldIsNot: "field_is_not",
  FieldGt: "field_gt",
  FieldLt: "field_lt",
  FieldGtEq: "field_gt_eq",
  FieldLtEq: "field_lt_eq",
} as const;
export type V3ServicesTaggingRulesExpressionBranchOp = ClosedEnum<
  typeof V3ServicesTaggingRulesExpressionBranchOp
>;

export type V3ServicesTaggingRulesExpressionBranchRhs =
  | string
  | boolean
  | number
  | number;

export type V3ServicesTaggingRulesExpressionBranch = {
  lhs: string;
  op?: V3ServicesTaggingRulesExpressionBranchOp | undefined;
  rhs: string | boolean | number | number;
};

/** @internal */
export const V3ServicesTaggingRulesExpressionBranchOp$inboundSchema:
  z.ZodNativeEnum<typeof V3ServicesTaggingRulesExpressionBranchOp> = z
    .nativeEnum(V3ServicesTaggingRulesExpressionBranchOp);
/** @internal */
export const V3ServicesTaggingRulesExpressionBranchOp$outboundSchema:
  z.ZodNativeEnum<typeof V3ServicesTaggingRulesExpressionBranchOp> =
    V3ServicesTaggingRulesExpressionBranchOp$inboundSchema;

/** @internal */
export const V3ServicesTaggingRulesExpressionBranchRhs$inboundSchema: z.ZodType<
  V3ServicesTaggingRulesExpressionBranchRhs,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.boolean(), z.number().int(), z.number()]);
/** @internal */
export type V3ServicesTaggingRulesExpressionBranchRhs$Outbound =
  | string
  | boolean
  | number
  | number;

/** @internal */
export const V3ServicesTaggingRulesExpressionBranchRhs$outboundSchema:
  z.ZodType<
    V3ServicesTaggingRulesExpressionBranchRhs$Outbound,
    z.ZodTypeDef,
    V3ServicesTaggingRulesExpressionBranchRhs
  > = z.union([z.string(), z.boolean(), z.number().int(), z.number()]);

export function v3ServicesTaggingRulesExpressionBranchRhsToJSON(
  v3ServicesTaggingRulesExpressionBranchRhs:
    V3ServicesTaggingRulesExpressionBranchRhs,
): string {
  return JSON.stringify(
    V3ServicesTaggingRulesExpressionBranchRhs$outboundSchema.parse(
      v3ServicesTaggingRulesExpressionBranchRhs,
    ),
  );
}
export function v3ServicesTaggingRulesExpressionBranchRhsFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ServicesTaggingRulesExpressionBranchRhs,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesTaggingRulesExpressionBranchRhs$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3ServicesTaggingRulesExpressionBranchRhs' from JSON`,
  );
}

/** @internal */
export const V3ServicesTaggingRulesExpressionBranch$inboundSchema: z.ZodType<
  V3ServicesTaggingRulesExpressionBranch,
  z.ZodTypeDef,
  unknown
> = z.object({
  lhs: z.string(),
  op: V3ServicesTaggingRulesExpressionBranchOp$inboundSchema.optional(),
  rhs: z.union([z.string(), z.boolean(), z.number().int(), z.number()]),
});
/** @internal */
export type V3ServicesTaggingRulesExpressionBranch$Outbound = {
  lhs: string;
  op?: string | undefined;
  rhs: string | boolean | number | number;
};

/** @internal */
export const V3ServicesTaggingRulesExpressionBranch$outboundSchema: z.ZodType<
  V3ServicesTaggingRulesExpressionBranch$Outbound,
  z.ZodTypeDef,
  V3ServicesTaggingRulesExpressionBranch
> = z.object({
  lhs: z.string(),
  op: V3ServicesTaggingRulesExpressionBranchOp$outboundSchema.optional(),
  rhs: z.union([z.string(), z.boolean(), z.number().int(), z.number()]),
});

export function v3ServicesTaggingRulesExpressionBranchToJSON(
  v3ServicesTaggingRulesExpressionBranch:
    V3ServicesTaggingRulesExpressionBranch,
): string {
  return JSON.stringify(
    V3ServicesTaggingRulesExpressionBranch$outboundSchema.parse(
      v3ServicesTaggingRulesExpressionBranch,
    ),
  );
}
export function v3ServicesTaggingRulesExpressionBranchFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesTaggingRulesExpressionBranch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3ServicesTaggingRulesExpressionBranch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesTaggingRulesExpressionBranch' from JSON`,
  );
}
