/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3ServicesTaggingRulesTagConfigObject,
  V3ServicesTaggingRulesTagConfigObject$inboundSchema,
  V3ServicesTaggingRulesTagConfigObject$Outbound,
  V3ServicesTaggingRulesTagConfigObject$outboundSchema,
} from "./v3servicestaggingrulestagconfigobject.js";

export type V3ServicesTaggingRulesTagsObject = {
  severity?: V3ServicesTaggingRulesTagConfigObject | undefined;
};

/** @internal */
export const V3ServicesTaggingRulesTagsObject$inboundSchema: z.ZodType<
  V3ServicesTaggingRulesTagsObject,
  z.ZodTypeDef,
  unknown
> = z.object({
  severity: V3ServicesTaggingRulesTagConfigObject$inboundSchema.optional(),
});
/** @internal */
export type V3ServicesTaggingRulesTagsObject$Outbound = {
  severity?: V3ServicesTaggingRulesTagConfigObject$Outbound | undefined;
};

/** @internal */
export const V3ServicesTaggingRulesTagsObject$outboundSchema: z.ZodType<
  V3ServicesTaggingRulesTagsObject$Outbound,
  z.ZodTypeDef,
  V3ServicesTaggingRulesTagsObject
> = z.object({
  severity: V3ServicesTaggingRulesTagConfigObject$outboundSchema.optional(),
});

export function v3ServicesTaggingRulesTagsObjectToJSON(
  v3ServicesTaggingRulesTagsObject: V3ServicesTaggingRulesTagsObject,
): string {
  return JSON.stringify(
    V3ServicesTaggingRulesTagsObject$outboundSchema.parse(
      v3ServicesTaggingRulesTagsObject,
    ),
  );
}
export function v3ServicesTaggingRulesTagsObjectFromJSON(
  jsonString: string,
): SafeParseResult<V3ServicesTaggingRulesTagsObject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3ServicesTaggingRulesTagsObject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3ServicesTaggingRulesTagsObject' from JSON`,
  );
}
