/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3SLOSLOViolatingIncidentResponse = {
  id: number;
  ownerType: string;
  ownerId: string;
  orgId: string;
  sloId: number;
  incidentId: string;
  slis: Array<string>;
  errorBudgetSpent: number;
  isFalsePositive: boolean;
  startTime: Date;
  endTime: Date;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
};

/** @internal */
export const V3SLOSLOViolatingIncidentResponse$inboundSchema: z.ZodType<
  V3SLOSLOViolatingIncidentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  owner_type: z.string(),
  owner_id: z.string(),
  org_id: z.string(),
  slo_id: z.number().int(),
  incident_id: z.string(),
  slis: z.array(z.string()),
  error_budget_spent: z.number(),
  is_false_positive: z.boolean(),
  start_time: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  end_time: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ),
}).transform((v) => {
  return remap$(v, {
    "owner_type": "ownerType",
    "owner_id": "ownerId",
    "org_id": "orgId",
    "slo_id": "sloId",
    "incident_id": "incidentId",
    "error_budget_spent": "errorBudgetSpent",
    "is_false_positive": "isFalsePositive",
    "start_time": "startTime",
    "end_time": "endTime",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "deleted_at": "deletedAt",
  });
});

export function v3SLOSLOViolatingIncidentResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3SLOSLOViolatingIncidentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3SLOSLOViolatingIncidentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3SLOSLOViolatingIncidentResponse' from JSON`,
  );
}
