/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3SLOSLOMonitoringCheck = {
  id?: number | undefined;
  sloId?: number | undefined;
  name: string;
  threshold?: number | undefined;
  ownerType: string;
  ownerId: string;
  orgId?: string | undefined;
  isChecked?: boolean | null | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  deletedAt?: Date | null | undefined;
};

/** @internal */
export const V3SLOSLOMonitoringCheck$inboundSchema: z.ZodType<
  V3SLOSLOMonitoringCheck,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  slo_id: z.number().int().optional(),
  name: z.string(),
  threshold: z.number().int().optional(),
  owner_type: z.string(),
  owner_id: z.string(),
  org_id: z.string().optional(),
  is_checked: z.nullable(z.boolean()).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "slo_id": "sloId",
    "owner_type": "ownerType",
    "owner_id": "ownerId",
    "org_id": "orgId",
    "is_checked": "isChecked",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "deleted_at": "deletedAt",
  });
});
/** @internal */
export type V3SLOSLOMonitoringCheck$Outbound = {
  id?: number | undefined;
  slo_id?: number | undefined;
  name: string;
  threshold?: number | undefined;
  owner_type: string;
  owner_id: string;
  org_id?: string | undefined;
  is_checked?: boolean | null | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  deleted_at?: string | null | undefined;
};

/** @internal */
export const V3SLOSLOMonitoringCheck$outboundSchema: z.ZodType<
  V3SLOSLOMonitoringCheck$Outbound,
  z.ZodTypeDef,
  V3SLOSLOMonitoringCheck
> = z.object({
  id: z.number().int().optional(),
  sloId: z.number().int().optional(),
  name: z.string(),
  threshold: z.number().int().optional(),
  ownerType: z.string(),
  ownerId: z.string(),
  orgId: z.string().optional(),
  isChecked: z.nullable(z.boolean()).optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
  deletedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    sloId: "slo_id",
    ownerType: "owner_type",
    ownerId: "owner_id",
    orgId: "org_id",
    isChecked: "is_checked",
    createdAt: "created_at",
    updatedAt: "updated_at",
    deletedAt: "deleted_at",
  });
});

export function v3SLOSLOMonitoringCheckToJSON(
  v3SLOSLOMonitoringCheck: V3SLOSLOMonitoringCheck,
): string {
  return JSON.stringify(
    V3SLOSLOMonitoringCheck$outboundSchema.parse(v3SLOSLOMonitoringCheck),
  );
}
export function v3SLOSLOMonitoringCheckFromJSON(
  jsonString: string,
): SafeParseResult<V3SLOSLOMonitoringCheck, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3SLOSLOMonitoringCheck$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3SLOSLOMonitoringCheck' from JSON`,
  );
}
