/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { V3SloSlo, V3SloSlo$inboundSchema } from "./v3sloslo.js";

export type Insights = {
  errorBudgetConsumptionForPast30days: number;
};

export type V3SLOSLOWithInsightsResponse = {
  insights?: Insights | undefined;
  slo: V3SloSlo;
};

/** @internal */
export const Insights$inboundSchema: z.ZodType<
  Insights,
  z.ZodTypeDef,
  unknown
> = z.object({
  error_budget_consumption_for_past_30days: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "error_budget_consumption_for_past_30days":
      "errorBudgetConsumptionForPast30days",
  });
});

export function insightsFromJSON(
  jsonString: string,
): SafeParseResult<Insights, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Insights$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Insights' from JSON`,
  );
}

/** @internal */
export const V3SLOSLOWithInsightsResponse$inboundSchema: z.ZodType<
  V3SLOSLOWithInsightsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  insights: z.lazy(() => Insights$inboundSchema).optional(),
  slo: V3SloSlo$inboundSchema,
});

export function v3SLOSLOWithInsightsResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3SLOSLOWithInsightsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3SLOSLOWithInsightsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3SLOSLOWithInsightsResponse' from JSON`,
  );
}
