/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const V3SLOSLOActionType = {
  Service: "SERVICE",
  User: "USER",
  Squad: "SQUAD",
} as const;
export type V3SLOSLOActionType = ClosedEnum<typeof V3SLOSLOActionType>;

/** @internal */
export const V3SLOSLOActionType$inboundSchema: z.ZodNativeEnum<
  typeof V3SLOSLOActionType
> = z.nativeEnum(V3SLOSLOActionType);
/** @internal */
export const V3SLOSLOActionType$outboundSchema: z.ZodNativeEnum<
  typeof V3SLOSLOActionType
> = V3SLOSLOActionType$inboundSchema;
