/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type V3TeamsUpdateTeamMemberRequest = {
  /**
   * this field is required if you are using RBAC permission model
   */
  roleIds?: Array<string> | undefined;
  /**
   * this field is required if you are using OBAC permission model
   */
  role?: string | undefined;
};

/** @internal */
export type V3TeamsUpdateTeamMemberRequest$Outbound = {
  role_ids?: Array<string> | undefined;
  role?: string | undefined;
};

/** @internal */
export const V3TeamsUpdateTeamMemberRequest$outboundSchema: z.ZodType<
  V3TeamsUpdateTeamMemberRequest$Outbound,
  z.ZodTypeDef,
  V3TeamsUpdateTeamMemberRequest
> = z.object({
  roleIds: z.array(z.string()).optional(),
  role: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    roleIds: "role_ids",
  });
});

export function v3TeamsUpdateTeamMemberRequestToJSON(
  v3TeamsUpdateTeamMemberRequest: V3TeamsUpdateTeamMemberRequest,
): string {
  return JSON.stringify(
    V3TeamsUpdateTeamMemberRequest$outboundSchema.parse(
      v3TeamsUpdateTeamMemberRequest,
    ),
  );
}
