/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  V3TeamsAbilities,
  V3TeamsAbilities$Outbound,
  V3TeamsAbilities$outboundSchema,
} from "./v3teamsabilities.js";

export type V3TeamsUpdateTeamRoleRequest = {
  name?: string | undefined;
  abilities?: V3TeamsAbilities | undefined;
};

/** @internal */
export type V3TeamsUpdateTeamRoleRequest$Outbound = {
  name?: string | undefined;
  abilities?: V3TeamsAbilities$Outbound | undefined;
};

/** @internal */
export const V3TeamsUpdateTeamRoleRequest$outboundSchema: z.ZodType<
  V3TeamsUpdateTeamRoleRequest$Outbound,
  z.ZodTypeDef,
  V3TeamsUpdateTeamRoleRequest
> = z.object({
  name: z.string().optional(),
  abilities: V3TeamsAbilities$outboundSchema.optional(),
});

export function v3TeamsUpdateTeamRoleRequestToJSON(
  v3TeamsUpdateTeamRoleRequest: V3TeamsUpdateTeamRoleRequest,
): string {
  return JSON.stringify(
    V3TeamsUpdateTeamRoleRequest$outboundSchema.parse(
      v3TeamsUpdateTeamRoleRequest,
    ),
  );
}
