/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3TeamsTeamMember,
  V3TeamsTeamMember$inboundSchema,
} from "./v3teamsteammember.js";
import {
  V3TeamsTeamRole,
  V3TeamsTeamRole$inboundSchema,
} from "./v3teamsteamrole.js";

export type Organization = {
  id: string;
  name: string;
  slug: string;
};

export type V3TeamsTeamResponse = {
  id: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  organizationId: string;
  name: string;
  description: string;
  slug: string;
  members: Array<V3TeamsTeamMember>;
  roles: Array<V3TeamsTeamRole>;
  default: boolean;
  organization: Organization;
};

/** @internal */
export const Organization$inboundSchema: z.ZodType<
  Organization,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
});

export function organizationFromJSON(
  jsonString: string,
): SafeParseResult<Organization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Organization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Organization' from JSON`,
  );
}

/** @internal */
export const V3TeamsTeamResponse$inboundSchema: z.ZodType<
  V3TeamsTeamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  created_by: z.string(),
  organization_id: z.string(),
  name: z.string(),
  description: z.string(),
  slug: z.string(),
  members: z.array(V3TeamsTeamMember$inboundSchema),
  roles: z.array(V3TeamsTeamRole$inboundSchema),
  default: z.boolean(),
  organization: z.lazy(() => Organization$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "created_by": "createdBy",
    "organization_id": "organizationId",
  });
});

export function v3TeamsTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3TeamsTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3TeamsTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3TeamsTeamResponse' from JSON`,
  );
}
