/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  V3UsersGlobalRBACAbilityName,
  V3UsersGlobalRBACAbilityName$outboundSchema,
} from "./v3usersglobalrbacabilityname.js";

export type V3UsersUpdateUserAbilitiesRequestData = {
  userId: string;
  abilities: Array<V3UsersGlobalRBACAbilityName>;
};

export type V3UsersUpdateUserAbilitiesRequest = {
  data: Array<V3UsersUpdateUserAbilitiesRequestData>;
};

/** @internal */
export type V3UsersUpdateUserAbilitiesRequestData$Outbound = {
  user_id: string;
  abilities: Array<string>;
};

/** @internal */
export const V3UsersUpdateUserAbilitiesRequestData$outboundSchema: z.ZodType<
  V3UsersUpdateUserAbilitiesRequestData$Outbound,
  z.ZodTypeDef,
  V3UsersUpdateUserAbilitiesRequestData
> = z.object({
  userId: z.string(),
  abilities: z.array(V3UsersGlobalRBACAbilityName$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
  });
});

export function v3UsersUpdateUserAbilitiesRequestDataToJSON(
  v3UsersUpdateUserAbilitiesRequestData: V3UsersUpdateUserAbilitiesRequestData,
): string {
  return JSON.stringify(
    V3UsersUpdateUserAbilitiesRequestData$outboundSchema.parse(
      v3UsersUpdateUserAbilitiesRequestData,
    ),
  );
}

/** @internal */
export type V3UsersUpdateUserAbilitiesRequest$Outbound = {
  data: Array<V3UsersUpdateUserAbilitiesRequestData$Outbound>;
};

/** @internal */
export const V3UsersUpdateUserAbilitiesRequest$outboundSchema: z.ZodType<
  V3UsersUpdateUserAbilitiesRequest$Outbound,
  z.ZodTypeDef,
  V3UsersUpdateUserAbilitiesRequest
> = z.object({
  data: z.array(
    z.lazy(() => V3UsersUpdateUserAbilitiesRequestData$outboundSchema),
  ),
});

export function v3UsersUpdateUserAbilitiesRequestToJSON(
  v3UsersUpdateUserAbilitiesRequest: V3UsersUpdateUserAbilitiesRequest,
): string {
  return JSON.stringify(
    V3UsersUpdateUserAbilitiesRequest$outboundSchema.parse(
      v3UsersUpdateUserAbilitiesRequest,
    ),
  );
}
