/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3UsersContact = {
  dialCode: string;
  phoneNumber: string;
};

/** @internal */
export const V3UsersContact$inboundSchema: z.ZodType<
  V3UsersContact,
  z.ZodTypeDef,
  unknown
> = z.object({
  dial_code: z.string(),
  phone_number: z.string(),
}).transform((v) => {
  return remap$(v, {
    "dial_code": "dialCode",
    "phone_number": "phoneNumber",
  });
});

export function v3UsersContactFromJSON(
  jsonString: string,
): SafeParseResult<V3UsersContact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3UsersContact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3UsersContact' from JSON`,
  );
}
