/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3WebformsRecaptchaSecrets,
  V3WebformsRecaptchaSecrets$inboundSchema,
} from "./v3webformsrecaptchasecrets.js";
import {
  V3WebformsWFInputField,
  V3WebformsWFInputField$inboundSchema,
} from "./v3webformswfinputfield.js";
import {
  V3WebformsWFService,
  V3WebformsWFService$inboundSchema,
} from "./v3webformswfservice.js";

export type V3WebformsWebformResponseTags = {};

export type V3WebformsWebformResponse = {
  id: number;
  orgId: string;
  ownerId: string;
  name: string;
  isCname: boolean;
  publicUrl: string;
  hostName?: string | undefined;
  tags: V3WebformsWebformResponseTags;
  isCaptchaEnabled: boolean;
  captchaProvider: string;
  /**
   * reCAPTCHA credentials to be validated
   */
  captchaSecret: V3WebformsRecaptchaSecrets;
  formOwnerType: string;
  formOwnerId: string;
  formOwnerName: string;
  services: Array<V3WebformsWFService>;
  inputField: Array<V3WebformsWFInputField>;
  header: string;
  title: string;
  logoUrl?: string | undefined;
  footerText: string;
  footerLink: string;
  emailOn: Array<string>;
  description?: string | undefined;
  incidentCount: number;
  mttr: number;
  isDeleted: boolean;
  deletedAt: string;
};

/** @internal */
export const V3WebformsWebformResponseTags$inboundSchema: z.ZodType<
  V3WebformsWebformResponseTags,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function v3WebformsWebformResponseTagsFromJSON(
  jsonString: string,
): SafeParseResult<V3WebformsWebformResponseTags, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WebformsWebformResponseTags$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WebformsWebformResponseTags' from JSON`,
  );
}

/** @internal */
export const V3WebformsWebformResponse$inboundSchema: z.ZodType<
  V3WebformsWebformResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  org_id: z.string(),
  owner_id: z.string(),
  name: z.string(),
  is_cname: z.boolean(),
  public_url: z.string(),
  host_name: z.string().optional(),
  tags: z.lazy(() => V3WebformsWebformResponseTags$inboundSchema),
  is_captcha_enabled: z.boolean(),
  captcha_provider: z.string(),
  captcha_secret: V3WebformsRecaptchaSecrets$inboundSchema,
  form_owner_type: z.string(),
  form_owner_id: z.string(),
  form_owner_name: z.string(),
  services: z.array(V3WebformsWFService$inboundSchema),
  input_field: z.array(V3WebformsWFInputField$inboundSchema),
  header: z.string(),
  title: z.string(),
  logo_url: z.string().optional(),
  footer_text: z.string(),
  footer_link: z.string(),
  email_on: z.array(z.string()),
  description: z.string().optional(),
  incident_count: z.number().int(),
  mttr: z.number(),
  is_deleted: z.boolean(),
  deleted_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "org_id": "orgId",
    "owner_id": "ownerId",
    "is_cname": "isCname",
    "public_url": "publicUrl",
    "host_name": "hostName",
    "is_captcha_enabled": "isCaptchaEnabled",
    "captcha_provider": "captchaProvider",
    "captcha_secret": "captchaSecret",
    "form_owner_type": "formOwnerType",
    "form_owner_id": "formOwnerId",
    "form_owner_name": "formOwnerName",
    "input_field": "inputField",
    "logo_url": "logoUrl",
    "footer_text": "footerText",
    "footer_link": "footerLink",
    "email_on": "emailOn",
    "incident_count": "incidentCount",
    "is_deleted": "isDeleted",
    "deleted_at": "deletedAt",
  });
});

export function v3WebformsWebformResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3WebformsWebformResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WebformsWebformResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WebformsWebformResponse' from JSON`,
  );
}
