/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Service details for a webform
 */
export type V3WebformsWFService = {
  /**
   * Public identifier for the service
   */
  serviceId: string;
  /**
   * Service name as shown in UI
   */
  name: string;
  /**
   * Optional alias for the service
   */
  alias: string;
};

/** @internal */
export const V3WebformsWFService$inboundSchema: z.ZodType<
  V3WebformsWFService,
  z.ZodTypeDef,
  unknown
> = z.object({
  service_id: z.string(),
  name: z.string(),
  alias: z.string(),
}).transform((v) => {
  return remap$(v, {
    "service_id": "serviceId",
  });
});
/** @internal */
export type V3WebformsWFService$Outbound = {
  service_id: string;
  name: string;
  alias: string;
};

/** @internal */
export const V3WebformsWFService$outboundSchema: z.ZodType<
  V3WebformsWFService$Outbound,
  z.ZodTypeDef,
  V3WebformsWFService
> = z.object({
  serviceId: z.string(),
  name: z.string(),
  alias: z.string(),
}).transform((v) => {
  return remap$(v, {
    serviceId: "service_id",
  });
});

export function v3WebformsWFServiceToJSON(
  v3WebformsWFService: V3WebformsWFService,
): string {
  return JSON.stringify(
    V3WebformsWFService$outboundSchema.parse(v3WebformsWFService),
  );
}
export function v3WebformsWFServiceFromJSON(
  jsonString: string,
): SafeParseResult<V3WebformsWFService, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WebformsWFService$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WebformsWFService' from JSON`,
  );
}
