/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  V3WebformsRecaptchaSecrets,
  V3WebformsRecaptchaSecrets$Outbound,
  V3WebformsRecaptchaSecrets$outboundSchema,
} from "./v3webformsrecaptchasecrets.js";
import {
  V3WebformsWFInputField,
  V3WebformsWFInputField$Outbound,
  V3WebformsWFInputField$outboundSchema,
} from "./v3webformswfinputfield.js";
import {
  V3WebformsWFService,
  V3WebformsWFService$Outbound,
  V3WebformsWFService$outboundSchema,
} from "./v3webformswfservice.js";

/**
 * Key-value tags for the webform
 */
export type V3WebformsCreateOrUpdateWebformRequestTags = {};

/**
 * Public API request for creating a webform
 */
export type V3WebformsCreateOrUpdateWebformRequest = {
  /**
   * Unique identifier of the owner (string or UUID)
   */
  ownerId: string;
  /**
   * Name of the webform
   */
  name: string;
  /**
   * Indicates if a custom domain (CNAME) is used
   */
  isCname: boolean;
  /**
   * Custom hostname if CNAME is enabled
   */
  hostName?: string | undefined;
  /**
   * Key-value tags for the webform
   */
  tags?: V3WebformsCreateOrUpdateWebformRequestTags | undefined;
  /**
   * Whether CAPTCHA is enabled on the form
   */
  isCaptchaEnabled: boolean;
  /**
   * CAPTCHA credentials to be validated
   */
  captchaSecret: V3WebformsRecaptchaSecrets;
  /**
   * Entity type that owns the form (e.g., team, user)
   */
  formOwnerType: string;
  /**
   * Identifier for the owner entity
   */
  formOwnerId: string;
  /**
   * List of services tied to this webform
   */
  services: Array<V3WebformsWFService>;
  /**
   * Input fields to be rendered on the form
   */
  inputField?: Array<V3WebformsWFInputField> | undefined;
  /**
   * Header text shown on the form
   */
  header: string;
  /**
   * Title of the webform
   */
  title: string;
  /**
   * URL to the organization's logo
   */
  logoUrl?: string | undefined;
  /**
   * Text displayed in the footer
   */
  footerText: string;
  /**
   * Hyperlink in the footer (mailto or https)
   */
  footerLink: string;
  /**
   * Emails to notify on submission
   */
  emailOn?: Array<string> | undefined;
  /**
   * Optional description for the webform
   */
  description?: string | undefined;
};

/** @internal */
export type V3WebformsCreateOrUpdateWebformRequestTags$Outbound = {};

/** @internal */
export const V3WebformsCreateOrUpdateWebformRequestTags$outboundSchema:
  z.ZodType<
    V3WebformsCreateOrUpdateWebformRequestTags$Outbound,
    z.ZodTypeDef,
    V3WebformsCreateOrUpdateWebformRequestTags
  > = z.object({});

export function v3WebformsCreateOrUpdateWebformRequestTagsToJSON(
  v3WebformsCreateOrUpdateWebformRequestTags:
    V3WebformsCreateOrUpdateWebformRequestTags,
): string {
  return JSON.stringify(
    V3WebformsCreateOrUpdateWebformRequestTags$outboundSchema.parse(
      v3WebformsCreateOrUpdateWebformRequestTags,
    ),
  );
}

/** @internal */
export type V3WebformsCreateOrUpdateWebformRequest$Outbound = {
  owner_id: string;
  name: string;
  is_cname: boolean;
  host_name?: string | undefined;
  tags?: V3WebformsCreateOrUpdateWebformRequestTags$Outbound | undefined;
  is_captcha_enabled: boolean;
  captcha_secret: V3WebformsRecaptchaSecrets$Outbound;
  form_owner_type: string;
  form_owner_id: string;
  services: Array<V3WebformsWFService$Outbound>;
  input_field?: Array<V3WebformsWFInputField$Outbound> | undefined;
  header: string;
  title: string;
  logo_url?: string | undefined;
  footer_text: string;
  footer_link: string;
  email_on?: Array<string> | undefined;
  description?: string | undefined;
};

/** @internal */
export const V3WebformsCreateOrUpdateWebformRequest$outboundSchema: z.ZodType<
  V3WebformsCreateOrUpdateWebformRequest$Outbound,
  z.ZodTypeDef,
  V3WebformsCreateOrUpdateWebformRequest
> = z.object({
  ownerId: z.string(),
  name: z.string(),
  isCname: z.boolean(),
  hostName: z.string().optional(),
  tags: z.lazy(() => V3WebformsCreateOrUpdateWebformRequestTags$outboundSchema)
    .optional(),
  isCaptchaEnabled: z.boolean(),
  captchaSecret: V3WebformsRecaptchaSecrets$outboundSchema,
  formOwnerType: z.string(),
  formOwnerId: z.string(),
  services: z.array(V3WebformsWFService$outboundSchema),
  inputField: z.array(V3WebformsWFInputField$outboundSchema).optional(),
  header: z.string(),
  title: z.string(),
  logoUrl: z.string().optional(),
  footerText: z.string(),
  footerLink: z.string(),
  emailOn: z.array(z.string()).optional(),
  description: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    ownerId: "owner_id",
    isCname: "is_cname",
    hostName: "host_name",
    isCaptchaEnabled: "is_captcha_enabled",
    captchaSecret: "captcha_secret",
    formOwnerType: "form_owner_type",
    formOwnerId: "form_owner_id",
    inputField: "input_field",
    logoUrl: "logo_url",
    footerText: "footer_text",
    footerLink: "footer_link",
    emailOn: "email_on",
  });
});

export function v3WebformsCreateOrUpdateWebformRequestToJSON(
  v3WebformsCreateOrUpdateWebformRequest:
    V3WebformsCreateOrUpdateWebformRequest,
): string {
  return JSON.stringify(
    V3WebformsCreateOrUpdateWebformRequest$outboundSchema.parse(
      v3WebformsCreateOrUpdateWebformRequest,
    ),
  );
}
