/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3WorkflowsWorkflowAPIResponse,
  V3WorkflowsWorkflowAPIResponse$inboundSchema,
} from "./v3workflowsworkflowapiresponse.js";

export type Acl = {};

export type V3WorkflowsListWorkflowAPIResponseMeta = {
  totalCount: number;
  acl?: Acl | undefined;
};

export type V3WorkflowsListWorkflowAPIResponse = {
  data: Array<V3WorkflowsWorkflowAPIResponse>;
  meta: V3WorkflowsListWorkflowAPIResponseMeta;
};

/** @internal */
export const Acl$inboundSchema: z.ZodType<Acl, z.ZodTypeDef, unknown> = z
  .object({});

export function aclFromJSON(
  jsonString: string,
): SafeParseResult<Acl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Acl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Acl' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsListWorkflowAPIResponseMeta$inboundSchema: z.ZodType<
  V3WorkflowsListWorkflowAPIResponseMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  total_count: z.number().int(),
  acl: z.lazy(() => Acl$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function v3WorkflowsListWorkflowAPIResponseMetaFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsListWorkflowAPIResponseMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsListWorkflowAPIResponseMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsListWorkflowAPIResponseMeta' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsListWorkflowAPIResponse$inboundSchema: z.ZodType<
  V3WorkflowsListWorkflowAPIResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(V3WorkflowsWorkflowAPIResponse$inboundSchema),
  meta: z.lazy(() => V3WorkflowsListWorkflowAPIResponseMeta$inboundSchema),
});

export function v3WorkflowsListWorkflowAPIResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsListWorkflowAPIResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsListWorkflowAPIResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsListWorkflowAPIResponse' from JSON`,
  );
}
