/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3WorkflowsMsTeamsMessageUserName = {
  MsteamsMessageUser: "msteams_message_user",
} as const;
export type V3WorkflowsMsTeamsMessageUserName = ClosedEnum<
  typeof V3WorkflowsMsTeamsMessageUserName
>;

export type V3WorkflowsMsTeamsMessageUserData = {
  memberId: string;
  message: string;
};

export type V3WorkflowsMsTeamsMessageUser = {
  name: V3WorkflowsMsTeamsMessageUserName;
  data: V3WorkflowsMsTeamsMessageUserData;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageUserName$inboundSchema: z.ZodNativeEnum<
  typeof V3WorkflowsMsTeamsMessageUserName
> = z.nativeEnum(V3WorkflowsMsTeamsMessageUserName);
/** @internal */
export const V3WorkflowsMsTeamsMessageUserName$outboundSchema: z.ZodNativeEnum<
  typeof V3WorkflowsMsTeamsMessageUserName
> = V3WorkflowsMsTeamsMessageUserName$inboundSchema;

/** @internal */
export const V3WorkflowsMsTeamsMessageUserData$inboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageUserData,
  z.ZodTypeDef,
  unknown
> = z.object({
  member_id: z.string(),
  message: z.string(),
}).transform((v) => {
  return remap$(v, {
    "member_id": "memberId",
  });
});
/** @internal */
export type V3WorkflowsMsTeamsMessageUserData$Outbound = {
  member_id: string;
  message: string;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageUserData$outboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageUserData$Outbound,
  z.ZodTypeDef,
  V3WorkflowsMsTeamsMessageUserData
> = z.object({
  memberId: z.string(),
  message: z.string(),
}).transform((v) => {
  return remap$(v, {
    memberId: "member_id",
  });
});

export function v3WorkflowsMsTeamsMessageUserDataToJSON(
  v3WorkflowsMsTeamsMessageUserData: V3WorkflowsMsTeamsMessageUserData,
): string {
  return JSON.stringify(
    V3WorkflowsMsTeamsMessageUserData$outboundSchema.parse(
      v3WorkflowsMsTeamsMessageUserData,
    ),
  );
}
export function v3WorkflowsMsTeamsMessageUserDataFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsMsTeamsMessageUserData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsMsTeamsMessageUserData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsMsTeamsMessageUserData' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsMsTeamsMessageUser$inboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: V3WorkflowsMsTeamsMessageUserName$inboundSchema,
  data: z.lazy(() => V3WorkflowsMsTeamsMessageUserData$inboundSchema),
});
/** @internal */
export type V3WorkflowsMsTeamsMessageUser$Outbound = {
  name: string;
  data: V3WorkflowsMsTeamsMessageUserData$Outbound;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageUser$outboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageUser$Outbound,
  z.ZodTypeDef,
  V3WorkflowsMsTeamsMessageUser
> = z.object({
  name: V3WorkflowsMsTeamsMessageUserName$outboundSchema,
  data: z.lazy(() => V3WorkflowsMsTeamsMessageUserData$outboundSchema),
});

export function v3WorkflowsMsTeamsMessageUserToJSON(
  v3WorkflowsMsTeamsMessageUser: V3WorkflowsMsTeamsMessageUser,
): string {
  return JSON.stringify(
    V3WorkflowsMsTeamsMessageUser$outboundSchema.parse(
      v3WorkflowsMsTeamsMessageUser,
    ),
  );
}
export function v3WorkflowsMsTeamsMessageUserFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsMsTeamsMessageUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsMsTeamsMessageUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsMsTeamsMessageUser' from JSON`,
  );
}
