/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3WorkflowsMsTeamsMessageChannelName = {
  MsteamsMessageChannel: "msteams_message_channel",
} as const;
export type V3WorkflowsMsTeamsMessageChannelName = ClosedEnum<
  typeof V3WorkflowsMsTeamsMessageChannelName
>;

export type V3WorkflowsMsTeamsMessageChannelData = {
  channelId: string;
  message: string;
};

export type V3WorkflowsMsTeamsMessageChannel = {
  name: V3WorkflowsMsTeamsMessageChannelName;
  data: V3WorkflowsMsTeamsMessageChannelData;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageChannelName$inboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsMsTeamsMessageChannelName> = z.nativeEnum(
    V3WorkflowsMsTeamsMessageChannelName,
  );
/** @internal */
export const V3WorkflowsMsTeamsMessageChannelName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsMsTeamsMessageChannelName> =
    V3WorkflowsMsTeamsMessageChannelName$inboundSchema;

/** @internal */
export const V3WorkflowsMsTeamsMessageChannelData$inboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageChannelData,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  message: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
  });
});
/** @internal */
export type V3WorkflowsMsTeamsMessageChannelData$Outbound = {
  channel_id: string;
  message: string;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageChannelData$outboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageChannelData$Outbound,
  z.ZodTypeDef,
  V3WorkflowsMsTeamsMessageChannelData
> = z.object({
  channelId: z.string(),
  message: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
  });
});

export function v3WorkflowsMsTeamsMessageChannelDataToJSON(
  v3WorkflowsMsTeamsMessageChannelData: V3WorkflowsMsTeamsMessageChannelData,
): string {
  return JSON.stringify(
    V3WorkflowsMsTeamsMessageChannelData$outboundSchema.parse(
      v3WorkflowsMsTeamsMessageChannelData,
    ),
  );
}
export function v3WorkflowsMsTeamsMessageChannelDataFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsMsTeamsMessageChannelData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsMsTeamsMessageChannelData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsMsTeamsMessageChannelData' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsMsTeamsMessageChannel$inboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: V3WorkflowsMsTeamsMessageChannelName$inboundSchema,
  data: z.lazy(() => V3WorkflowsMsTeamsMessageChannelData$inboundSchema),
});
/** @internal */
export type V3WorkflowsMsTeamsMessageChannel$Outbound = {
  name: string;
  data: V3WorkflowsMsTeamsMessageChannelData$Outbound;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageChannel$outboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageChannel$Outbound,
  z.ZodTypeDef,
  V3WorkflowsMsTeamsMessageChannel
> = z.object({
  name: V3WorkflowsMsTeamsMessageChannelName$outboundSchema,
  data: z.lazy(() => V3WorkflowsMsTeamsMessageChannelData$outboundSchema),
});

export function v3WorkflowsMsTeamsMessageChannelToJSON(
  v3WorkflowsMsTeamsMessageChannel: V3WorkflowsMsTeamsMessageChannel,
): string {
  return JSON.stringify(
    V3WorkflowsMsTeamsMessageChannel$outboundSchema.parse(
      v3WorkflowsMsTeamsMessageChannel,
    ),
  );
}
export function v3WorkflowsMsTeamsMessageChannelFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsMsTeamsMessageChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsMsTeamsMessageChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsMsTeamsMessageChannel' from JSON`,
  );
}
