/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3WorkflowsCommunicationChannelType = {
  ChatRoom: "chat_room",
  VideoConference: "video_conference",
  Other: "other",
} as const;
export type V3WorkflowsCommunicationChannelType = ClosedEnum<
  typeof V3WorkflowsCommunicationChannelType
>;

export type V3WorkflowsCommunicationChannel = {
  displayText: string;
  link: string;
  type: V3WorkflowsCommunicationChannelType;
};

/** @internal */
export const V3WorkflowsCommunicationChannelType$inboundSchema: z.ZodNativeEnum<
  typeof V3WorkflowsCommunicationChannelType
> = z.nativeEnum(V3WorkflowsCommunicationChannelType);
/** @internal */
export const V3WorkflowsCommunicationChannelType$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsCommunicationChannelType> =
    V3WorkflowsCommunicationChannelType$inboundSchema;

/** @internal */
export const V3WorkflowsCommunicationChannel$inboundSchema: z.ZodType<
  V3WorkflowsCommunicationChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_text: z.string(),
  link: z.string(),
  type: V3WorkflowsCommunicationChannelType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "display_text": "displayText",
  });
});
/** @internal */
export type V3WorkflowsCommunicationChannel$Outbound = {
  display_text: string;
  link: string;
  type: string;
};

/** @internal */
export const V3WorkflowsCommunicationChannel$outboundSchema: z.ZodType<
  V3WorkflowsCommunicationChannel$Outbound,
  z.ZodTypeDef,
  V3WorkflowsCommunicationChannel
> = z.object({
  displayText: z.string(),
  link: z.string(),
  type: V3WorkflowsCommunicationChannelType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    displayText: "display_text",
  });
});

export function v3WorkflowsCommunicationChannelToJSON(
  v3WorkflowsCommunicationChannel: V3WorkflowsCommunicationChannel,
): string {
  return JSON.stringify(
    V3WorkflowsCommunicationChannel$outboundSchema.parse(
      v3WorkflowsCommunicationChannel,
    ),
  );
}
export function v3WorkflowsCommunicationChannelFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsCommunicationChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsCommunicationChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsCommunicationChannel' from JSON`,
  );
}
