/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type V3WorkflowsBulkEnableDisableWorkflowsRequest = {
  ownerId: string;
  enabled: boolean;
  workflowIds: Array<number>;
};

/** @internal */
export type V3WorkflowsBulkEnableDisableWorkflowsRequest$Outbound = {
  owner_id: string;
  enabled: boolean;
  workflow_ids: Array<number>;
};

/** @internal */
export const V3WorkflowsBulkEnableDisableWorkflowsRequest$outboundSchema:
  z.ZodType<
    V3WorkflowsBulkEnableDisableWorkflowsRequest$Outbound,
    z.ZodTypeDef,
    V3WorkflowsBulkEnableDisableWorkflowsRequest
  > = z.object({
    ownerId: z.string(),
    enabled: z.boolean(),
    workflowIds: z.array(z.number().int()),
  }).transform((v) => {
    return remap$(v, {
      ownerId: "owner_id",
      workflowIds: "workflow_ids",
    });
  });

export function v3WorkflowsBulkEnableDisableWorkflowsRequestToJSON(
  v3WorkflowsBulkEnableDisableWorkflowsRequest:
    V3WorkflowsBulkEnableDisableWorkflowsRequest,
): string {
  return JSON.stringify(
    V3WorkflowsBulkEnableDisableWorkflowsRequest$outboundSchema.parse(
      v3WorkflowsBulkEnableDisableWorkflowsRequest,
    ),
  );
}
