/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const V3WorkflowsUpdateIncidentPriorityUpdateName = {
  SqUpdateIncidentPriority: "sq_update_incident_priority",
} as const;
export type V3WorkflowsUpdateIncidentPriorityUpdateName = ClosedEnum<
  typeof V3WorkflowsUpdateIncidentPriorityUpdateName
>;

export const V3WorkflowsUpdateIncidentPriorityUpdatePriority = {
  P1: "P1",
  P2: "P2",
  P3: "P3",
  P4: "P4",
  P5: "P5",
  Unset: "UNSET",
} as const;
export type V3WorkflowsUpdateIncidentPriorityUpdatePriority = ClosedEnum<
  typeof V3WorkflowsUpdateIncidentPriorityUpdatePriority
>;

export type V3WorkflowsUpdateIncidentPriorityUpdateData = {
  priority?: V3WorkflowsUpdateIncidentPriorityUpdatePriority | undefined;
};

export type V3WorkflowsUpdateIncidentPriorityUpdate = {
  name: V3WorkflowsUpdateIncidentPriorityUpdateName;
  data?: V3WorkflowsUpdateIncidentPriorityUpdateData | undefined;
};

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdateName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsUpdateIncidentPriorityUpdateName> = z
    .nativeEnum(V3WorkflowsUpdateIncidentPriorityUpdateName);

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdatePriority$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsUpdateIncidentPriorityUpdatePriority> = z
    .nativeEnum(V3WorkflowsUpdateIncidentPriorityUpdatePriority);

/** @internal */
export type V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound = {
  priority?: string | undefined;
};

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema:
  z.ZodType<
    V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound,
    z.ZodTypeDef,
    V3WorkflowsUpdateIncidentPriorityUpdateData
  > = z.object({
    priority: V3WorkflowsUpdateIncidentPriorityUpdatePriority$outboundSchema
      .optional(),
  });

export function v3WorkflowsUpdateIncidentPriorityUpdateDataToJSON(
  v3WorkflowsUpdateIncidentPriorityUpdateData:
    V3WorkflowsUpdateIncidentPriorityUpdateData,
): string {
  return JSON.stringify(
    V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema.parse(
      v3WorkflowsUpdateIncidentPriorityUpdateData,
    ),
  );
}

/** @internal */
export type V3WorkflowsUpdateIncidentPriorityUpdate$Outbound = {
  name: string;
  data?: V3WorkflowsUpdateIncidentPriorityUpdateData$Outbound | undefined;
};

/** @internal */
export const V3WorkflowsUpdateIncidentPriorityUpdate$outboundSchema: z.ZodType<
  V3WorkflowsUpdateIncidentPriorityUpdate$Outbound,
  z.ZodTypeDef,
  V3WorkflowsUpdateIncidentPriorityUpdate
> = z.object({
  name: V3WorkflowsUpdateIncidentPriorityUpdateName$outboundSchema,
  data: z.lazy(() => V3WorkflowsUpdateIncidentPriorityUpdateData$outboundSchema)
    .optional(),
});

export function v3WorkflowsUpdateIncidentPriorityUpdateToJSON(
  v3WorkflowsUpdateIncidentPriorityUpdate:
    V3WorkflowsUpdateIncidentPriorityUpdate,
): string {
  return JSON.stringify(
    V3WorkflowsUpdateIncidentPriorityUpdate$outboundSchema.parse(
      v3WorkflowsUpdateIncidentPriorityUpdate,
    ),
  );
}
