/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V3WorkflowsIssueStatusAndMessage = {
  messages: Array<string>;
  statusId: number;
};

/** @internal */
export const V3WorkflowsIssueStatusAndMessage$inboundSchema: z.ZodType<
  V3WorkflowsIssueStatusAndMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  messages: z.array(z.string()),
  status_id: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "status_id": "statusId",
  });
});
/** @internal */
export type V3WorkflowsIssueStatusAndMessage$Outbound = {
  messages: Array<string>;
  status_id: number;
};

/** @internal */
export const V3WorkflowsIssueStatusAndMessage$outboundSchema: z.ZodType<
  V3WorkflowsIssueStatusAndMessage$Outbound,
  z.ZodTypeDef,
  V3WorkflowsIssueStatusAndMessage
> = z.object({
  messages: z.array(z.string()),
  statusId: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    statusId: "status_id",
  });
});

export function v3WorkflowsIssueStatusAndMessageToJSON(
  v3WorkflowsIssueStatusAndMessage: V3WorkflowsIssueStatusAndMessage,
): string {
  return JSON.stringify(
    V3WorkflowsIssueStatusAndMessage$outboundSchema.parse(
      v3WorkflowsIssueStatusAndMessage,
    ),
  );
}
export function v3WorkflowsIssueStatusAndMessageFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsIssueStatusAndMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsIssueStatusAndMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsIssueStatusAndMessage' from JSON`,
  );
}
