/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const V3WorkflowsSqMakeHTTPCallUpdateName = {
  SqMakeHttpCall: "sq_make_http_call",
} as const;
export type V3WorkflowsSqMakeHTTPCallUpdateName = ClosedEnum<
  typeof V3WorkflowsSqMakeHTTPCallUpdateName
>;

export const V3WorkflowsSqMakeHTTPCallUpdateMethod = {
  Get: "GET",
  Post: "POST",
  Put: "PUT",
  Patch: "PATCH",
  Delete: "DELETE",
} as const;
export type V3WorkflowsSqMakeHTTPCallUpdateMethod = ClosedEnum<
  typeof V3WorkflowsSqMakeHTTPCallUpdateMethod
>;

export type V3WorkflowsSqMakeHTTPCallUpdateHeader = {
  key: string;
  value: string;
};

export type V3WorkflowsSqMakeHTTPCallUpdateData = {
  method?: V3WorkflowsSqMakeHTTPCallUpdateMethod | undefined;
  url?: string | undefined;
  headers?: Array<V3WorkflowsSqMakeHTTPCallUpdateHeader> | undefined;
  body?: string | undefined;
};

export type V3WorkflowsSqMakeHTTPCallUpdate = {
  name: V3WorkflowsSqMakeHTTPCallUpdateName;
  data?: V3WorkflowsSqMakeHTTPCallUpdateData | undefined;
};

/** @internal */
export const V3WorkflowsSqMakeHTTPCallUpdateName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSqMakeHTTPCallUpdateName> = z.nativeEnum(
    V3WorkflowsSqMakeHTTPCallUpdateName,
  );

/** @internal */
export const V3WorkflowsSqMakeHTTPCallUpdateMethod$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSqMakeHTTPCallUpdateMethod> = z.nativeEnum(
    V3WorkflowsSqMakeHTTPCallUpdateMethod,
  );

/** @internal */
export type V3WorkflowsSqMakeHTTPCallUpdateHeader$Outbound = {
  key: string;
  value: string;
};

/** @internal */
export const V3WorkflowsSqMakeHTTPCallUpdateHeader$outboundSchema: z.ZodType<
  V3WorkflowsSqMakeHTTPCallUpdateHeader$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSqMakeHTTPCallUpdateHeader
> = z.object({
  key: z.string(),
  value: z.string(),
});

export function v3WorkflowsSqMakeHTTPCallUpdateHeaderToJSON(
  v3WorkflowsSqMakeHTTPCallUpdateHeader: V3WorkflowsSqMakeHTTPCallUpdateHeader,
): string {
  return JSON.stringify(
    V3WorkflowsSqMakeHTTPCallUpdateHeader$outboundSchema.parse(
      v3WorkflowsSqMakeHTTPCallUpdateHeader,
    ),
  );
}

/** @internal */
export type V3WorkflowsSqMakeHTTPCallUpdateData$Outbound = {
  method?: string | undefined;
  url?: string | undefined;
  headers?: Array<V3WorkflowsSqMakeHTTPCallUpdateHeader$Outbound> | undefined;
  body?: string | undefined;
};

/** @internal */
export const V3WorkflowsSqMakeHTTPCallUpdateData$outboundSchema: z.ZodType<
  V3WorkflowsSqMakeHTTPCallUpdateData$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSqMakeHTTPCallUpdateData
> = z.object({
  method: V3WorkflowsSqMakeHTTPCallUpdateMethod$outboundSchema.optional(),
  url: z.string().optional(),
  headers: z.array(
    z.lazy(() => V3WorkflowsSqMakeHTTPCallUpdateHeader$outboundSchema),
  ).optional(),
  body: z.string().optional(),
});

export function v3WorkflowsSqMakeHTTPCallUpdateDataToJSON(
  v3WorkflowsSqMakeHTTPCallUpdateData: V3WorkflowsSqMakeHTTPCallUpdateData,
): string {
  return JSON.stringify(
    V3WorkflowsSqMakeHTTPCallUpdateData$outboundSchema.parse(
      v3WorkflowsSqMakeHTTPCallUpdateData,
    ),
  );
}

/** @internal */
export type V3WorkflowsSqMakeHTTPCallUpdate$Outbound = {
  name: string;
  data?: V3WorkflowsSqMakeHTTPCallUpdateData$Outbound | undefined;
};

/** @internal */
export const V3WorkflowsSqMakeHTTPCallUpdate$outboundSchema: z.ZodType<
  V3WorkflowsSqMakeHTTPCallUpdate$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSqMakeHTTPCallUpdate
> = z.object({
  name: V3WorkflowsSqMakeHTTPCallUpdateName$outboundSchema,
  data: z.lazy(() => V3WorkflowsSqMakeHTTPCallUpdateData$outboundSchema)
    .optional(),
});

export function v3WorkflowsSqMakeHTTPCallUpdateToJSON(
  v3WorkflowsSqMakeHTTPCallUpdate: V3WorkflowsSqMakeHTTPCallUpdate,
): string {
  return JSON.stringify(
    V3WorkflowsSqMakeHTTPCallUpdate$outboundSchema.parse(
      v3WorkflowsSqMakeHTTPCallUpdate,
    ),
  );
}
