/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3WorkflowsCommunicationChannel,
  V3WorkflowsCommunicationChannel$inboundSchema,
  V3WorkflowsCommunicationChannel$Outbound,
  V3WorkflowsCommunicationChannel$outboundSchema,
} from "./v3workflowscommunicationchannel.js";

export const V3WorkflowsSqAddCommunicationChannelName = {
  SqAddCommunicationChannel: "sq_add_communication_channel",
} as const;
export type V3WorkflowsSqAddCommunicationChannelName = ClosedEnum<
  typeof V3WorkflowsSqAddCommunicationChannelName
>;

export type V3WorkflowsSqAddCommunicationChannelData = {
  channels: Array<V3WorkflowsCommunicationChannel>;
};

export type V3WorkflowsSqAddCommunicationChannel = {
  name: V3WorkflowsSqAddCommunicationChannelName;
  data: V3WorkflowsSqAddCommunicationChannelData;
};

/** @internal */
export const V3WorkflowsSqAddCommunicationChannelName$inboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSqAddCommunicationChannelName> = z
    .nativeEnum(V3WorkflowsSqAddCommunicationChannelName);
/** @internal */
export const V3WorkflowsSqAddCommunicationChannelName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSqAddCommunicationChannelName> =
    V3WorkflowsSqAddCommunicationChannelName$inboundSchema;

/** @internal */
export const V3WorkflowsSqAddCommunicationChannelData$inboundSchema: z.ZodType<
  V3WorkflowsSqAddCommunicationChannelData,
  z.ZodTypeDef,
  unknown
> = z.object({
  channels: z.array(V3WorkflowsCommunicationChannel$inboundSchema),
});
/** @internal */
export type V3WorkflowsSqAddCommunicationChannelData$Outbound = {
  channels: Array<V3WorkflowsCommunicationChannel$Outbound>;
};

/** @internal */
export const V3WorkflowsSqAddCommunicationChannelData$outboundSchema: z.ZodType<
  V3WorkflowsSqAddCommunicationChannelData$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSqAddCommunicationChannelData
> = z.object({
  channels: z.array(V3WorkflowsCommunicationChannel$outboundSchema),
});

export function v3WorkflowsSqAddCommunicationChannelDataToJSON(
  v3WorkflowsSqAddCommunicationChannelData:
    V3WorkflowsSqAddCommunicationChannelData,
): string {
  return JSON.stringify(
    V3WorkflowsSqAddCommunicationChannelData$outboundSchema.parse(
      v3WorkflowsSqAddCommunicationChannelData,
    ),
  );
}
export function v3WorkflowsSqAddCommunicationChannelDataFromJSON(
  jsonString: string,
): SafeParseResult<
  V3WorkflowsSqAddCommunicationChannelData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsSqAddCommunicationChannelData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3WorkflowsSqAddCommunicationChannelData' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsSqAddCommunicationChannel$inboundSchema: z.ZodType<
  V3WorkflowsSqAddCommunicationChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: V3WorkflowsSqAddCommunicationChannelName$inboundSchema,
  data: z.lazy(() => V3WorkflowsSqAddCommunicationChannelData$inboundSchema),
});
/** @internal */
export type V3WorkflowsSqAddCommunicationChannel$Outbound = {
  name: string;
  data: V3WorkflowsSqAddCommunicationChannelData$Outbound;
};

/** @internal */
export const V3WorkflowsSqAddCommunicationChannel$outboundSchema: z.ZodType<
  V3WorkflowsSqAddCommunicationChannel$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSqAddCommunicationChannel
> = z.object({
  name: V3WorkflowsSqAddCommunicationChannelName$outboundSchema,
  data: z.lazy(() => V3WorkflowsSqAddCommunicationChannelData$outboundSchema),
});

export function v3WorkflowsSqAddCommunicationChannelToJSON(
  v3WorkflowsSqAddCommunicationChannel: V3WorkflowsSqAddCommunicationChannel,
): string {
  return JSON.stringify(
    V3WorkflowsSqAddCommunicationChannel$outboundSchema.parse(
      v3WorkflowsSqAddCommunicationChannel,
    ),
  );
}
export function v3WorkflowsSqAddCommunicationChannelFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsSqAddCommunicationChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsSqAddCommunicationChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsSqAddCommunicationChannel' from JSON`,
  );
}
