/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const V3WorkflowsMsTeamsMessageChannelUpdateName = {
  MsteamsMessageChannel: "msteams_message_channel",
} as const;
export type V3WorkflowsMsTeamsMessageChannelUpdateName = ClosedEnum<
  typeof V3WorkflowsMsTeamsMessageChannelUpdateName
>;

export type V3WorkflowsMsTeamsMessageChannelUpdateData = {
  channelId?: string | undefined;
  message?: string | undefined;
};

export type V3WorkflowsMsTeamsMessageChannelUpdate = {
  name: V3WorkflowsMsTeamsMessageChannelUpdateName;
  data?: V3WorkflowsMsTeamsMessageChannelUpdateData | undefined;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageChannelUpdateName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsMsTeamsMessageChannelUpdateName> = z
    .nativeEnum(V3WorkflowsMsTeamsMessageChannelUpdateName);

/** @internal */
export type V3WorkflowsMsTeamsMessageChannelUpdateData$Outbound = {
  channel_id?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageChannelUpdateData$outboundSchema:
  z.ZodType<
    V3WorkflowsMsTeamsMessageChannelUpdateData$Outbound,
    z.ZodTypeDef,
    V3WorkflowsMsTeamsMessageChannelUpdateData
  > = z.object({
    channelId: z.string().optional(),
    message: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      channelId: "channel_id",
    });
  });

export function v3WorkflowsMsTeamsMessageChannelUpdateDataToJSON(
  v3WorkflowsMsTeamsMessageChannelUpdateData:
    V3WorkflowsMsTeamsMessageChannelUpdateData,
): string {
  return JSON.stringify(
    V3WorkflowsMsTeamsMessageChannelUpdateData$outboundSchema.parse(
      v3WorkflowsMsTeamsMessageChannelUpdateData,
    ),
  );
}

/** @internal */
export type V3WorkflowsMsTeamsMessageChannelUpdate$Outbound = {
  name: string;
  data?: V3WorkflowsMsTeamsMessageChannelUpdateData$Outbound | undefined;
};

/** @internal */
export const V3WorkflowsMsTeamsMessageChannelUpdate$outboundSchema: z.ZodType<
  V3WorkflowsMsTeamsMessageChannelUpdate$Outbound,
  z.ZodTypeDef,
  V3WorkflowsMsTeamsMessageChannelUpdate
> = z.object({
  name: V3WorkflowsMsTeamsMessageChannelUpdateName$outboundSchema,
  data: z.lazy(() => V3WorkflowsMsTeamsMessageChannelUpdateData$outboundSchema)
    .optional(),
});

export function v3WorkflowsMsTeamsMessageChannelUpdateToJSON(
  v3WorkflowsMsTeamsMessageChannelUpdate:
    V3WorkflowsMsTeamsMessageChannelUpdate,
): string {
  return JSON.stringify(
    V3WorkflowsMsTeamsMessageChannelUpdate$outboundSchema.parse(
      v3WorkflowsMsTeamsMessageChannelUpdate,
    ),
  );
}
