/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3WorkflowsActionResponse,
  V3WorkflowsActionResponse$inboundSchema,
} from "./v3workflowsactionresponse.js";
import {
  V3WorkflowsTag,
  V3WorkflowsTag$inboundSchema,
} from "./v3workflowstag.js";
import {
  V3WorkflowsWorkflowFilters,
  V3WorkflowsWorkflowFilters$inboundSchema,
} from "./v3workflowsworkflowfilters.js";

export type V3WorkflowsWorkflowAPIResponse = {
  id: number;
  ownerId: string;
  title: string;
  description: string;
  enabled: boolean;
  trigger: string;
  filters?: V3WorkflowsWorkflowFilters | undefined;
  tags: Array<V3WorkflowsTag>;
  actions: Array<V3WorkflowsActionResponse>;
  createdAt: string;
  createdBy: string;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const V3WorkflowsWorkflowAPIResponse$inboundSchema: z.ZodType<
  V3WorkflowsWorkflowAPIResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  owner_id: z.string(),
  title: z.string(),
  description: z.string(),
  enabled: z.boolean(),
  trigger: z.string(),
  filters: V3WorkflowsWorkflowFilters$inboundSchema.optional(),
  tags: z.array(V3WorkflowsTag$inboundSchema),
  actions: z.array(V3WorkflowsActionResponse$inboundSchema),
  created_at: z.string(),
  created_by: z.string(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "owner_id": "ownerId",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function v3WorkflowsWorkflowAPIResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsWorkflowAPIResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsWorkflowAPIResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsWorkflowAPIResponse' from JSON`,
  );
}
