/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const V3WorkflowsSlackMessageChannelName = {
  SlackMessageChannel: "slack_message_channel",
} as const;
export type V3WorkflowsSlackMessageChannelName = ClosedEnum<
  typeof V3WorkflowsSlackMessageChannelName
>;

export type V3WorkflowsSlackMessageChannelData = {
  channelId: string;
  channelName: string;
  message: string;
};

export type V3WorkflowsSlackMessageChannel = {
  name: V3WorkflowsSlackMessageChannelName;
  data: V3WorkflowsSlackMessageChannelData;
};

/** @internal */
export const V3WorkflowsSlackMessageChannelName$inboundSchema: z.ZodNativeEnum<
  typeof V3WorkflowsSlackMessageChannelName
> = z.nativeEnum(V3WorkflowsSlackMessageChannelName);
/** @internal */
export const V3WorkflowsSlackMessageChannelName$outboundSchema: z.ZodNativeEnum<
  typeof V3WorkflowsSlackMessageChannelName
> = V3WorkflowsSlackMessageChannelName$inboundSchema;

/** @internal */
export const V3WorkflowsSlackMessageChannelData$inboundSchema: z.ZodType<
  V3WorkflowsSlackMessageChannelData,
  z.ZodTypeDef,
  unknown
> = z.object({
  channel_id: z.string(),
  channel_name: z.string(),
  message: z.string(),
}).transform((v) => {
  return remap$(v, {
    "channel_id": "channelId",
    "channel_name": "channelName",
  });
});
/** @internal */
export type V3WorkflowsSlackMessageChannelData$Outbound = {
  channel_id: string;
  channel_name: string;
  message: string;
};

/** @internal */
export const V3WorkflowsSlackMessageChannelData$outboundSchema: z.ZodType<
  V3WorkflowsSlackMessageChannelData$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSlackMessageChannelData
> = z.object({
  channelId: z.string(),
  channelName: z.string(),
  message: z.string(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    channelName: "channel_name",
  });
});

export function v3WorkflowsSlackMessageChannelDataToJSON(
  v3WorkflowsSlackMessageChannelData: V3WorkflowsSlackMessageChannelData,
): string {
  return JSON.stringify(
    V3WorkflowsSlackMessageChannelData$outboundSchema.parse(
      v3WorkflowsSlackMessageChannelData,
    ),
  );
}
export function v3WorkflowsSlackMessageChannelDataFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsSlackMessageChannelData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsSlackMessageChannelData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsSlackMessageChannelData' from JSON`,
  );
}

/** @internal */
export const V3WorkflowsSlackMessageChannel$inboundSchema: z.ZodType<
  V3WorkflowsSlackMessageChannel,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: V3WorkflowsSlackMessageChannelName$inboundSchema,
  data: z.lazy(() => V3WorkflowsSlackMessageChannelData$inboundSchema),
});
/** @internal */
export type V3WorkflowsSlackMessageChannel$Outbound = {
  name: string;
  data: V3WorkflowsSlackMessageChannelData$Outbound;
};

/** @internal */
export const V3WorkflowsSlackMessageChannel$outboundSchema: z.ZodType<
  V3WorkflowsSlackMessageChannel$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSlackMessageChannel
> = z.object({
  name: V3WorkflowsSlackMessageChannelName$outboundSchema,
  data: z.lazy(() => V3WorkflowsSlackMessageChannelData$outboundSchema),
});

export function v3WorkflowsSlackMessageChannelToJSON(
  v3WorkflowsSlackMessageChannel: V3WorkflowsSlackMessageChannel,
): string {
  return JSON.stringify(
    V3WorkflowsSlackMessageChannel$outboundSchema.parse(
      v3WorkflowsSlackMessageChannel,
    ),
  );
}
export function v3WorkflowsSlackMessageChannelFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsSlackMessageChannel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3WorkflowsSlackMessageChannel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsSlackMessageChannel' from JSON`,
  );
}
