/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export const V3WorkflowsSlackMessageChannelUpdateName = {
  SlackMessageChannel: "slack_message_channel",
} as const;
export type V3WorkflowsSlackMessageChannelUpdateName = ClosedEnum<
  typeof V3WorkflowsSlackMessageChannelUpdateName
>;

export type V3WorkflowsSlackMessageChannelUpdateData = {
  channelId?: string | undefined;
  channelName?: string | undefined;
  message?: string | undefined;
};

export type V3WorkflowsSlackMessageChannelUpdate = {
  name: V3WorkflowsSlackMessageChannelUpdateName;
  data?: V3WorkflowsSlackMessageChannelUpdateData | undefined;
};

/** @internal */
export const V3WorkflowsSlackMessageChannelUpdateName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSlackMessageChannelUpdateName> = z
    .nativeEnum(V3WorkflowsSlackMessageChannelUpdateName);

/** @internal */
export type V3WorkflowsSlackMessageChannelUpdateData$Outbound = {
  channel_id?: string | undefined;
  channel_name?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export const V3WorkflowsSlackMessageChannelUpdateData$outboundSchema: z.ZodType<
  V3WorkflowsSlackMessageChannelUpdateData$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSlackMessageChannelUpdateData
> = z.object({
  channelId: z.string().optional(),
  channelName: z.string().optional(),
  message: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    channelId: "channel_id",
    channelName: "channel_name",
  });
});

export function v3WorkflowsSlackMessageChannelUpdateDataToJSON(
  v3WorkflowsSlackMessageChannelUpdateData:
    V3WorkflowsSlackMessageChannelUpdateData,
): string {
  return JSON.stringify(
    V3WorkflowsSlackMessageChannelUpdateData$outboundSchema.parse(
      v3WorkflowsSlackMessageChannelUpdateData,
    ),
  );
}

/** @internal */
export type V3WorkflowsSlackMessageChannelUpdate$Outbound = {
  name: string;
  data?: V3WorkflowsSlackMessageChannelUpdateData$Outbound | undefined;
};

/** @internal */
export const V3WorkflowsSlackMessageChannelUpdate$outboundSchema: z.ZodType<
  V3WorkflowsSlackMessageChannelUpdate$Outbound,
  z.ZodTypeDef,
  V3WorkflowsSlackMessageChannelUpdate
> = z.object({
  name: V3WorkflowsSlackMessageChannelUpdateName$outboundSchema,
  data: z.lazy(() => V3WorkflowsSlackMessageChannelUpdateData$outboundSchema)
    .optional(),
});

export function v3WorkflowsSlackMessageChannelUpdateToJSON(
  v3WorkflowsSlackMessageChannelUpdate: V3WorkflowsSlackMessageChannelUpdate,
): string {
  return JSON.stringify(
    V3WorkflowsSlackMessageChannelUpdate$outboundSchema.parse(
      v3WorkflowsSlackMessageChannelUpdate,
    ),
  );
}
