/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V3WorkflowsActionResponse,
  V3WorkflowsActionResponse$inboundSchema,
} from "./v3workflowsactionresponse.js";
import {
  V3WorkflowsTag,
  V3WorkflowsTag$inboundSchema,
} from "./v3workflowstag.js";
import {
  V3WorkflowsWorkflowFilters,
  V3WorkflowsWorkflowFilters$inboundSchema,
} from "./v3workflowsworkflowfilters.js";

export type V3WorkflowsUpdateWorkflowAPIResponse = {
  id?: number | undefined;
  ownerId?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  enabled?: boolean | undefined;
  trigger?: string | undefined;
  filters?: V3WorkflowsWorkflowFilters | undefined;
  tags?: Array<V3WorkflowsTag> | undefined;
  actions?: Array<V3WorkflowsActionResponse> | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const V3WorkflowsUpdateWorkflowAPIResponse$inboundSchema: z.ZodType<
  V3WorkflowsUpdateWorkflowAPIResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  owner_id: z.string().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  enabled: z.boolean().optional(),
  trigger: z.string().optional(),
  filters: V3WorkflowsWorkflowFilters$inboundSchema.optional(),
  tags: z.array(V3WorkflowsTag$inboundSchema).optional(),
  actions: z.array(V3WorkflowsActionResponse$inboundSchema).optional(),
  created_at: z.string().optional(),
  created_by: z.string().optional(),
  updated_at: z.string().optional(),
  updated_by: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "owner_id": "ownerId",
    "created_at": "createdAt",
    "created_by": "createdBy",
    "updated_at": "updatedAt",
    "updated_by": "updatedBy",
  });
});

export function v3WorkflowsUpdateWorkflowAPIResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3WorkflowsUpdateWorkflowAPIResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V3WorkflowsUpdateWorkflowAPIResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3WorkflowsUpdateWorkflowAPIResponse' from JSON`,
  );
}
