/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const V3WorkflowsSqMarkIncidentSLOAffectingUpdateName = {
  SqMarkIncidentSloAffecting: "sq_mark_incident_slo_affecting",
} as const;
export type V3WorkflowsSqMarkIncidentSLOAffectingUpdateName = ClosedEnum<
  typeof V3WorkflowsSqMarkIncidentSLOAffectingUpdateName
>;

export type V3WorkflowsSqMarkIncidentSLOAffectingUpdateData = {
  slis?: Array<string> | undefined;
  slo?: number | undefined;
};

export type V3WorkflowsSqMarkIncidentSLOAffectingUpdate = {
  name: V3WorkflowsSqMarkIncidentSLOAffectingUpdateName;
  data?: V3WorkflowsSqMarkIncidentSLOAffectingUpdateData | undefined;
};

/** @internal */
export const V3WorkflowsSqMarkIncidentSLOAffectingUpdateName$outboundSchema:
  z.ZodNativeEnum<typeof V3WorkflowsSqMarkIncidentSLOAffectingUpdateName> = z
    .nativeEnum(V3WorkflowsSqMarkIncidentSLOAffectingUpdateName);

/** @internal */
export type V3WorkflowsSqMarkIncidentSLOAffectingUpdateData$Outbound = {
  slis?: Array<string> | undefined;
  slo?: number | undefined;
};

/** @internal */
export const V3WorkflowsSqMarkIncidentSLOAffectingUpdateData$outboundSchema:
  z.ZodType<
    V3WorkflowsSqMarkIncidentSLOAffectingUpdateData$Outbound,
    z.ZodTypeDef,
    V3WorkflowsSqMarkIncidentSLOAffectingUpdateData
  > = z.object({
    slis: z.array(z.string()).optional(),
    slo: z.number().int().optional(),
  });

export function v3WorkflowsSqMarkIncidentSLOAffectingUpdateDataToJSON(
  v3WorkflowsSqMarkIncidentSLOAffectingUpdateData:
    V3WorkflowsSqMarkIncidentSLOAffectingUpdateData,
): string {
  return JSON.stringify(
    V3WorkflowsSqMarkIncidentSLOAffectingUpdateData$outboundSchema.parse(
      v3WorkflowsSqMarkIncidentSLOAffectingUpdateData,
    ),
  );
}

/** @internal */
export type V3WorkflowsSqMarkIncidentSLOAffectingUpdate$Outbound = {
  name: string;
  data?: V3WorkflowsSqMarkIncidentSLOAffectingUpdateData$Outbound | undefined;
};

/** @internal */
export const V3WorkflowsSqMarkIncidentSLOAffectingUpdate$outboundSchema:
  z.ZodType<
    V3WorkflowsSqMarkIncidentSLOAffectingUpdate$Outbound,
    z.ZodTypeDef,
    V3WorkflowsSqMarkIncidentSLOAffectingUpdate
  > = z.object({
    name: V3WorkflowsSqMarkIncidentSLOAffectingUpdateName$outboundSchema,
    data: z.lazy(() =>
      V3WorkflowsSqMarkIncidentSLOAffectingUpdateData$outboundSchema
    ).optional(),
  });

export function v3WorkflowsSqMarkIncidentSLOAffectingUpdateToJSON(
  v3WorkflowsSqMarkIncidentSLOAffectingUpdate:
    V3WorkflowsSqMarkIncidentSLOAffectingUpdate,
): string {
  return JSON.stringify(
    V3WorkflowsSqMarkIncidentSLOAffectingUpdate$outboundSchema.parse(
      v3WorkflowsSqMarkIncidentSLOAffectingUpdate,
    ),
  );
}
