/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";
import { V4Tag, V4Tag$Outbound, V4Tag$outboundSchema } from "./v4tag.js";

export const V4CreateScheduleRequestOwnerType = {
  User: "user",
  Squad: "squad",
} as const;
export type V4CreateScheduleRequestOwnerType = ClosedEnum<
  typeof V4CreateScheduleRequestOwnerType
>;

export type V4CreateScheduleRequest = {
  name: string;
  description: string;
  teamID: string;
  ownerID: string;
  ownerType: V4CreateScheduleRequestOwnerType;
  timeZone: string;
  tags: Array<V4Tag>;
};

/** @internal */
export const V4CreateScheduleRequestOwnerType$outboundSchema: z.ZodNativeEnum<
  typeof V4CreateScheduleRequestOwnerType
> = z.nativeEnum(V4CreateScheduleRequestOwnerType);

/** @internal */
export type V4CreateScheduleRequest$Outbound = {
  name: string;
  description: string;
  teamID: string;
  ownerID: string;
  ownerType: string;
  timeZone: string;
  tags: Array<V4Tag$Outbound>;
};

/** @internal */
export const V4CreateScheduleRequest$outboundSchema: z.ZodType<
  V4CreateScheduleRequest$Outbound,
  z.ZodTypeDef,
  V4CreateScheduleRequest
> = z.object({
  name: z.string(),
  description: z.string(),
  teamID: z.string(),
  ownerID: z.string(),
  ownerType: V4CreateScheduleRequestOwnerType$outboundSchema,
  timeZone: z.string(),
  tags: z.array(V4Tag$outboundSchema),
});

export function v4CreateScheduleRequestToJSON(
  v4CreateScheduleRequest: V4CreateScheduleRequest,
): string {
  return JSON.stringify(
    V4CreateScheduleRequest$outboundSchema.parse(v4CreateScheduleRequest),
  );
}
