/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V4OverrideParticipantGroup,
  V4OverrideParticipantGroup$inboundSchema,
} from "./v4overrideparticipantgroup.js";

export type V4OverrideResponse = {
  id: number;
  orgID: string;
  teamID: string;
  scheduleID: number;
  startTime: string;
  endTime: string;
  reason: string;
  overriddenParticipant: V4OverrideParticipantGroup;
  overrideWith: V4OverrideParticipantGroup;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const V4OverrideResponse$inboundSchema: z.ZodType<
  V4OverrideResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  orgID: z.string(),
  teamID: z.string(),
  scheduleID: z.number().int(),
  startTime: z.string(),
  endTime: z.string(),
  reason: z.string(),
  overriddenParticipant: V4OverrideParticipantGroup$inboundSchema,
  overrideWith: V4OverrideParticipantGroup$inboundSchema,
  createdAt: z.string(),
  updatedAt: z.string(),
});

export function v4OverrideResponseFromJSON(
  jsonString: string,
): SafeParseResult<V4OverrideResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V4OverrideResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4OverrideResponse' from JSON`,
  );
}
