/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V4Participant = {
  id: string;
  type: string;
};

/** @internal */
export const V4Participant$inboundSchema: z.ZodType<
  V4Participant,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string(),
});
/** @internal */
export type V4Participant$Outbound = {
  id: string;
  type: string;
};

/** @internal */
export const V4Participant$outboundSchema: z.ZodType<
  V4Participant$Outbound,
  z.ZodTypeDef,
  V4Participant
> = z.object({
  id: z.string(),
  type: z.string(),
});

export function v4ParticipantToJSON(v4Participant: V4Participant): string {
  return JSON.stringify(V4Participant$outboundSchema.parse(v4Participant));
}
export function v4ParticipantFromJSON(
  jsonString: string,
): SafeParseResult<V4Participant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V4Participant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4Participant' from JSON`,
  );
}
