/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V4ParticipantGroup,
  V4ParticipantGroup$inboundSchema,
} from "./v4participantgroup.js";
import {
  V4ShiftTimeSlot,
  V4ShiftTimeSlot$inboundSchema,
} from "./v4shifttimeslot.js";

export type V4RotationResponse = {
  id: number;
  name: string;
  scheduleID: number;
  color: string;
  startDate: string;
  period: string;
  customPeriodFrequency?: number | undefined;
  customPeriodUnit?: string | undefined;
  shiftTimeSlots?: Array<V4ShiftTimeSlot> | undefined;
  changeParticipantsFrequency: number;
  changeParticipantsUnit: string;
  endDate?: string | undefined;
  endsAfterIterations?: number | undefined;
  rotationParticipants?: Array<V4ParticipantGroup> | undefined;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const V4RotationResponse$inboundSchema: z.ZodType<
  V4RotationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  name: z.string(),
  scheduleID: z.number().int(),
  color: z.string(),
  startDate: z.string(),
  period: z.string(),
  customPeriodFrequency: z.number().int().optional(),
  customPeriodUnit: z.string().optional(),
  shiftTimeSlots: z.array(V4ShiftTimeSlot$inboundSchema).optional(),
  changeParticipantsFrequency: z.number().int(),
  changeParticipantsUnit: z.string(),
  endDate: z.string().optional(),
  endsAfterIterations: z.number().int().optional(),
  rotationParticipants: z.array(V4ParticipantGroup$inboundSchema).optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export function v4RotationResponseFromJSON(
  jsonString: string,
): SafeParseResult<V4RotationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V4RotationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4RotationResponse' from JSON`,
  );
}
