/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V4SquadsSquadMember = {
  userId: string;
  /**
   * this field is required if you are using OBAC permission model
   */
  role?: string | undefined;
};

/** @internal */
export const V4SquadsSquadMember$inboundSchema: z.ZodType<
  V4SquadsSquadMember,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
  role: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
  });
});
/** @internal */
export type V4SquadsSquadMember$Outbound = {
  user_id: string;
  role?: string | undefined;
};

/** @internal */
export const V4SquadsSquadMember$outboundSchema: z.ZodType<
  V4SquadsSquadMember$Outbound,
  z.ZodTypeDef,
  V4SquadsSquadMember
> = z.object({
  userId: z.string(),
  role: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
  });
});

export function v4SquadsSquadMemberToJSON(
  v4SquadsSquadMember: V4SquadsSquadMember,
): string {
  return JSON.stringify(
    V4SquadsSquadMember$outboundSchema.parse(v4SquadsSquadMember),
  );
}
export function v4SquadsSquadMemberFromJSON(
  jsonString: string,
): SafeParseResult<V4SquadsSquadMember, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V4SquadsSquadMember$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4SquadsSquadMember' from JSON`,
  );
}
