/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V4SquadsSquadMember,
  V4SquadsSquadMember$inboundSchema,
} from "./v4squadssquadmember.js";

export type V4SquadsCreateSquadResponse = {
  organizationId: string;
  ownerId: string;
  id: string;
  name: string;
  slug: string;
  members: Array<V4SquadsSquadMember>;
  createdAt: string;
  createdBy: string;
};

/** @internal */
export const V4SquadsCreateSquadResponse$inboundSchema: z.ZodType<
  V4SquadsCreateSquadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  organization_id: z.string(),
  owner_id: z.string(),
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  members: z.array(V4SquadsSquadMember$inboundSchema),
  created_at: z.string(),
  created_by: z.string(),
}).transform((v) => {
  return remap$(v, {
    "organization_id": "organizationId",
    "owner_id": "ownerId",
    "created_at": "createdAt",
    "created_by": "createdBy",
  });
});

export function v4SquadsCreateSquadResponseFromJSON(
  jsonString: string,
): SafeParseResult<V4SquadsCreateSquadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V4SquadsCreateSquadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4SquadsCreateSquadResponse' from JSON`,
  );
}
