/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V4StatusPagesComponentsCreateComponentRequest = {
  name: string;
  description?: string | undefined;
  allowSubscription?: boolean | undefined;
  groupID?: string | undefined;
  serviceID?: string | undefined;
};

/** @internal */
export type V4StatusPagesComponentsCreateComponentRequest$Outbound = {
  name: string;
  description?: string | undefined;
  allowSubscription?: boolean | undefined;
  groupID?: string | undefined;
  serviceID?: string | undefined;
};

/** @internal */
export const V4StatusPagesComponentsCreateComponentRequest$outboundSchema:
  z.ZodType<
    V4StatusPagesComponentsCreateComponentRequest$Outbound,
    z.ZodTypeDef,
    V4StatusPagesComponentsCreateComponentRequest
  > = z.object({
    name: z.string(),
    description: z.string().optional(),
    allowSubscription: z.boolean().optional(),
    groupID: z.string().optional(),
    serviceID: z.string().optional(),
  });

export function v4StatusPagesComponentsCreateComponentRequestToJSON(
  v4StatusPagesComponentsCreateComponentRequest:
    V4StatusPagesComponentsCreateComponentRequest,
): string {
  return JSON.stringify(
    V4StatusPagesComponentsCreateComponentRequest$outboundSchema.parse(
      v4StatusPagesComponentsCreateComponentRequest,
    ),
  );
}
