/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V4StatusPagesMaintenancesCreateMaintenanceResponse = {
  id: number;
  title: string;
  pageID: number;
  note: string;
  components?: Array<number> | undefined;
  startTime: Date;
  endTime: Date;
};

/** @internal */
export const V4StatusPagesMaintenancesCreateMaintenanceResponse$inboundSchema:
  z.ZodType<
    V4StatusPagesMaintenancesCreateMaintenanceResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.number().int(),
    title: z.string(),
    pageID: z.number().int(),
    note: z.string(),
    components: z.array(z.number().int()).optional(),
    startTime: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    endTime: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  });

export function v4StatusPagesMaintenancesCreateMaintenanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V4StatusPagesMaintenancesCreateMaintenanceResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V4StatusPagesMaintenancesCreateMaintenanceResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V4StatusPagesMaintenancesCreateMaintenanceResponse' from JSON`,
  );
}
