/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V4StatusPagesIssuesUpdateIssueRequestComponent = {
  id?: number | undefined;
  statusID?: number | undefined;
};

export type V4StatusPagesIssuesUpdateIssueRequestStateMessage = {
  text?: string | undefined;
  timestamp?: Date | undefined;
};

export type V4StatusPagesIssuesUpdateIssueRequestIssue = {
  stateID?: number | undefined;
  stateMessages?:
    | Array<V4StatusPagesIssuesUpdateIssueRequestStateMessage>
    | undefined;
};

export type V4StatusPagesIssuesUpdateIssueRequest = {
  title: string;
  statusID?: number | undefined;
  components: Array<V4StatusPagesIssuesUpdateIssueRequestComponent>;
  issues: Array<V4StatusPagesIssuesUpdateIssueRequestIssue>;
};

/** @internal */
export type V4StatusPagesIssuesUpdateIssueRequestComponent$Outbound = {
  id?: number | undefined;
  statusID?: number | undefined;
};

/** @internal */
export const V4StatusPagesIssuesUpdateIssueRequestComponent$outboundSchema:
  z.ZodType<
    V4StatusPagesIssuesUpdateIssueRequestComponent$Outbound,
    z.ZodTypeDef,
    V4StatusPagesIssuesUpdateIssueRequestComponent
  > = z.object({
    id: z.number().int().optional(),
    statusID: z.number().int().optional(),
  });

export function v4StatusPagesIssuesUpdateIssueRequestComponentToJSON(
  v4StatusPagesIssuesUpdateIssueRequestComponent:
    V4StatusPagesIssuesUpdateIssueRequestComponent,
): string {
  return JSON.stringify(
    V4StatusPagesIssuesUpdateIssueRequestComponent$outboundSchema.parse(
      v4StatusPagesIssuesUpdateIssueRequestComponent,
    ),
  );
}

/** @internal */
export type V4StatusPagesIssuesUpdateIssueRequestStateMessage$Outbound = {
  text?: string | undefined;
  timestamp?: string | undefined;
};

/** @internal */
export const V4StatusPagesIssuesUpdateIssueRequestStateMessage$outboundSchema:
  z.ZodType<
    V4StatusPagesIssuesUpdateIssueRequestStateMessage$Outbound,
    z.ZodTypeDef,
    V4StatusPagesIssuesUpdateIssueRequestStateMessage
  > = z.object({
    text: z.string().optional(),
    timestamp: z.date().transform(v => v.toISOString()).optional(),
  });

export function v4StatusPagesIssuesUpdateIssueRequestStateMessageToJSON(
  v4StatusPagesIssuesUpdateIssueRequestStateMessage:
    V4StatusPagesIssuesUpdateIssueRequestStateMessage,
): string {
  return JSON.stringify(
    V4StatusPagesIssuesUpdateIssueRequestStateMessage$outboundSchema.parse(
      v4StatusPagesIssuesUpdateIssueRequestStateMessage,
    ),
  );
}

/** @internal */
export type V4StatusPagesIssuesUpdateIssueRequestIssue$Outbound = {
  stateID?: number | undefined;
  stateMessages?:
    | Array<V4StatusPagesIssuesUpdateIssueRequestStateMessage$Outbound>
    | undefined;
};

/** @internal */
export const V4StatusPagesIssuesUpdateIssueRequestIssue$outboundSchema:
  z.ZodType<
    V4StatusPagesIssuesUpdateIssueRequestIssue$Outbound,
    z.ZodTypeDef,
    V4StatusPagesIssuesUpdateIssueRequestIssue
  > = z.object({
    stateID: z.number().int().optional(),
    stateMessages: z.array(
      z.lazy(() =>
        V4StatusPagesIssuesUpdateIssueRequestStateMessage$outboundSchema
      ),
    ).optional(),
  });

export function v4StatusPagesIssuesUpdateIssueRequestIssueToJSON(
  v4StatusPagesIssuesUpdateIssueRequestIssue:
    V4StatusPagesIssuesUpdateIssueRequestIssue,
): string {
  return JSON.stringify(
    V4StatusPagesIssuesUpdateIssueRequestIssue$outboundSchema.parse(
      v4StatusPagesIssuesUpdateIssueRequestIssue,
    ),
  );
}

/** @internal */
export type V4StatusPagesIssuesUpdateIssueRequest$Outbound = {
  title: string;
  statusID?: number | undefined;
  components: Array<V4StatusPagesIssuesUpdateIssueRequestComponent$Outbound>;
  issues: Array<V4StatusPagesIssuesUpdateIssueRequestIssue$Outbound>;
};

/** @internal */
export const V4StatusPagesIssuesUpdateIssueRequest$outboundSchema: z.ZodType<
  V4StatusPagesIssuesUpdateIssueRequest$Outbound,
  z.ZodTypeDef,
  V4StatusPagesIssuesUpdateIssueRequest
> = z.object({
  title: z.string(),
  statusID: z.number().int().optional(),
  components: z.array(
    z.lazy(() => V4StatusPagesIssuesUpdateIssueRequestComponent$outboundSchema),
  ),
  issues: z.array(
    z.lazy(() => V4StatusPagesIssuesUpdateIssueRequestIssue$outboundSchema),
  ),
});

export function v4StatusPagesIssuesUpdateIssueRequestToJSON(
  v4StatusPagesIssuesUpdateIssueRequest: V4StatusPagesIssuesUpdateIssueRequest,
): string {
  return JSON.stringify(
    V4StatusPagesIssuesUpdateIssueRequest$outboundSchema.parse(
      v4StatusPagesIssuesUpdateIssueRequest,
    ),
  );
}
