/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V4StatusPagesIssuesComponentStatus,
  V4StatusPagesIssuesComponentStatus$inboundSchema,
} from "./v4statuspagesissuescomponentstatus.js";
import {
  V4StatusPagesIssuesIssueStateMessage,
  V4StatusPagesIssuesIssueStateMessage$inboundSchema,
} from "./v4statuspagesissuesissuestatemessage.js";

export type V4StatusPagesIssuesIssueDetail = {
  state?: V4StatusPagesIssuesComponentStatus | undefined;
  stateMessages?: Array<V4StatusPagesIssuesIssueStateMessage> | undefined;
};

/** @internal */
export const V4StatusPagesIssuesIssueDetail$inboundSchema: z.ZodType<
  V4StatusPagesIssuesIssueDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  state: V4StatusPagesIssuesComponentStatus$inboundSchema.optional(),
  stateMessages: z.array(V4StatusPagesIssuesIssueStateMessage$inboundSchema)
    .optional(),
});

export function v4StatusPagesIssuesIssueDetailFromJSON(
  jsonString: string,
): SafeParseResult<V4StatusPagesIssuesIssueDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V4StatusPagesIssuesIssueDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4StatusPagesIssuesIssueDetail' from JSON`,
  );
}
