/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";
import {
  V4StatusPagesNewStatusPageComponentList,
  V4StatusPagesNewStatusPageComponentList$Outbound,
  V4StatusPagesNewStatusPageComponentList$outboundSchema,
} from "./v4statuspagesnewstatuspagecomponentlist.js";
import {
  V4StatusPagesNewStatusPageThemeColor,
  V4StatusPagesNewStatusPageThemeColor$Outbound,
  V4StatusPagesNewStatusPageThemeColor$outboundSchema,
} from "./v4statuspagesnewstatuspagethemecolor.js";

export const V4StatusPagesCreateStatusPageRequestOwnerType = {
  Team: "team",
  User: "user",
  Squad: "squad",
} as const;
export type V4StatusPagesCreateStatusPageRequestOwnerType = ClosedEnum<
  typeof V4StatusPagesCreateStatusPageRequestOwnerType
>;

export type V4StatusPagesCreateStatusPageRequest = {
  name: string;
  description?: string | undefined;
  isPublic?: boolean | undefined;
  domainName: string;
  customDomainName?: string | undefined;
  logoUrl: string;
  timezone: string;
  teamID: string;
  themeColor?: V4StatusPagesNewStatusPageThemeColor | undefined;
  components?: Array<V4StatusPagesNewStatusPageComponentList> | undefined;
  contactEmail: string;
  allowWebhookSubscription?: boolean | undefined;
  allowComponentsSubscription?: boolean | undefined;
  allowMaintenanceSubscription?: boolean | undefined;
  ownerType: V4StatusPagesCreateStatusPageRequestOwnerType;
  ownerID: string;
};

/** @internal */
export const V4StatusPagesCreateStatusPageRequestOwnerType$outboundSchema:
  z.ZodNativeEnum<typeof V4StatusPagesCreateStatusPageRequestOwnerType> = z
    .nativeEnum(V4StatusPagesCreateStatusPageRequestOwnerType);

/** @internal */
export type V4StatusPagesCreateStatusPageRequest$Outbound = {
  name: string;
  description?: string | undefined;
  isPublic?: boolean | undefined;
  domainName: string;
  customDomainName?: string | undefined;
  logoUrl: string;
  timezone: string;
  teamID: string;
  themeColor?: V4StatusPagesNewStatusPageThemeColor$Outbound | undefined;
  components?:
    | Array<V4StatusPagesNewStatusPageComponentList$Outbound>
    | undefined;
  contactEmail: string;
  allowWebhookSubscription?: boolean | undefined;
  allowComponentsSubscription?: boolean | undefined;
  allowMaintenanceSubscription?: boolean | undefined;
  ownerType: string;
  ownerID: string;
};

/** @internal */
export const V4StatusPagesCreateStatusPageRequest$outboundSchema: z.ZodType<
  V4StatusPagesCreateStatusPageRequest$Outbound,
  z.ZodTypeDef,
  V4StatusPagesCreateStatusPageRequest
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  isPublic: z.boolean().optional(),
  domainName: z.string(),
  customDomainName: z.string().optional(),
  logoUrl: z.string(),
  timezone: z.string(),
  teamID: z.string(),
  themeColor: V4StatusPagesNewStatusPageThemeColor$outboundSchema.optional(),
  components: z.array(V4StatusPagesNewStatusPageComponentList$outboundSchema)
    .optional(),
  contactEmail: z.string(),
  allowWebhookSubscription: z.boolean().optional(),
  allowComponentsSubscription: z.boolean().optional(),
  allowMaintenanceSubscription: z.boolean().optional(),
  ownerType: V4StatusPagesCreateStatusPageRequestOwnerType$outboundSchema,
  ownerID: z.string(),
});

export function v4StatusPagesCreateStatusPageRequestToJSON(
  v4StatusPagesCreateStatusPageRequest: V4StatusPagesCreateStatusPageRequest,
): string {
  return JSON.stringify(
    V4StatusPagesCreateStatusPageRequest$outboundSchema.parse(
      v4StatusPagesCreateStatusPageRequest,
    ),
  );
}
