/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  V4StatusPagesComponentGroupsComponentStatus,
  V4StatusPagesComponentGroupsComponentStatus$inboundSchema,
} from "./v4statuspagescomponentgroupscomponentstatus.js";

export type V4StatusPagesComponentGroupsComponent = {
  id?: number | undefined;
  type?: string | undefined;
  name?: string | undefined;
  allowSubscription?: boolean | undefined;
  description?: string | undefined;
  status?: V4StatusPagesComponentGroupsComponentStatus | undefined;
  underMaintenance?: boolean | undefined;
  statusMaintenance?: V4StatusPagesComponentGroupsComponentStatus | undefined;
  components?: Array<V4StatusPagesComponentGroupsComponent> | undefined;
  isHidden?: boolean | undefined;
};

/** @internal */
export const V4StatusPagesComponentGroupsComponent$inboundSchema: z.ZodType<
  V4StatusPagesComponentGroupsComponent,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  type: z.string().optional(),
  name: z.string().optional(),
  allowSubscription: z.boolean().optional(),
  description: z.string().optional(),
  status: V4StatusPagesComponentGroupsComponentStatus$inboundSchema.optional(),
  underMaintenance: z.boolean().optional(),
  statusMaintenance: V4StatusPagesComponentGroupsComponentStatus$inboundSchema
    .optional(),
  components: z.array(
    z.lazy(() => V4StatusPagesComponentGroupsComponent$inboundSchema),
  ).optional(),
  isHidden: z.boolean().optional(),
});

export function v4StatusPagesComponentGroupsComponentFromJSON(
  jsonString: string,
): SafeParseResult<V4StatusPagesComponentGroupsComponent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V4StatusPagesComponentGroupsComponent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4StatusPagesComponentGroupsComponent' from JSON`,
  );
}
