/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type V4StatusPagesGetStatusPageByIdResponseThemeColor = {
  primary: string;
  secondary: string;
};

export type V4StatusPagesGetStatusPageByIdResponse = {
  id: number;
  organizationID: string;
  name: string;
  isPublic: boolean;
  timezone: string;
  description?: string | undefined;
  domainName: string;
  customDomainName: string;
  contactEmail: string;
  themeColor: V4StatusPagesGetStatusPageByIdResponseThemeColor;
  allowComponentsSubscription: boolean;
  allowMaintenanceSubscription: boolean;
  allowWebhookSubscription: boolean;
  ownerType: string;
  ownerID: string;
  teamID: string;
};

/** @internal */
export const V4StatusPagesGetStatusPageByIdResponseThemeColor$inboundSchema:
  z.ZodType<
    V4StatusPagesGetStatusPageByIdResponseThemeColor,
    z.ZodTypeDef,
    unknown
  > = z.object({
    primary: z.string(),
    secondary: z.string(),
  });

export function v4StatusPagesGetStatusPageByIdResponseThemeColorFromJSON(
  jsonString: string,
): SafeParseResult<
  V4StatusPagesGetStatusPageByIdResponseThemeColor,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V4StatusPagesGetStatusPageByIdResponseThemeColor$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V4StatusPagesGetStatusPageByIdResponseThemeColor' from JSON`,
  );
}

/** @internal */
export const V4StatusPagesGetStatusPageByIdResponse$inboundSchema: z.ZodType<
  V4StatusPagesGetStatusPageByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int(),
  organizationID: z.string(),
  name: z.string(),
  isPublic: z.boolean(),
  timezone: z.string(),
  description: z.string().optional(),
  domainName: z.string(),
  customDomainName: z.string(),
  contactEmail: z.string(),
  themeColor: z.lazy(() =>
    V4StatusPagesGetStatusPageByIdResponseThemeColor$inboundSchema
  ),
  allowComponentsSubscription: z.boolean(),
  allowMaintenanceSubscription: z.boolean(),
  allowWebhookSubscription: z.boolean(),
  ownerType: z.string(),
  ownerID: z.string(),
  teamID: z.string(),
});

export function v4StatusPagesGetStatusPageByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<V4StatusPagesGetStatusPageByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V4StatusPagesGetStatusPageByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V4StatusPagesGetStatusPageByIdResponse' from JSON`,
  );
}
