/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V4StatusPagesMaintenancesCreateMaintenanceRequest = {
  title: string;
  note: string;
  components: Array<number>;
  startTime: Date;
  endTime: Date;
};

/** @internal */
export type V4StatusPagesMaintenancesCreateMaintenanceRequest$Outbound = {
  title: string;
  note: string;
  components: Array<number>;
  startTime: string;
  endTime: string;
};

/** @internal */
export const V4StatusPagesMaintenancesCreateMaintenanceRequest$outboundSchema:
  z.ZodType<
    V4StatusPagesMaintenancesCreateMaintenanceRequest$Outbound,
    z.ZodTypeDef,
    V4StatusPagesMaintenancesCreateMaintenanceRequest
  > = z.object({
    title: z.string(),
    note: z.string(),
    components: z.array(z.number().int()),
    startTime: z.date().transform(v => v.toISOString()),
    endTime: z.date().transform(v => v.toISOString()),
  });

export function v4StatusPagesMaintenancesCreateMaintenanceRequestToJSON(
  v4StatusPagesMaintenancesCreateMaintenanceRequest:
    V4StatusPagesMaintenancesCreateMaintenanceRequest,
): string {
  return JSON.stringify(
    V4StatusPagesMaintenancesCreateMaintenanceRequest$outboundSchema.parse(
      v4StatusPagesMaintenancesCreateMaintenanceRequest,
    ),
  );
}
