/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V4StatusPagesComponentGroupsCreateComponentGroupRequest = {
  name: string;
  description?: string | undefined;
  allowSubscription?: boolean | undefined;
};

/** @internal */
export type V4StatusPagesComponentGroupsCreateComponentGroupRequest$Outbound = {
  name: string;
  description?: string | undefined;
  allowSubscription?: boolean | undefined;
};

/** @internal */
export const V4StatusPagesComponentGroupsCreateComponentGroupRequest$outboundSchema:
  z.ZodType<
    V4StatusPagesComponentGroupsCreateComponentGroupRequest$Outbound,
    z.ZodTypeDef,
    V4StatusPagesComponentGroupsCreateComponentGroupRequest
  > = z.object({
    name: z.string(),
    description: z.string().optional(),
    allowSubscription: z.boolean().optional(),
  });

export function v4StatusPagesComponentGroupsCreateComponentGroupRequestToJSON(
  v4StatusPagesComponentGroupsCreateComponentGroupRequest:
    V4StatusPagesComponentGroupsCreateComponentGroupRequest,
): string {
  return JSON.stringify(
    V4StatusPagesComponentGroupsCreateComponentGroupRequest$outboundSchema
      .parse(v4StatusPagesComponentGroupsCreateComponentGroupRequest),
  );
}
