/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";
import { V4Tag, V4Tag$Outbound, V4Tag$outboundSchema } from "./v4tag.js";

export const V4UpdateScheduleRequestOwnerType = {
  User: "user",
  Squad: "squad",
} as const;
export type V4UpdateScheduleRequestOwnerType = ClosedEnum<
  typeof V4UpdateScheduleRequestOwnerType
>;

export type V4UpdateScheduleRequest = {
  name: string;
  description: string;
  ownerID: string;
  ownerType: V4UpdateScheduleRequestOwnerType;
  tags: Array<V4Tag>;
};

/** @internal */
export const V4UpdateScheduleRequestOwnerType$outboundSchema: z.ZodNativeEnum<
  typeof V4UpdateScheduleRequestOwnerType
> = z.nativeEnum(V4UpdateScheduleRequestOwnerType);

/** @internal */
export type V4UpdateScheduleRequest$Outbound = {
  name: string;
  description: string;
  ownerID: string;
  ownerType: string;
  tags: Array<V4Tag$Outbound>;
};

/** @internal */
export const V4UpdateScheduleRequest$outboundSchema: z.ZodType<
  V4UpdateScheduleRequest$Outbound,
  z.ZodTypeDef,
  V4UpdateScheduleRequest
> = z.object({
  name: z.string(),
  description: z.string(),
  ownerID: z.string(),
  ownerType: V4UpdateScheduleRequestOwnerType$outboundSchema,
  tags: z.array(V4Tag$outboundSchema),
});

export function v4UpdateScheduleRequestToJSON(
  v4UpdateScheduleRequest: V4UpdateScheduleRequest,
): string {
  return JSON.stringify(
    V4UpdateScheduleRequest$outboundSchema.parse(v4UpdateScheduleRequest),
  );
}
