/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  V4ParticipantGroup,
  V4ParticipantGroup$Outbound,
  V4ParticipantGroup$outboundSchema,
} from "./v4participantgroup.js";

export type V4UpdateRotationParticipantsRequest = {
  participantGroups: Array<V4ParticipantGroup>;
};

/** @internal */
export type V4UpdateRotationParticipantsRequest$Outbound = {
  participantGroups: Array<V4ParticipantGroup$Outbound>;
};

/** @internal */
export const V4UpdateRotationParticipantsRequest$outboundSchema: z.ZodType<
  V4UpdateRotationParticipantsRequest$Outbound,
  z.ZodTypeDef,
  V4UpdateRotationParticipantsRequest
> = z.object({
  participantGroups: z.array(V4ParticipantGroup$outboundSchema),
});

export function v4UpdateRotationParticipantsRequestToJSON(
  v4UpdateRotationParticipantsRequest: V4UpdateRotationParticipantsRequest,
): string {
  return JSON.stringify(
    V4UpdateRotationParticipantsRequest$outboundSchema.parse(
      v4UpdateRotationParticipantsRequest,
    ),
  );
}
